"""
Tests for P126A: Per-Strategy Controlled Apply Authorization Gate
Verifies the artifact generated by p126a_controlled_apply_authorization_gate.py
"""
import json
import sqlite3
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
ARTIFACT  = REPO_ROOT / "outputs/replay/p126a_controlled_apply_authorization_gate_20260528.json"
DB_PATH   = REPO_ROOT / "lottery_api/data/lottery_v2.db"
MD_PATH   = REPO_ROOT / "docs/replay/p126a_controlled_apply_authorization_gate_20260528.md"

EXPECTED_STRATEGIES = [
    "power_fourier_rhythm_2bet",
    "biglotto_echo_aware_3bet",
    "daily539_f4cold_3bet",
    "biglotto_ts3_markov_4bet_w30",
    "daily539_f4cold_5bet",
]


@pytest.fixture(scope="module")
def artifact():
    assert ARTIFACT.exists(), f"P126A artifact not found: {ARTIFACT}"
    with ARTIFACT.open() as f:
        return json.load(f)


@pytest.fixture(scope="module")
def md_content():
    assert MD_PATH.exists(), f"P126A markdown not found: {MD_PATH}"
    return MD_PATH.read_text()


# ---------------------------------------------------------------------------
# Classification & identity
# ---------------------------------------------------------------------------
class TestClassification:
    def test_task_id(self, artifact):
        assert artifact["task_id"] == "P126A"

    def test_classification(self, artifact):
        assert artifact["classification"] == "P126A_WAITING_FOR_PER_STRATEGY_APPLY_AUTHORIZATION"

    def test_generated_at(self, artifact):
        assert artifact["generated_at"]


# ---------------------------------------------------------------------------
# P129B source artifact
# ---------------------------------------------------------------------------
class TestP129BSource:
    def test_p129b_artifact_exists(self):
        p = REPO_ROOT / "outputs/replay/p129b_execute_bet_index_schema_migration_20260528.json"
        assert p.exists()

    def test_p129b_classification(self, artifact):
        assert artifact["p129b_source_summary"]["classification"] == "P129B_PRODUCTION_BET_INDEX_SCHEMA_MIGRATION_APPLIED"

    def test_p129b_classification_ok(self, artifact):
        assert artifact["p129b_source_summary"]["classification_ok"] is True

    def test_p129b_migration_ok(self, artifact):
        assert artifact["p129b_source_summary"]["migration_ok"] is True

    def test_p129b_backup_ok(self, artifact):
        assert artifact["p129b_source_summary"]["backup_ok"] is True

    def test_p129b_rows_after(self, artifact):
        assert artifact["p129b_source_summary"]["rows_after_migration"] == 54462

    def test_p129b_bet_index_present(self, artifact):
        assert artifact["p129b_source_summary"]["bet_index_present"] is True


# ---------------------------------------------------------------------------
# P126 source artifact
# ---------------------------------------------------------------------------
class TestP126Source:
    def test_p126_classification_ok(self, artifact):
        assert artifact["p126_source_summary"]["classification_ok"] is True

    def test_p126_candidate_count(self, artifact):
        assert artifact["p126_source_summary"]["candidate_count"] == 5

    def test_p126_estimated_rows(self, artifact):
        assert artifact["p126_source_summary"]["estimated_rows_from_p126"] == 18000

    def test_p126_total_new_rows(self, artifact):
        assert artifact["p126_source_summary"]["total_new_rows_if_all_applied"] == 18000

    def test_p126_total_after_all(self, artifact):
        assert artifact["p126_source_summary"]["total_replay_rows_after_all_applied"] == 72462


# ---------------------------------------------------------------------------
# DB snapshot: before / after — both must be 54462
# ---------------------------------------------------------------------------
class TestDbSnapshots:
    def test_rows_before(self, artifact):
        assert artifact["db_snapshot_before"]["replay_rows"] == 54462

    def test_rows_after(self, artifact):
        assert artifact["db_snapshot_after"]["replay_rows"] == 54462

    def test_bet_index_before(self, artifact):
        assert artifact["db_snapshot_before"]["has_bet_index_column"] is True

    def test_bet_index_after(self, artifact):
        assert artifact["db_snapshot_after"]["has_bet_index_column"] is True

    def test_new_unique_before(self, artifact):
        assert artifact["db_snapshot_before"]["has_new_unique_constraint"] is True

    def test_new_unique_after(self, artifact):
        assert artifact["db_snapshot_after"]["has_new_unique_constraint"] is True

    def test_columns_count_before(self, artifact):
        assert artifact["db_snapshot_before"]["columns_count"] == 28

    def test_columns_count_after(self, artifact):
        assert artifact["db_snapshot_after"]["columns_count"] == 28


# ---------------------------------------------------------------------------
# Schema readiness
# ---------------------------------------------------------------------------
class TestSchemaReadiness:
    def test_bet_index_present(self, artifact):
        assert artifact["schema_readiness"]["bet_index_column_present"] is True

    def test_unique_constraint_ready(self, artifact):
        assert artifact["schema_readiness"]["unique_constraint_ready"] is True

    def test_p129b_completed(self, artifact):
        assert artifact["schema_readiness"]["p129b_completed"] is True

    def test_production_rows(self, artifact):
        assert artifact["schema_readiness"]["production_rows"] == 54462


# ---------------------------------------------------------------------------
# Per-strategy authorization gates — exactly 5
# ---------------------------------------------------------------------------
class TestPerStrategyGates:
    def _gates(self, artifact):
        return artifact["per_strategy_authorization_gates"]

    def test_exactly_5_gates(self, artifact):
        assert len(self._gates(artifact)) == 5

    def test_all_strategy_ids_present(self, artifact):
        ids = {g["strategy_id"] for g in self._gates(artifact)}
        assert ids == set(EXPECTED_STRATEGIES)

    def test_all_authorization_absent(self, artifact):
        for g in self._gates(artifact):
            assert g["authorization_present"] is False, f"{g['strategy_id']} should be unauthorized"

    def test_all_apply_disallowed(self, artifact):
        for g in self._gates(artifact):
            assert g["apply_allowed"] is False, f"{g['strategy_id']} should not be allowed"

    def test_all_have_authorization_phrase(self, artifact):
        for g in self._gates(artifact):
            assert g["authorization_phrase"]
            assert "YES authorize controlled_apply for" in g["authorization_phrase"]
            assert g["strategy_id"] in g["authorization_phrase"]

    def test_phrases_not_resolved(self, artifact):
        for g in self._gates(artifact):
            phrase = g["authorization_phrase"]
            assert "<reason>" in phrase, f"Phrase should still contain placeholder: {phrase}"

    def test_all_have_recommended_order(self, artifact):
        orders = {g["recommended_order"] for g in self._gates(artifact)}
        assert orders == {1, 2, 3, 4, 5}

    def test_all_have_expected_insert_rows(self, artifact):
        for g in self._gates(artifact):
            assert g["expected_insert_rows"] > 0

    def test_all_have_missing_bet_indices(self, artifact):
        for g in self._gates(artifact):
            assert len(g["missing_bet_indices"]) > 0

    def test_all_have_lottery_type(self, artifact):
        for g in self._gates(artifact):
            assert g["lottery_type"] in {"POWER_LOTTO", "BIG_LOTTO", "DAILY_539"}

    def test_all_have_target_bet_count(self, artifact):
        for g in self._gates(artifact):
            assert g["target_bet_count"] >= 2

    def test_all_have_risk_level(self, artifact):
        for g in self._gates(artifact):
            assert g["risk_level"]

    # Strategy-specific checks
    def test_power_fourier_2bet(self, artifact):
        g = next(x for x in self._gates(artifact) if x["strategy_id"] == "power_fourier_rhythm_2bet")
        assert g["lottery_type"] == "POWER_LOTTO"
        assert g["target_bet_count"] == 2
        assert g["expected_insert_rows"] == 1500
        assert g["missing_bet_indices"] == [2]
        assert g["recommended_order"] == 1

    def test_biglotto_echo_3bet(self, artifact):
        g = next(x for x in self._gates(artifact) if x["strategy_id"] == "biglotto_echo_aware_3bet")
        assert g["lottery_type"] == "BIG_LOTTO"
        assert g["target_bet_count"] == 3
        assert g["expected_insert_rows"] == 3000
        assert 2 in g["missing_bet_indices"] and 3 in g["missing_bet_indices"]

    def test_daily539_f4cold_3bet(self, artifact):
        g = next(x for x in self._gates(artifact) if x["strategy_id"] == "daily539_f4cold_3bet")
        assert g["lottery_type"] == "DAILY_539"
        assert g["target_bet_count"] == 3
        assert g["expected_insert_rows"] == 3000

    def test_biglotto_ts3_4bet(self, artifact):
        g = next(x for x in self._gates(artifact) if x["strategy_id"] == "biglotto_ts3_markov_4bet_w30")
        assert g["lottery_type"] == "BIG_LOTTO"
        assert g["target_bet_count"] == 4
        assert g["expected_insert_rows"] == 4500

    def test_daily539_f4cold_5bet(self, artifact):
        g = next(x for x in self._gates(artifact) if x["strategy_id"] == "daily539_f4cold_5bet")
        assert g["lottery_type"] == "DAILY_539"
        assert g["target_bet_count"] == 5
        assert g["expected_insert_rows"] == 6000
        assert g["recommended_order"] == 5

    def test_total_expected_rows_18000(self, artifact):
        total = sum(g["expected_insert_rows"] for g in self._gates(artifact))
        assert total == 18000


# ---------------------------------------------------------------------------
# Required authorization phrases
# ---------------------------------------------------------------------------
class TestRequiredPhrases:
    def test_exactly_5_phrases(self, artifact):
        assert len(artifact["required_authorization_phrases"]) == 5

    def test_power_fourier_phrase(self, artifact):
        phrases = artifact["required_authorization_phrases"]
        assert any("power_fourier_rhythm_2bet" in p for p in phrases)

    def test_biglotto_echo_phrase(self, artifact):
        phrases = artifact["required_authorization_phrases"]
        assert any("biglotto_echo_aware_3bet" in p for p in phrases)

    def test_daily539_f4cold_3bet_phrase(self, artifact):
        phrases = artifact["required_authorization_phrases"]
        assert any("daily539_f4cold_3bet" in p for p in phrases)

    def test_biglotto_ts3_phrase(self, artifact):
        phrases = artifact["required_authorization_phrases"]
        assert any("biglotto_ts3_markov_4bet_w30" in p for p in phrases)

    def test_daily539_f4cold_5bet_phrase(self, artifact):
        phrases = artifact["required_authorization_phrases"]
        assert any("daily539_f4cold_5bet" in p for p in phrases)

    def test_all_phrases_have_prefix(self, artifact):
        for p in artifact["required_authorization_phrases"]:
            assert p.startswith("YES authorize controlled_apply for ")

    def test_all_phrases_have_placeholder(self, artifact):
        for p in artifact["required_authorization_phrases"]:
            assert "<reason>" in p


# ---------------------------------------------------------------------------
# No apply executed
# ---------------------------------------------------------------------------
class TestNoApply:
    def test_apply_execution_performed_false(self, artifact):
        assert artifact["apply_execution_performed"] is False

    def test_replay_rows_inserted_zero(self, artifact):
        assert artifact["replay_rows_inserted"] == 0

    def test_summary_apply_false(self, artifact):
        assert artifact["summary"]["apply_execution_performed"] is False

    def test_summary_rows_inserted_zero(self, artifact):
        assert artifact["summary"]["replay_rows_inserted"] == 0

    def test_rows_unchanged(self, artifact):
        assert artifact["summary"]["rows_before"] == artifact["summary"]["rows_after"] == 54462


# ---------------------------------------------------------------------------
# Blocked or excluded
# ---------------------------------------------------------------------------
class TestBlockedOrExcluded:
    def _items(self, artifact):
        return {b["item"] for b in artifact["blocked_or_excluded"]}

    def test_4_star_excluded(self, artifact):
        assert "4_STAR" in self._items(artifact)

    def test_p108_excluded(self, artifact):
        assert "P108" in self._items(artifact)

    def test_p117_excluded(self, artifact):
        assert "P117" in self._items(artifact)

    def test_p118_excluded(self, artifact):
        assert "P118" in self._items(artifact)

    def test_rejected_strategies_excluded(self, artifact):
        assert "rejected_strategies" in self._items(artifact)

    def test_no_scheduler(self, artifact):
        assert "scheduler_cron_launchd" in self._items(artifact)

    def test_no_lifecycle(self, artifact):
        assert "lifecycle_champion_registry" in self._items(artifact)

    def test_no_apply_in_p126a(self, artifact):
        assert "controlled_apply" in self._items(artifact)


# ---------------------------------------------------------------------------
# Duplicate guard
# ---------------------------------------------------------------------------
class TestDuplicateGuard:
    def test_unique_key(self, artifact):
        key = artifact["duplicate_guard"]["unique_key"]
        assert "lottery_type" in key
        assert "target_draw" in key
        assert "strategy_id" in key
        assert "bet_index" in key

    def test_constraint_active(self, artifact):
        assert artifact["duplicate_guard"]["constraint_active"] is True

    def test_p129b_applied(self, artifact):
        assert artifact["duplicate_guard"]["p129b_migration_applied"] is True


# ---------------------------------------------------------------------------
# Apply preconditions
# ---------------------------------------------------------------------------
class TestApplyPreconditions:
    def _find(self, artifact, check_name):
        return next((p for p in artifact["apply_preconditions"] if p["check"] == check_name), None)

    def test_p129b_schema_migrated(self, artifact):
        pc = self._find(artifact, "p129b_schema_migrated")
        assert pc is not None
        assert pc["status"] == "PASS"

    def test_bet_index_present(self, artifact):
        pc = self._find(artifact, "bet_index_column_present")
        assert pc is not None
        assert pc["status"] == "PASS"

    def test_unique_constraint_ready(self, artifact):
        pc = self._find(artifact, "unique_constraint_ready")
        assert pc is not None
        assert pc["status"] == "PASS"

    def test_db_invariant(self, artifact):
        pc = self._find(artifact, "db_invariant_confirmed")
        assert pc is not None
        assert pc["status"] == "PASS"

    def test_backup_exists(self, artifact):
        pc = self._find(artifact, "backup_exists")
        assert pc is not None
        assert pc["status"] == "PASS"


# ---------------------------------------------------------------------------
# Recommended apply order
# ---------------------------------------------------------------------------
class TestRecommendedOrder:
    def test_exactly_5_entries(self, artifact):
        assert len(artifact["recommended_apply_order"]) == 5

    def test_order_1_is_power_fourier(self, artifact):
        order1 = next(r for r in artifact["recommended_apply_order"] if r["order"] == 1)
        assert order1["strategy_id"] == "power_fourier_rhythm_2bet"

    def test_order_5_is_f4cold_5bet(self, artifact):
        order5 = next(r for r in artifact["recommended_apply_order"] if r["order"] == 5)
        assert order5["strategy_id"] == "daily539_f4cold_5bet"

    def test_total_expected_rows_18000(self, artifact):
        total = sum(r["expected_insert_rows"] for r in artifact["recommended_apply_order"])
        assert total == 18000


# ---------------------------------------------------------------------------
# Known regression failures documented
# ---------------------------------------------------------------------------
class TestKnownRegressionFailures:
    def test_at_least_4_entries(self, artifact):
        assert len(artifact["known_regression_failures"]) >= 4

    def test_p129a_failures_documented(self, artifact):
        files = [rf["test_file"] for rf in artifact["known_regression_failures"]]
        assert any("p129a" in f for f in files)

    def test_p129_failures_documented(self, artifact):
        files = [rf["test_file"] for rf in artifact["known_regression_failures"]]
        assert any("test_p129_" in f for f in files)

    def test_p128_failures_documented(self, artifact):
        files = [rf["test_file"] for rf in artifact["known_regression_failures"]]
        assert any("p128" in f for f in files)

    def test_p126_failures_documented(self, artifact):
        files = [rf["test_file"] for rf in artifact["known_regression_failures"]]
        assert any("p126" in f for f in files)

    def test_all_have_status(self, artifact):
        for rf in artifact["known_regression_failures"]:
            assert rf["status"] in {"KNOWN_OBSOLETE", "KNOWN_PRE_EXISTING"}


# ---------------------------------------------------------------------------
# Migration status
# ---------------------------------------------------------------------------
class TestMigrationStatus:
    def test_p128_accepted(self, artifact):
        assert artifact["migration_status"]["p128_design_accepted"] is True

    def test_p129b_applied(self, artifact):
        assert artifact["migration_status"]["p129b_migration_applied"] is True

    def test_bet_index_active(self, artifact):
        assert artifact["migration_status"]["bet_index_column_active"] is True

    def test_unique_active(self, artifact):
        assert artifact["migration_status"]["unique_constraint_active"] is True

    def test_ready_for_apply(self, artifact):
        assert artifact["migration_status"]["ready_for_apply"] is True


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
class TestSummary:
    def test_classification(self, artifact):
        assert artifact["summary"]["classification"] == "P126A_WAITING_FOR_PER_STRATEGY_APPLY_AUTHORIZATION"

    def test_strategies_authorized_zero(self, artifact):
        assert artifact["summary"]["strategies_authorized"] == 0

    def test_strategies_waiting_5(self, artifact):
        assert artifact["summary"]["strategies_waiting"] == 5

    def test_schema_ready(self, artifact):
        assert artifact["summary"]["schema_ready_for_apply"] is True

    def test_apply_not_executed(self, artifact):
        assert artifact["summary"]["apply_execution_performed"] is False

    def test_rows_inserted_zero(self, artifact):
        assert artifact["summary"]["replay_rows_inserted"] == 0

    def test_p126_estimated_rows(self, artifact):
        assert artifact["summary"]["p126_apply_estimated_rows"] == 18000

    def test_p126_candidates(self, artifact):
        assert artifact["summary"]["p126_candidates"] == 5


# ---------------------------------------------------------------------------
# Markdown content
# ---------------------------------------------------------------------------
class TestMarkdown:
    def test_md_exists(self, md_content):
        assert md_content

    def test_all_5_phrases_in_md(self, md_content):
        for strategy_id in EXPECTED_STRATEGIES:
            phrase_fragment = f"YES authorize controlled_apply for {strategy_id}"
            assert phrase_fragment in md_content, f"Phrase for {strategy_id} missing from MD"

    def test_classification_in_md(self, md_content):
        assert "P126A_WAITING_FOR_PER_STRATEGY_APPLY_AUTHORIZATION" in md_content

    def test_executive_summary_in_md(self, md_content):
        assert "Executive Summary" in md_content

    def test_migration_recap_in_md(self, md_content):
        assert "P129B" in md_content

    def test_dry_run_recap_in_md(self, md_content):
        assert "P126" in md_content

    def test_authorization_section_in_md(self, md_content):
        assert "Authorization" in md_content

    def test_recommended_order_in_md(self, md_content):
        assert "Recommended Apply Order" in md_content

    def test_duplicate_guard_in_md(self, md_content):
        assert "Duplicate Guard" in md_content

    def test_regression_section_in_md(self, md_content):
        assert "regression" in md_content.lower() or "obsolete" in md_content.lower()

    def test_non_actions_in_md(self, md_content):
        assert "Non-Action" in md_content or "non-action" in md_content.lower()


# ---------------------------------------------------------------------------
# Live production DB verification
# ---------------------------------------------------------------------------
class TestLiveProductionDB:
    def test_db_exists(self):
        assert DB_PATH.exists()

    def test_row_count_54462(self):
        conn = sqlite3.connect(DB_PATH)
        try:
            count = conn.execute("SELECT COUNT(*) FROM strategy_prediction_replays").fetchone()[0]
            assert count == 54462
        finally:
            conn.close()

    def test_bet_index_column_exists(self):
        conn = sqlite3.connect(DB_PATH)
        try:
            cols = [r[1] for r in conn.execute("PRAGMA table_info(strategy_prediction_replays)")]
            assert "bet_index" in cols
        finally:
            conn.close()

    def test_new_unique_constraint_active(self):
        conn = sqlite3.connect(DB_PATH)
        try:
            ddl = conn.execute(
                "SELECT sql FROM sqlite_master WHERE type='table' AND name='strategy_prediction_replays'"
            ).fetchone()[0]
            assert "UNIQUE(lottery_type, target_draw, strategy_id, bet_index)" in ddl
        finally:
            conn.close()

    def test_columns_count_28(self):
        conn = sqlite3.connect(DB_PATH)
        try:
            cols = conn.execute("PRAGMA table_info(strategy_prediction_replays)").fetchall()
            assert len(cols) == 28
        finally:
            conn.close()
