"""
Tests for P129B: Execute bet_index Schema Migration on Production DB
Verifies the artifact generated by p129b_execute_bet_index_schema_migration.py
"""
import json
import sqlite3
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
ARTIFACT  = REPO_ROOT / "outputs/replay/p129b_execute_bet_index_schema_migration_20260528.json"
DB_PATH   = REPO_ROOT / "lottery_api/data/lottery_v2.db"


@pytest.fixture(scope="module")
def artifact():
    assert ARTIFACT.exists(), f"P129B artifact not found: {ARTIFACT}"
    with ARTIFACT.open() as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Classification & identity
# ---------------------------------------------------------------------------
class TestClassification:
    def test_task_id(self, artifact):
        assert artifact["task_id"] == "P129B"

    def test_classification(self, artifact):
        assert artifact["classification"] == "P129B_PRODUCTION_BET_INDEX_SCHEMA_MIGRATION_APPLIED"

    def test_generated_at_present(self, artifact):
        assert artifact["generated_at"]


# ---------------------------------------------------------------------------
# Authorization
# ---------------------------------------------------------------------------
class TestAuthorization:
    def test_authorization_present(self, artifact):
        assert artifact["authorization"]["authorization_present"] is True

    def test_migration_allowed(self, artifact):
        assert artifact["authorization"]["migration_allowed"] is True

    def test_auth_text_has_prefix(self, artifact):
        text = artifact["authorization"]["authorization_text_observed"]
        assert text.startswith("YES authorize migration_plan_p128 because ")

    def test_auth_text_not_placeholder(self, artifact):
        text = artifact["authorization"]["authorization_text_observed"]
        assert not text.endswith("<reason>")

    def test_reason_text_present(self, artifact):
        assert artifact["authorization"]["reason_text"]

    def test_stop_reason_is_null(self, artifact):
        assert artifact["authorization"]["stop_reason"] is None

    def test_exact_required_phrase_format(self, artifact):
        phrase = artifact["authorization"]["exact_required_phrase"]
        assert phrase == "YES authorize migration_plan_p128 because <reason>"


# ---------------------------------------------------------------------------
# DB snapshot before migration
# ---------------------------------------------------------------------------
class TestDbSnapshotBefore:
    def test_rows_before(self, artifact):
        assert artifact["db_snapshot_before"]["replay_rows"] == 54462

    def test_no_bet_index_before(self, artifact):
        assert artifact["db_snapshot_before"]["has_bet_index_column"] is False

    def test_columns_count_before(self, artifact):
        assert artifact["db_snapshot_before"]["columns_count"] == 27


# ---------------------------------------------------------------------------
# Backup
# ---------------------------------------------------------------------------
class TestBackup:
    def test_backup_created(self, artifact):
        assert artifact["backup"]["backup_created"] is True

    def test_backup_ok(self, artifact):
        assert artifact["backup"]["backup_ok"] is True

    def test_backup_verification_pass(self, artifact):
        assert artifact["backup"]["backup_verification"] == "PASS"

    def test_backup_row_count(self, artifact):
        assert artifact["backup"]["backup_row_count"] == 54462

    def test_backup_path_present(self, artifact):
        assert artifact["backup"]["backup_path"]

    def test_backup_file_exists(self, artifact):
        path = Path(artifact["backup"]["backup_path"])
        assert path.exists(), f"Backup file not found: {path}"


# ---------------------------------------------------------------------------
# Migration steps
# ---------------------------------------------------------------------------
class TestMigrationSteps:
    def test_migration_ok(self, artifact):
        assert artifact["migration_ok"] is True

    def test_migration_steps_count(self, artifact):
        assert artifact["migration_steps_count"] == 18

    def test_all_steps_ok(self, artifact):
        for step in artifact["migration_steps"]:
            assert step["status"] == "OK", f"Step {step['step']} failed: {step}"

    def test_migration_error_null(self, artifact):
        assert artifact["migration_error"] is None

    def test_corrected_copy_sql_used(self, artifact):
        assert artifact["corrected_copy_sql_used"] is True

    def test_row_number_copy_sql_used(self, artifact):
        assert artifact["row_number_copy_sql_used"] is True

    def test_corrected_copy_sql_has_row_number(self, artifact):
        sql = artifact["corrected_copy_sql_text"]
        assert "ROW_NUMBER() OVER" in sql

    def test_corrected_copy_sql_partition_by(self, artifact):
        sql = artifact["corrected_copy_sql_text"]
        assert "PARTITION BY lottery_type, target_draw, strategy_id" in sql

    def test_corrected_copy_sql_order_by_id(self, artifact):
        sql = artifact["corrected_copy_sql_text"]
        assert "ORDER BY id" in sql

    def test_step1_is_fk_off(self, artifact):
        assert artifact["migration_steps"][0]["step"] == 1
        assert "foreign_keys" in artifact["migration_steps"][0]["sql"].lower()

    def test_step2_is_begin(self, artifact):
        assert "BEGIN" in artifact["migration_steps"][1]["sql"]

    def test_step3_creates_new_table(self, artifact):
        assert "CREATE TABLE strategy_prediction_replays_new" in artifact["migration_steps"][2]["sql"]

    def test_step4_copies_data(self, artifact):
        assert "INSERT INTO strategy_prediction_replays_new" in artifact["migration_steps"][3]["sql"]

    def test_step5_drops_old_table(self, artifact):
        assert "DROP TABLE strategy_prediction_replays" in artifact["migration_steps"][4]["sql"]

    def test_step6_renames_table(self, artifact):
        assert "RENAME TO strategy_prediction_replays" in artifact["migration_steps"][5]["sql"]

    def test_step15_creates_bet_index_index(self, artifact):
        assert "idx_spr_bet_index" in artifact["migration_steps"][14]["sql"]

    def test_step16_commits(self, artifact):
        assert "COMMIT" in artifact["migration_steps"][15]["sql"]

    def test_step17_fk_on(self, artifact):
        assert "foreign_keys" in artifact["migration_steps"][16]["sql"].lower()

    def test_step18_count_equals_expected(self, artifact):
        step = artifact["migration_steps"][17]
        assert step["step"] == 18
        assert "54462" in step["purpose"] or "COUNT" in step["sql"]


# ---------------------------------------------------------------------------
# Schema before/after
# ---------------------------------------------------------------------------
class TestSchemaBefore:
    def test_no_bet_index_before(self, artifact):
        assert artifact["schema_before"]["has_bet_index_column"] is False

    def test_old_unique_constraint(self, artifact):
        constraint = artifact["schema_before"]["current_unique_constraint"]
        assert "replay_run_id" in constraint

    def test_columns_count_27(self, artifact):
        assert artifact["schema_before"]["columns_count"] == 27


class TestSchemaAfter:
    def test_has_bet_index(self, artifact):
        assert artifact["schema_after"]["has_bet_index_column"] is True

    def test_new_unique_constraint(self, artifact):
        assert artifact["schema_after"]["has_new_unique_constraint"] is True

    def test_bet_index_in_columns(self, artifact):
        assert "bet_index" in artifact["schema_after"]["columns"]

    def test_bet_index_last_column(self, artifact):
        assert artifact["schema_after"]["columns"][-1] == "bet_index"

    def test_has_bet_index_index(self, artifact):
        assert artifact["schema_after"]["has_bet_index_index"] is True

    def test_full_ddl_has_bet_index(self, artifact):
        ddl = artifact["schema_after"]["full_ddl"]
        assert "bet_index" in ddl

    def test_full_ddl_has_not_null(self, artifact):
        ddl = artifact["schema_after"]["full_ddl"]
        assert "NOT NULL" in ddl

    def test_full_ddl_has_new_unique(self, artifact):
        ddl = artifact["schema_after"]["full_ddl"]
        assert "UNIQUE(lottery_type, target_draw, strategy_id, bet_index)" in ddl

    def test_full_ddl_old_unique_removed(self, artifact):
        ddl = artifact["schema_after"]["full_ddl"]
        assert "UNIQUE(lottery_type, target_draw, strategy_id, replay_run_id)" not in ddl

    def test_10_indexes_after(self, artifact):
        assert len(artifact["schema_after"]["indexes"]) == 10

    def test_idx_spr_bet_index_present(self, artifact):
        assert "idx_spr_bet_index" in artifact["schema_after"]["indexes"]


# ---------------------------------------------------------------------------
# DB snapshot after migration
# ---------------------------------------------------------------------------
class TestDbSnapshotAfter:
    def test_rows_after(self, artifact):
        assert artifact["db_snapshot_after"]["replay_rows"] == 54462

    def test_bet_index_present_after(self, artifact):
        assert artifact["db_snapshot_after"]["has_bet_index_column"] is True

    def test_columns_count_after(self, artifact):
        assert artifact["db_snapshot_after"]["columns_count"] == 28

    def test_10_indexes_after(self, artifact):
        assert len(artifact["db_snapshot_after"]["indexes"]) == 10


# ---------------------------------------------------------------------------
# bet_index distribution
# ---------------------------------------------------------------------------
class TestBetIndexDistribution:
    def test_total_rows(self, artifact):
        assert artifact["bet_index_distribution"]["total_rows"] == 54462

    def test_bet_index_1_count(self, artifact):
        assert artifact["bet_index_distribution"]["rows_with_bet_index_1"] == 54302

    def test_bet_index_gt1_count(self, artifact):
        assert artifact["bet_index_distribution"]["rows_with_bet_index_gt1"] == 160

    def test_no_invalid_bet_index(self, artifact):
        assert artifact["bet_index_distribution"]["rows_with_invalid_bet_index"] == 0

    def test_distribution_matches_expectation(self, artifact):
        assert artifact["bet_index_distribution"]["distribution_matches_expectation"] is True

    def test_all_rows_valid(self, artifact):
        assert artifact["bet_index_distribution"]["all_rows_valid"] is True

    def test_distribution_sums_to_total(self, artifact):
        dist = artifact["bet_index_distribution"]["distribution"]
        total = sum(d["count"] for d in dist)
        assert total == 54462

    def test_expected_bet_index_1(self, artifact):
        assert artifact["bet_index_distribution"]["expected_bet_index_1"] == 54302

    def test_expected_bet_index_gt1(self, artifact):
        assert artifact["bet_index_distribution"]["expected_bet_index_gt1"] == 160


# ---------------------------------------------------------------------------
# Row preservation
# ---------------------------------------------------------------------------
class TestRowPreservation:
    def test_expected_rows(self, artifact):
        assert artifact["replay_row_preservation_check"]["expected_rows"] == 54462

    def test_actual_rows(self, artifact):
        assert artifact["replay_row_preservation_check"]["actual_rows"] == 54462

    def test_rows_preserved(self, artifact):
        assert artifact["replay_row_preservation_check"]["rows_preserved"] is True

    def test_check_ok(self, artifact):
        assert artifact["replay_row_preservation_check"]["check_ok"] is True


# ---------------------------------------------------------------------------
# UNIQUE constraint validation
# ---------------------------------------------------------------------------
class TestUniqueConstraint:
    def test_duplicate_rejected(self, artifact):
        assert artifact["unique_constraint_validation"]["duplicate_same_bet_index_rejected"] is True

    def test_multi_bet_allowed(self, artifact):
        assert artifact["unique_constraint_validation"]["multi_bet_different_index_allowed"] is True

    def test_constraint_works(self, artifact):
        assert artifact["unique_constraint_validation"]["constraint_works_as_expected"] is True

    def test_validation_ok(self, artifact):
        assert artifact["unique_constraint_validation"]["validation_ok"] is True


# ---------------------------------------------------------------------------
# Duplicate audit (120 groups preserved)
# ---------------------------------------------------------------------------
class TestDuplicateAudit:
    def test_120_groups_preserved(self, artifact):
        assert artifact["duplicate_audit"]["groups_with_multiple_rows"] == 120


# ---------------------------------------------------------------------------
# P126 still blocked
# ---------------------------------------------------------------------------
class TestP126Blocked:
    def test_status_blocked(self, artifact):
        assert artifact["p126_apply_status"]["status"] == "BLOCKED_UNTIL_PER_STRATEGY_AUTHORIZATION"

    def test_apply_not_executed(self, artifact):
        assert artifact["p126_apply_status"]["apply_executed"] is False

    def test_5_required_phrases(self, artifact):
        phrases = artifact["p126_apply_status"]["required_per_strategy_phrases"]
        assert len(phrases) == 5

    def test_phrase_format_biglotto_echo(self, artifact):
        phrases = artifact["p126_apply_status"]["required_per_strategy_phrases"]
        assert any("biglotto_echo_aware_3bet" in p for p in phrases)

    def test_phrase_format_daily539_f4cold_5bet(self, artifact):
        phrases = artifact["p126_apply_status"]["required_per_strategy_phrases"]
        assert any("daily539_f4cold_5bet" in p for p in phrases)

    def test_phrase_format_daily539_f4cold_3bet(self, artifact):
        phrases = artifact["p126_apply_status"]["required_per_strategy_phrases"]
        assert any("daily539_f4cold_3bet" in p for p in phrases)

    def test_phrase_format_power_fourier(self, artifact):
        phrases = artifact["p126_apply_status"]["required_per_strategy_phrases"]
        assert any("power_fourier_rhythm_2bet" in p for p in phrases)

    def test_phrase_format_biglotto_ts3(self, artifact):
        phrases = artifact["p126_apply_status"]["required_per_strategy_phrases"]
        assert any("biglotto_ts3_markov_4bet_w30" in p for p in phrases)


# ---------------------------------------------------------------------------
# Source artifacts linked correctly
# ---------------------------------------------------------------------------
class TestSourceArtifacts:
    def test_p129a_classification(self, artifact):
        assert artifact["p129a_source_summary"]["classification"] == "P129A_WAITING_FOR_KELVIN_MIGRATION_AUTHORIZATION"

    def test_p129a_ok(self, artifact):
        assert artifact["p129a_source_summary"]["classification_ok"] is True

    def test_p129_classification(self, artifact):
        assert artifact["p129_source_summary"]["classification"] == "P129_BET_INDEX_SCHEMA_MIGRATION_REHEARSAL_READY"

    def test_p129_ok(self, artifact):
        assert artifact["p129_source_summary"]["classification_ok"] is True

    def test_p129_row_number_required(self, artifact):
        assert artifact["p129_source_summary"]["row_number_copy_sql_required"] is True

    def test_p129_duplicate_groups(self, artifact):
        assert artifact["p129_source_summary"]["duplicate_groups_found"] == 120

    def test_p129_extra_rows(self, artifact):
        assert artifact["p129_source_summary"]["extra_rows_from_old_runs"] == 160


# ---------------------------------------------------------------------------
# Governance / blocked items
# ---------------------------------------------------------------------------
class TestGovernance:
    def _blocked_items(self, artifact):
        return {b["item"] for b in artifact["blocked_or_excluded"]}

    def test_p126_apply_blocked_entry(self, artifact):
        assert "p126_apply" in self._blocked_items(artifact)

    def test_4_star_excluded(self, artifact):
        assert "4_STAR" in self._blocked_items(artifact)

    def test_scheduler_excluded(self, artifact):
        assert "scheduler_cron_launchd" in self._blocked_items(artifact)

    def test_lifecycle_excluded(self, artifact):
        assert "lifecycle_champion_registry" in self._blocked_items(artifact)

    def test_p108_excluded(self, artifact):
        assert "P108" in self._blocked_items(artifact)

    def test_p117_excluded(self, artifact):
        assert "P117" in self._blocked_items(artifact)

    def test_p118_excluded(self, artifact):
        assert "P118" in self._blocked_items(artifact)


# ---------------------------------------------------------------------------
# Rollback reference
# ---------------------------------------------------------------------------
class TestRollback:
    def test_rollback_backup_path(self, artifact):
        assert artifact["rollback_reference"]["backup_path"]

    def test_rollback_command_present(self, artifact):
        assert "cp" in artifact["rollback_reference"]["rollback_command"]


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
class TestSummary:
    def test_migration_executed(self, artifact):
        assert artifact["summary"]["migration_executed"] is True

    def test_migration_ok(self, artifact):
        assert artifact["summary"]["migration_ok"] is True

    def test_backup_ok(self, artifact):
        assert artifact["summary"]["backup_ok"] is True

    def test_rows_before(self, artifact):
        assert artifact["summary"]["rows_before"] == 54462

    def test_rows_after(self, artifact):
        assert artifact["summary"]["rows_after"] == 54462

    def test_bet_index_column_present(self, artifact):
        assert artifact["summary"]["bet_index_column_present"] is True

    def test_unique_constraint_ok(self, artifact):
        assert artifact["summary"]["unique_constraint_ok"] is True

    def test_all_validation_ok(self, artifact):
        assert artifact["summary"]["all_validation_ok"] is True

    def test_p126_not_executed(self, artifact):
        assert artifact["summary"]["p126_apply_executed"] is False

    def test_classification_in_summary(self, artifact):
        assert artifact["summary"]["classification"] == "P129B_PRODUCTION_BET_INDEX_SCHEMA_MIGRATION_APPLIED"


# ---------------------------------------------------------------------------
# Live production DB verification
# ---------------------------------------------------------------------------
class TestLiveProductionDB:
    """Verify the actual production DB reflects the migration — not just the artifact."""

    def test_db_exists(self):
        assert DB_PATH.exists()

    def test_row_count_at_least_54462(self):
        # P129B established 54462 rows; P126B and subsequent applies grow this further.
        conn = sqlite3.connect(DB_PATH)
        try:
            count = conn.execute("SELECT COUNT(*) FROM strategy_prediction_replays").fetchone()[0]
            assert count >= 54462
        finally:
            conn.close()

    def test_bet_index_column_exists(self):
        conn = sqlite3.connect(DB_PATH)
        try:
            cols = [row[1] for row in conn.execute("PRAGMA table_info(strategy_prediction_replays)")]
            assert "bet_index" in cols
        finally:
            conn.close()

    def test_bet_index_not_null(self):
        conn = sqlite3.connect(DB_PATH)
        try:
            null_count = conn.execute(
                "SELECT COUNT(*) FROM strategy_prediction_replays WHERE bet_index IS NULL"
            ).fetchone()[0]
            assert null_count == 0
        finally:
            conn.close()

    def test_bet_index_1_count(self):
        conn = sqlite3.connect(DB_PATH)
        try:
            count = conn.execute(
                "SELECT COUNT(*) FROM strategy_prediction_replays WHERE bet_index = 1"
            ).fetchone()[0]
            assert count == 54302
        finally:
            conn.close()

    def test_bet_index_gt1_count(self):
        # P129B migration produced 160 rows with bet_index>1 from ROW_NUMBER dedup.
        # P126B and later applies legitimately add more bet_index=2 rows.
        conn = sqlite3.connect(DB_PATH)
        try:
            count = conn.execute(
                "SELECT COUNT(*) FROM strategy_prediction_replays WHERE bet_index > 1"
            ).fetchone()[0]
            assert count >= 160
        finally:
            conn.close()

    def test_columns_count_28(self):
        conn = sqlite3.connect(DB_PATH)
        try:
            cols = conn.execute("PRAGMA table_info(strategy_prediction_replays)").fetchall()
            assert len(cols) == 28
        finally:
            conn.close()

    def test_new_unique_constraint_in_ddl(self):
        conn = sqlite3.connect(DB_PATH)
        try:
            ddl = conn.execute(
                "SELECT sql FROM sqlite_master WHERE type='table' AND name='strategy_prediction_replays'"
            ).fetchone()[0]
            assert "UNIQUE(lottery_type, target_draw, strategy_id, bet_index)" in ddl
        finally:
            conn.close()

    def test_old_unique_constraint_removed(self):
        conn = sqlite3.connect(DB_PATH)
        try:
            ddl = conn.execute(
                "SELECT sql FROM sqlite_master WHERE type='table' AND name='strategy_prediction_replays'"
            ).fetchone()[0]
            # UNIQUE clause must contain bet_index, not replay_run_id
            assert "UNIQUE(lottery_type, target_draw, strategy_id, bet_index)" in ddl
            assert "UNIQUE(lottery_type, target_draw, strategy_id, replay_run_id)" not in ddl
        finally:
            conn.close()

    def test_idx_spr_bet_index_exists(self):
        conn = sqlite3.connect(DB_PATH)
        try:
            indexes = [row[1] for row in conn.execute(
                "SELECT type, name FROM sqlite_master WHERE type='index' AND tbl_name='strategy_prediction_replays'"
            )]
            assert "idx_spr_bet_index" in indexes
        finally:
            conn.close()
