"""
P37 Manual Odds CSV Template Writer

Writes a TEMPLATE CSV and COLUMN_GUIDE.md for the manually-provisioned 2024 odds
file.  The template includes a single clearly-labelled EXAMPLE row so the
researcher understands the expected format.  The example row must never be
treated as real data.

PAPER_ONLY=True  PRODUCTION_READY=False  SEASON=2024
"""

from __future__ import annotations

import os
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd

from wbc_backend.recommendation.p37_manual_odds_provisioning_contract import (
    MANUAL_ODDS_TEMPLATE_COLUMNS,
    PAPER_ONLY,
    PRODUCTION_READY,
    P37ManualOddsTemplate,
)

# ---------------------------------------------------------------------------
# Example row — clearly synthetic, not real data
# ---------------------------------------------------------------------------
_EXAMPLE_ROW: Dict[str, Any] = {
    "game_id": "EXAMPLE_20240401_NYA_BOS",
    "game_date": "2024-04-01",
    "home_team": "BOS",
    "away_team": "NYA",
    "p_market": 0.52,
    "odds_decimal": 1.92,
    "sportsbook": "EXAMPLE_BOOK",
    "market_type": "moneyline",
    "closing_timestamp": "2024-04-01T17:00:00+00:00",
    "source_odds_ref": "EXAMPLE_SOURCE_REF",
    "license_ref": "EXAMPLE_LICENSE_REF",
}

_COLUMN_GUIDE_CONTENT: str = """# P37 Manual Odds CSV — Column Guide

## File
`odds_2024_approved_TEMPLATE.csv` → rename to `odds_2024_approved.csv`
Place at: `data/mlb_2024/manual_import/odds_2024_approved.csv`

---

## Column Definitions

| Column | Type | Required | Notes |
|--------|------|----------|-------|
| game_id | string | YES | Unique game identifier. Format: `YYYYMMDD_AWAY_HOME` recommended |
| game_date | date string | YES | ISO date `YYYY-MM-DD` |
| home_team | string | YES | MLB abbreviation (e.g. BOS, NYA) |
| away_team | string | YES | MLB abbreviation |
| p_market | float [0,1] | YES | Pre-game market-implied win probability for home team. Derived from closing odds: p = 1/odds_decimal (vig-adjusted). Do NOT use game outcome. |
| odds_decimal | float ≥ 1.0 | YES | Closing decimal odds for home team moneyline |
| sportsbook | string | YES | Source sportsbook name (e.g. Pinnacle, BetUS) |
| market_type | string | YES | One of: moneyline, ml, money_line, 1x2, h2h |
| closing_timestamp | datetime string | YES | ISO 8601 UTC closing time (e.g. 2024-04-01T17:00:00+00:00) |
| source_odds_ref | string | YES | Reference to the specific source page/API endpoint/dataset row |
| license_ref | string | YES | Reference to the license or approval record entry |

---

## Forbidden Columns
Do NOT include any of the following in the odds file:
- y_true
- final_score
- home_score
- away_score
- winner
- outcome
- result
- run_diff
- total_runs
- game_result

Including these columns causes the P36/P37 leakage validator to block the import.

---

## Deriving p_market from closing odds
For a moneyline market with no-vig adjustment:

```
raw_p = 1 / odds_decimal_home
# Apply standard two-sided vig removal if both sides available:
raw_q = 1 / odds_decimal_away
overround = raw_p + raw_q
p_market = raw_p / overround
```

Never infer `p_market` from the game outcome.
Never set `p_market = 1.0` for wins or `0.0` for losses.

---

## Data Isolation Invariant
All values in this file MUST reflect the state of information available
BEFORE the game started.  No post-game information may be used.

---

## Invariants (enforced by gate)
- paper_only = True (enforced, not a column)
- production_ready = False (enforced, not a column)
- raw_odds_commit_allowed = False (always)
- This template is EXAMPLE ONLY — do not use EXAMPLE rows in production analysis.

---

*Generated by P37 Manual Odds Provisioning Gate — PAPER_ONLY=True, SEASON=2024*
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build_manual_odds_csv_template() -> pd.DataFrame:
    """
    Return a DataFrame with one clearly-labelled EXAMPLE row.

    The example row is synthetic and must not be used as real data.
    """
    df = pd.DataFrame([_EXAMPLE_ROW], columns=list(MANUAL_ODDS_TEMPLATE_COLUMNS))
    return df


def validate_manual_odds_template(df: Any) -> Tuple[bool, str, List[str]]:
    """
    Check that a DataFrame has all required columns and no forbidden cols.

    Returns (ok, message, missing_columns).
    """
    if not isinstance(df, pd.DataFrame):
        return False, "Not a DataFrame", list(MANUAL_ODDS_TEMPLATE_COLUMNS)

    missing = [c for c in MANUAL_ODDS_TEMPLATE_COLUMNS if c not in df.columns]
    if missing:
        return False, f"Missing required columns: {missing}", missing

    return True, "Template valid", []


def write_manual_odds_template(output_dir: str) -> str:
    """
    Write odds_2024_approved_TEMPLATE.csv to output_dir.
    Returns the written file path.
    """
    os.makedirs(output_dir, exist_ok=True)
    df = build_manual_odds_csv_template()
    path = os.path.join(output_dir, "odds_2024_approved_TEMPLATE.csv")
    df.to_csv(path, index=False)
    return path


def write_manual_odds_column_guide(output_dir: str) -> str:
    """
    Write odds_2024_approved_COLUMN_GUIDE.md to output_dir.
    Returns the written file path.
    """
    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, "odds_2024_approved_COLUMN_GUIDE.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(_COLUMN_GUIDE_CONTENT)
    return path
