"""
Phase 22 — Learning Patch Task Generator
==========================================
Converts an approved learning patch gate decision into a safe, local,
sandbox-only patch-evaluation task specification.

Design principles:
  - Only ALLOW_PATCH_CANDIDATE gate decisions produce a task spec.
  - HOLD / INVESTIGATE / REJECT decisions yield None (no task).
  - All generated tasks have execution_mode = "SANDBOX_ONLY".
  - Sandbox source ("sandbox/test") NEVER produces a production task family.
  - No external LLM is called.
  - No production model or CLV file is modified.

Typical usage:
    from orchestrator.learning_patch_task_generator import generate_patch_evaluation_task

    task_spec = generate_patch_evaluation_task(gate_decision)
    if task_spec is not None:
        # planner creates this task in the DB
        pass
"""
from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from typing import Any

from orchestrator.learning_patch_gate import (
    GATE_ALLOW_PATCH,
    GATE_HOLD,
    GATE_INVESTIGATE_ONLY,
    GATE_REJECT,
)

logger = logging.getLogger(__name__)

# ── Constants ─────────────────────────────────────────────────────────────────

EXECUTION_MODE_SANDBOX = "SANDBOX_ONLY"
EXECUTION_MODE_PRODUCTION = "PRODUCTION"  # never generated by this module

# Allowed task families for sandbox patch evaluation
_SANDBOX_TASK_FAMILIES = frozenset({
    "calibration-patch-evaluation",
    "model-validation-atomic",
})

# Allowed task families for production (never invoked from sandbox source)
_PRODUCTION_TASK_FAMILIES = frozenset({
    "model-patch-atomic",
    "calibration-atomic",
})

_SOURCE_SANDBOX = "sandbox/test"

# Investigation task spec fields (for INVESTIGATE_ONLY)
_INVESTIGATE_TASK_TYPE = "model_validation_atomic"
_INVESTIGATE_TASK_FAMILY = "model-validation-atomic"


def generate_patch_evaluation_task(
    gate_decision: dict[str, Any],
) -> dict[str, Any] | None:
    """
    Convert a gate decision into a patch-evaluation task specification.

    Args:
        gate_decision: The full gate decision dict returned by
                       ``evaluate_patch_gate()`` or loaded from training memory.

    Returns:
        A task specification dict if the decision is ALLOW_PATCH_CANDIDATE,
        or None for HOLD / INVESTIGATE / REJECT decisions.

    Hard rules enforced here:
      - Only ALLOW_PATCH_CANDIDATE → task spec.
      - source "sandbox/test" → execution_mode=SANDBOX_ONLY.
      - allowed_task_family must be in _SANDBOX_TASK_FAMILIES for sandbox source.
      - No production patch task is ever generated from a sandbox source.
    """
    decision = gate_decision.get("gate_decision", "")
    source = gate_decision.get("source", _SOURCE_SANDBOX)
    is_sandbox = _is_sandbox_source(source)

    # ── Only ALLOW produces a task ────────────────────────────────────────────
    if decision != GATE_ALLOW_PATCH:
        logger.debug(
            "[PatchTaskGen] gate_decision=%s — no task generated (not ALLOW_PATCH_CANDIDATE)",
            decision,
        )
        return None

    # ── Determine task type and family ────────────────────────────────────────
    allowed_family = gate_decision.get("allowed_task_family") or "model-validation-atomic"

    if is_sandbox:
        # Enforce sandbox constraint — family must be in safe set
        if allowed_family not in _SANDBOX_TASK_FAMILIES:
            logger.warning(
                "[PatchTaskGen] Overriding disallowed sandbox family %r → model-validation-atomic",
                allowed_family,
            )
            allowed_family = "model-validation-atomic"
        task_type = "calibration_patch_evaluation"
        execution_mode = EXECUTION_MODE_SANDBOX
    else:
        # Production source: allow calibration-patch-evaluation but guard against unknown families
        if allowed_family not in (_SANDBOX_TASK_FAMILIES | _PRODUCTION_TASK_FAMILIES):
            logger.warning(
                "[PatchTaskGen] Overriding unknown production family %r → model-validation-atomic",
                allowed_family,
            )
            allowed_family = "model-validation-atomic"
        task_type = "calibration_patch_evaluation"
        execution_mode = EXECUTION_MODE_SANDBOX  # always SANDBOX_ONLY for safety

    # ── Build task specification ───────────────────────────────────────────────
    now = datetime.now(timezone.utc).isoformat()
    gate_decision_id = gate_decision.get("gate_decision_id") or _make_gate_id(gate_decision)
    learning_cycle_id = gate_decision.get("learning_cycle_id") or "unknown"
    computed_count = gate_decision.get("computed_clv_count", 0)
    recommendation = gate_decision.get("recommendation", "CANDIDATE_PATCH")
    confidence = gate_decision.get("confidence", "medium")

    task_spec: dict[str, Any] = {
        # ── Core task identity ────────────────────────────────────────────────
        "task_type": task_type,
        "analysis_family": allowed_family,
        "execution_mode": execution_mode,
        "source": "learning_patch_gate",
        # ── Provenance ────────────────────────────────────────────────────────
        "learning_cycle_id": learning_cycle_id,
        "gate_decision_id": gate_decision_id,
        "signal_state_type": "learning_clv_quality",
        # ── Target ────────────────────────────────────────────────────────────
        "target_metric": "clv_quality",
        "candidate_patch_type": _infer_patch_type(allowed_family),
        # ── Context from gate ─────────────────────────────────────────────────
        "computed_clv_count": computed_count,
        "recommendation": recommendation,
        "confidence": confidence,
        "gate_confidence": gate_decision.get("confidence", "medium"),
        "gate_reason": gate_decision.get("reason", ""),
        # ── Hard rule acceptance criteria ─────────────────────────────────────
        "acceptance_criteria": {
            "no_production_mutation": True,
            "no_external_llm": True,
            "validation_artifact_required": True,
            "sandbox_only": is_sandbox,
            "production_patch_allowed": False,
        },
        # ── Planner metadata ──────────────────────────────────────────────────
        "title": (
            f"[SANDBOX][{allowed_family}] CLV Patch Evaluation — "
            f"cycle {learning_cycle_id[:8]}"
        ),
        "focus_area": "clv_quality_patch_evaluation",
        "priority": "normal",
        "created_by": "learning_patch_task_generator",
        "created_at": now,
        # ── Executor injection ────────────────────────────────────────────────
        # Planner sets _sandbox_reports_dir and _sandbox_artifact_dir before
        # handing off to safe_task_executor. Leave None here.
        "_sandbox_reports_dir": None,
        "_sandbox_artifact_dir": None,
    }

    logger.info(
        "[PatchTaskGen] Generated %s task spec for gate_decision_id=%s  "
        "family=%s  execution_mode=%s  learning_cycle_id=%s",
        task_type,
        gate_decision_id,
        allowed_family,
        execution_mode,
        learning_cycle_id,
    )
    return task_spec


def generate_investigation_task(
    gate_decision: dict[str, Any],
) -> dict[str, Any] | None:
    """
    Convert an INVESTIGATE_ONLY gate decision into an investigation task spec.

    Args:
        gate_decision: Gate decision dict with gate_decision=INVESTIGATE_ONLY.

    Returns:
        Task specification dict, or None if decision is not INVESTIGATE_ONLY.
    """
    decision = gate_decision.get("gate_decision", "")
    if decision != GATE_INVESTIGATE_ONLY:
        return None

    now = datetime.now(timezone.utc).isoformat()
    gate_decision_id = gate_decision.get("gate_decision_id") or _make_gate_id(gate_decision)
    learning_cycle_id = gate_decision.get("learning_cycle_id") or "unknown"

    task_spec: dict[str, Any] = {
        "task_type": _INVESTIGATE_TASK_TYPE,
        "analysis_family": _INVESTIGATE_TASK_FAMILY,
        "execution_mode": EXECUTION_MODE_SANDBOX,
        "source": "learning_patch_gate",
        "learning_cycle_id": learning_cycle_id,
        "gate_decision_id": gate_decision_id,
        "signal_state_type": "learning_clv_quality",
        "target_metric": "clv_quality",
        "candidate_patch_type": "investigation",
        "acceptance_criteria": {
            "no_production_mutation": True,
            "no_external_llm": True,
            "validation_artifact_required": True,
            "sandbox_only": True,
            "production_patch_allowed": False,
        },
        "title": (
            f"[SANDBOX][{_INVESTIGATE_TASK_FAMILY}] CLV Investigation — "
            f"cycle {learning_cycle_id[:8]}"
        ),
        "focus_area": "clv_quality_investigation",
        "priority": "normal",
        "created_by": "learning_patch_task_generator",
        "created_at": now,
        "_sandbox_reports_dir": None,
        "_sandbox_artifact_dir": None,
    }

    logger.info(
        "[PatchTaskGen] Generated investigation task for gate_decision_id=%s  "
        "learning_cycle_id=%s",
        gate_decision_id,
        learning_cycle_id,
    )
    return task_spec


# ── Helpers ───────────────────────────────────────────────────────────────────

def _is_sandbox_source(source: str) -> bool:
    """Return True if the source string indicates sandbox / test mode."""
    s = (source or "").lower()
    return s.startswith("sandbox") or s.startswith("test")


def _infer_patch_type(family: str) -> str:
    """Infer the candidate_patch_type from the allowed task family."""
    mapping = {
        "calibration-patch-evaluation": "calibration",
        "model-validation-atomic": "threshold",
        "model-patch-atomic": "regime_filter",
        "calibration-atomic": "calibration",
    }
    return mapping.get(family, "threshold")


def _make_gate_id(gate_decision: dict[str, Any]) -> str:
    """Generate a deterministic-ish gate ID from available fields."""
    cycle_id = gate_decision.get("learning_cycle_id", "")
    decision = gate_decision.get("gate_decision", "")
    rec_at = gate_decision.get("recorded_at", "")
    return f"gate_{cycle_id[:8]}_{decision[:4]}_{rec_at[:10]}".replace(" ", "_")
