"""P540B — DAILY_539 Incremental Replay Generation (Manifested DB Write).

Backfills strategy_prediction_replays rows for DAILY_539 target draws that
already exist in `draws` but have never been backtested/replayed (per
P540A's readiness inventory). Every generated row uses only causal history
(all draws strictly before the target draw) via existing, already-proven
adapter modules (WAVE1_ADAPTERS, WAVE2_ADAPTERS, and the two ONLINE
registry.py DAILY_539 adapters) -- no new prediction algorithm is written
here.

Scope is deliberately narrower than "every DAILY_539 strategy_id currently
in the DB": strategies/bet_indices whose generating code is not safely
reusable (orphaned from origin/main, or explicitly documented as dry-run/
temp-DB-only) are excluded and reported in EXCLUDED_* below, not silently
regenerated or guessed at.

This module never runs without an explicit --apply flag; the default mode
only builds a manifest and a dry-run preview against the read-only DB.

Historical replay backfill only; not a prediction, betting edge,
future-winning, or production-readiness claim.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from lottery_api.models.replay_strategy_registry import (  # noqa: E402
    InsufficientHistory,
    InvalidOutput,
    RejectPrediction,
    UnsupportedLotteryType,
    get_adapter,
)
from lottery_api.models.p31a_wave1_retired_adapters import WAVE1_ADAPTERS  # noqa: E402
from lottery_api.models.p36_wave2_daily539_adapters import WAVE2_ADAPTERS  # noqa: E402

TASK_ID = "P540B"
LOTTERY_TYPE = "DAILY_539"

DEFAULT_DB_PATH = REPO_ROOT / "lottery_api" / "data" / "lottery_v2.db"
OUTPUT_DIR = REPO_ROOT / "outputs" / "research"

CONTROLLED_APPLY_ID = "P540B_DAILY539_INCREMENTAL_20260709"
TRUTH_LEVEL = "DAILY539_P540B_INCREMENTAL_BACKFILL_VERIFIED"
SOURCE = "P540B_DAILY539_INCREMENTAL_REPLAY_GENERATION"
RUN_ID = "p540b_daily539_incremental_20260709"

# Registry.py ONLINE adapters reused via the public get_adapter() lookup
# (mirrors how RSM/production code is meant to fetch them; avoids reaching
# into private classes directly). daily539_markov_cold is NOT included here
# -- see EXCLUDED_STRATEGY_IDS.
_REGISTRY_STRATEGY_IDS = ("daily539_f4cold",)

DISCLAIMER_EN = (
    "Historical replay backfill only; not a prediction, betting edge, "
    "future-winning, or production-readiness claim."
)

# Strategies excluded from this manifest entirely (not just a bet_index
# carve-out) -- documented, not silently dropped.
EXCLUDED_STRATEGY_IDS: dict[str, str] = {
    "daily539_f4cold_3bet": (
        "Generating adapter (lottery_api/models/p93_tierb_replay_adapters.py) carries an "
        "explicit module-level governance statement: 'These adapters ... must NOT be used for "
        "live prediction, strategy promotion, or production replay row insertion' and 'All rows "
        "generated using these adapters are dry_run=1, temp-DB only.' Existing production rows "
        "for this strategy_id were produced by a separate, explicitly authorized script (P94); "
        "reusing the adapter here for a new production write would need the same kind of explicit "
        "override, which is out of scope for this incremental task."
    ),
    "daily539_f4cold_5bet": (
        "Same p93_tierb_replay_adapters.py governance restriction as daily539_f4cold_3bet above."
    ),
    "daily539_markov_cold": (
        "Adapter's underlying tools/backtest_39lotto_comprehensive.py resolves its own default DB "
        "path relative to its own __file__ at import time (a known multi-sink DB-path-resolution "
        "pattern; the repo has 24+ such sinks per project history) and raises FileNotFoundError "
        "when imported from a git worktree that intentionally has no DB file checked out. This is "
        "an environment artifact, not a prediction-logic defect -- get_one_bet's own math only "
        "depends on the `history` argument. A symlink workaround was considered and rejected: it "
        "would create an unguarded default-path write route into the canonical DB, bypassing this "
        "task's manifested/transactional write path. Excluded from this run; a follow-up task "
        "should either run from an environment where the module's default path resolves, or fix "
        "the module to accept an explicit db_path override."
    ),
}

# Existing multi-bet strategies where only bet_index=1 is generated by this
# task, because the confirmed-reusable adapter interface for these
# strategy_ids only produces one bet; the additional historical bet_index
# values were produced by a different mechanism not confirmed reusable here.
EXCLUDED_BET_INDICES: dict[str, str] = {
    "acb_markov_midfreq_3bet": (
        "p31a_wave1_retired_adapters.AcbMarkovMidfreq3BetAdapter is bet-1-only by design "
        "('Replay records bet-1 only = pure ACB bet'); this matches how P31A/P31B originally "
        "scoped this strategy. Historical bet_index 2-3 rows for this strategy_id were generated "
        "by a separate module (p128_wave2_phase2_adapters.py) that is not present on origin/main "
        "(orphaned commit) -- not regenerated here."
    ),
    "daily539_f4cold": (
        "replay_strategy_registry._Daily539F4ColdAdapter.get_one_bet returns exactly one bet. "
        "Historical bet_index 2-3 rows for this strategy_id were produced by a mechanism not "
        "confirmed reusable within this task's scope -- not regenerated here."
    ),
}


def _build_adapters() -> list[Any]:
    adapters = list(WAVE1_ADAPTERS) + list(WAVE2_ADAPTERS)
    for sid in _REGISTRY_STRATEGY_IDS:
        adapters.append(get_adapter(sid))
    return adapters


def _open_ro(db_path: Path | str) -> sqlite3.Connection:
    conn = sqlite3.connect(f"file:{Path(db_path)}?mode=ro", uri=True)
    conn.execute("PRAGMA query_only=ON")
    return conn


def _file_sha256(path: Path | str) -> str:
    hasher = hashlib.sha256()
    hasher.update(Path(path).read_bytes())
    return hasher.hexdigest()


def load_lottery_draws(conn: sqlite3.Connection, lottery_type: str) -> list[dict]:
    """READ-ONLY. All draws for `lottery_type`, sorted chronologically."""
    rows = conn.execute(
        "SELECT draw, date, numbers FROM draws WHERE lottery_type = ? "
        "ORDER BY date ASC, CAST(draw AS INTEGER) ASC",
        (lottery_type,),
    ).fetchall()
    draws = []
    for draw, date, numbers_json in rows:
        nums = json.loads(numbers_json) if isinstance(numbers_json, str) else numbers_json
        draws.append({"draw": draw, "date": date, "numbers": [int(n) for n in nums]})
    return draws


def build_pre_write_snapshot(conn: sqlite3.Connection) -> dict[str, Any]:
    """READ-ONLY. Row counts by lottery, DAILY_539 max target_draw, missing target draws."""
    by_lottery = dict(
        conn.execute(
            "SELECT lottery_type, COUNT(*) FROM strategy_prediction_replays GROUP BY lottery_type"
        ).fetchall()
    )
    max_target_row = conn.execute(
        "SELECT MAX(CAST(target_draw AS INTEGER)) FROM strategy_prediction_replays WHERE lottery_type = ?",
        (LOTTERY_TYPE,),
    ).fetchone()
    max_target = max_target_row[0] if max_target_row and max_target_row[0] is not None else 0

    all_draws = load_lottery_draws(conn, LOTTERY_TYPE)
    missing = [d for d in all_draws if int(d["draw"]) > max_target]

    return {
        "strategy_prediction_replays_count_by_lottery": by_lottery,
        "strategy_prediction_replays_total": sum(by_lottery.values()),
        "daily539_latest_replayed_target_draw": str(max_target) if max_target else None,
        "daily539_missing_target_draws": [d["draw"] for d in missing],
        "daily539_missing_target_draw_count": len(missing),
    }


def build_manifest(pre_snapshot: dict[str, Any], adapters: list[Any]) -> dict[str, Any]:
    target_draws = pre_snapshot["daily539_missing_target_draws"]
    strategy_ids = sorted(a.meta.strategy_id for a in adapters)
    expected_rows = len(target_draws) * len(strategy_ids)

    return {
        "target_lottery": LOTTERY_TYPE,
        "target_draw_ids": list(target_draws),
        "target_draw_count": len(target_draws),
        "in_scope_strategy_ids": strategy_ids,
        "in_scope_strategy_id_count": len(strategy_ids),
        "bet_index_scope": "1 only, for every in-scope strategy_id (see EXCLUDED_BET_INDICES for carve-outs)",
        "expected_inserted_rows": expected_rows,
        "expected_written_tables": ["strategy_prediction_replays"],
        "dedupe_idempotency_key": "UNIQUE(lottery_type, target_draw, strategy_id, bet_index)",
        "rollback_method": (
            f"DELETE FROM strategy_prediction_replays WHERE controlled_apply_id = "
            f"'{CONTROLLED_APPLY_ID}'; -- documented here, NOT auto-run"
        ),
        "controlled_apply_id": CONTROLLED_APPLY_ID,
        "excluded_strategy_ids": EXCLUDED_STRATEGY_IDS,
        "excluded_bet_indices": EXCLUDED_BET_INDICES,
        "pre_write_baseline": {
            "strategy_prediction_replays_total": pre_snapshot["strategy_prediction_replays_total"],
            "daily539_count": pre_snapshot["strategy_prediction_replays_count_by_lottery"].get(LOTTERY_TYPE, 0),
            "big_lotto_count": pre_snapshot["strategy_prediction_replays_count_by_lottery"].get("BIG_LOTTO", 0),
            "power_lotto_count": pre_snapshot["strategy_prediction_replays_count_by_lottery"].get("POWER_LOTTO", 0),
        },
    }


def is_manifest_internally_consistent(manifest: dict[str, Any]) -> tuple[bool, list[str]]:
    problems: list[str] = []
    if manifest["target_lottery"] != LOTTERY_TYPE:
        problems.append("target_lottery is not DAILY_539")
    if any(s in manifest["in_scope_strategy_ids"] for s in EXCLUDED_STRATEGY_IDS):
        problems.append("an excluded strategy_id leaked into in_scope_strategy_ids")
    if manifest["target_draw_count"] * manifest["in_scope_strategy_id_count"] != manifest["expected_inserted_rows"]:
        problems.append("expected_inserted_rows does not equal target_draw_count * strategy_id_count")
    if manifest["target_draw_count"] == 0 or manifest["in_scope_strategy_id_count"] == 0:
        problems.append("empty target draw set or empty strategy set")
    return (len(problems) == 0, problems)


def _provenance_hash(strategy_id: str, target_draw: str, numbers: list[int]) -> str:
    payload = f"{strategy_id}|{target_draw}|{sorted(numbers)}"
    return hashlib.sha256(payload.encode()).hexdigest()[:16]


def _run_one_prediction(adapter: Any, history: list[dict], target: dict) -> dict:
    """Pure function: no DB access. Causal history in, one row dict out."""
    strategy_id = adapter.meta.strategy_id
    strategy_name = adapter.meta.strategy_name
    strategy_version = adapter.meta.strategy_version

    replay_status = "PREDICTED"
    reject_reason = None
    predicted_numbers = None
    hit_numbers = None
    hit_count = 0
    now_str = datetime.now(timezone.utc).isoformat()

    try:
        numbers, _special = adapter.get_one_bet(history, LOTTERY_TYPE)
        predicted_numbers = json.dumps(numbers)
        actual_nums = target["numbers"]
        hits = sorted(set(numbers) & set(actual_nums))
        hit_numbers = json.dumps(hits)
        hit_count = len(hits)
    except InsufficientHistory as exc:
        replay_status, reject_reason = "INSUFFICIENT_HISTORY", str(exc)
    except UnsupportedLotteryType as exc:
        replay_status, reject_reason = "STRATEGY_UNAVAILABLE", str(exc)
    except (InvalidOutput, RejectPrediction) as exc:
        replay_status, reject_reason = "INVALID_OUTPUT", str(exc)
    except ValueError as exc:
        replay_status, reject_reason = "INSUFFICIENT_HISTORY", str(exc)
    except AssertionError as exc:
        replay_status, reject_reason = "INVALID_OUTPUT", str(exc)
    except Exception as exc:  # noqa: BLE001
        replay_status, reject_reason = "REPLAY_ERROR", str(exc)

    history_cutoff = history[-1]["draw"] if history else None

    prov_hash = (
        _provenance_hash(strategy_id, str(target["draw"]), json.loads(predicted_numbers))
        if predicted_numbers
        else None
    )

    return {
        "lottery_type": LOTTERY_TYPE,
        "target_draw": str(target["draw"]),
        "target_date": target.get("date"),
        "strategy_id": strategy_id,
        "strategy_name": strategy_name,
        "strategy_version": strategy_version,
        "history_cutoff_draw": str(history_cutoff) if history_cutoff else None,
        "replay_status": replay_status,
        "reject_reason": reject_reason,
        "predicted_numbers": predicted_numbers,
        "predicted_special": None,
        "actual_numbers": json.dumps(target["numbers"]),
        "actual_special": None,
        "hit_numbers": hit_numbers,
        "hit_count": hit_count,
        "special_hit": 0,
        "replay_run_id": RUN_ID,
        "generated_at": now_str,
        "truth_level": TRUTH_LEVEL,
        "controlled_apply_id": CONTROLLED_APPLY_ID,
        "source": SOURCE,
        "provenance_hash": prov_hash,
        "provenance_source": "p540b_daily539_incremental_replay_generation.py",
        "dry_run": 0,
        "prediction_cutoff_date": history[-1]["date"] if history else None,
        "prediction_generated_at": now_str,
        "bet_index": 1,
    }


def generate_rows(all_draws: list[dict], target_draws: list[str], adapters: list[Any]) -> list[dict]:
    """Pure generation (no DB access): causal-sliced predictions for every
    (adapter, target_draw) pair. `all_draws` must be the FULL chronological
    history (read-only load); `target_draws` are the draw-id strings to
    generate rows for."""
    target_set = set(target_draws)
    by_draw_index = {d["draw"]: i for i, d in enumerate(all_draws)}

    rows: list[dict] = []
    for adapter in adapters:
        for target_draw_id in target_draws:
            idx = by_draw_index[target_draw_id]
            history = all_draws[:idx]  # strictly before -- no leakage
            target = all_draws[idx]
            assert target["draw"] in target_set
            rows.append(_run_one_prediction(adapter, history, target))
    return rows


def apply_rows_transactional(
    db_path: Path | str, rows: list[dict], expected_pre_count_daily539: int
) -> dict[str, Any]:
    """Single atomic transaction. Verifies the pre-count inside the
    transaction before inserting (protects against drift since the
    manifest was built), inserts, and rolls back on any mismatch."""
    conn = sqlite3.connect(str(db_path))
    try:
        conn.execute("BEGIN EXCLUSIVE")

        current_daily539 = conn.execute(
            "SELECT COUNT(*) FROM strategy_prediction_replays WHERE lottery_type = ?",
            (LOTTERY_TYPE,),
        ).fetchone()[0]
        if current_daily539 != expected_pre_count_daily539:
            conn.rollback()
            raise RuntimeError(
                f"PRE-COUNT DRIFT: expected {expected_pre_count_daily539} DAILY_539 rows, "
                f"found {current_daily539} at write time. Aborting without writing."
            )

        inserted = 0
        duplicates = 0
        for row in rows:
            try:
                conn.execute(
                    """
                    INSERT INTO strategy_prediction_replays (
                        lottery_type, target_draw, target_date, strategy_id,
                        strategy_name, strategy_version, history_cutoff_draw,
                        replay_status, reject_reason, predicted_numbers,
                        predicted_special, actual_numbers, actual_special,
                        hit_numbers, hit_count, special_hit, replay_run_id,
                        generated_at, truth_level, controlled_apply_id, source,
                        provenance_hash, provenance_source, dry_run,
                        prediction_cutoff_date, prediction_generated_at, bet_index
                    ) VALUES (
                        :lottery_type, :target_draw, :target_date, :strategy_id,
                        :strategy_name, :strategy_version, :history_cutoff_draw,
                        :replay_status, :reject_reason, :predicted_numbers,
                        :predicted_special, :actual_numbers, :actual_special,
                        :hit_numbers, :hit_count, :special_hit, :replay_run_id,
                        :generated_at, :truth_level, :controlled_apply_id, :source,
                        :provenance_hash, :provenance_source, :dry_run,
                        :prediction_cutoff_date, :prediction_generated_at, :bet_index
                    )
                    """,
                    row,
                )
                inserted += 1
            except sqlite3.IntegrityError:
                duplicates += 1

        if duplicates != 0:
            conn.rollback()
            raise RuntimeError(
                f"UNEXPECTED DUPLICATES during apply: {duplicates} rows hit the UNIQUE "
                "constraint. Rolled back without committing."
            )
        if inserted != len(rows):
            conn.rollback()
            raise RuntimeError(
                f"INSERT COUNT MISMATCH: expected {len(rows)}, inserted {inserted}. Rolled back."
            )

        conn.commit()
        return {"inserted": inserted, "duplicates": duplicates, "committed": True}
    except Exception:
        try:
            conn.rollback()
        except sqlite3.Error:
            pass
        raise
    finally:
        conn.close()


def build_dry_run_preview(db_path: Path | str) -> dict[str, Any]:
    """Read-only: builds manifest + generates rows in-memory, no write."""
    conn = _open_ro(db_path)
    try:
        pre_snapshot = build_pre_write_snapshot(conn)
        adapters = _build_adapters()
        manifest = build_manifest(pre_snapshot, adapters)
        ok, problems = is_manifest_internally_consistent(manifest)
        if not ok:
            return {"manifest": manifest, "manifest_consistent": False, "problems": problems, "rows": []}

        all_draws = load_lottery_draws(conn, LOTTERY_TYPE)
        rows = generate_rows(all_draws, manifest["target_draw_ids"], adapters)
    finally:
        conn.close()

    predicted = sum(1 for r in rows if r["replay_status"] == "PREDICTED")
    errors = len(rows) - predicted
    return {
        "pre_write_snapshot": pre_snapshot,
        "manifest": manifest,
        "manifest_consistent": True,
        "problems": [],
        "rows": rows,
        "row_count": len(rows),
        "matches_manifest_expected_count": len(rows) == manifest["expected_inserted_rows"],
        "predicted_count": predicted,
        "error_count": errors,
    }


def verify_post_write(
    db_path: Path | str,
    pre_snapshot: dict[str, Any],
    manifest: dict[str, Any],
    apply_result: dict[str, Any],
) -> dict[str, Any]:
    """READ-ONLY. Recomputes post-write snapshot + invariants against the
    current DB state. Safe to call independently of apply_rows_transactional
    (e.g. to re-verify a write that already committed)."""
    conn = _open_ro(db_path)
    try:
        post_snapshot = build_pre_write_snapshot(conn)

        inserted_by_draw = dict(
            conn.execute(
                "SELECT target_draw, COUNT(*) FROM strategy_prediction_replays "
                "WHERE controlled_apply_id = ? GROUP BY target_draw",
                (manifest["controlled_apply_id"],),
            ).fetchall()
        )
        big_lotto_after = conn.execute(
            "SELECT COUNT(*) FROM strategy_prediction_replays WHERE lottery_type = 'BIG_LOTTO'"
        ).fetchone()[0]
        power_lotto_after = conn.execute(
            "SELECT COUNT(*) FROM strategy_prediction_replays WHERE lottery_type = 'POWER_LOTTO'"
        ).fetchone()[0]
        # IS NOT (not !=) -- controlled_apply_id is NULL on rows pre-dating this
        # convention, and `!= ?` silently drops NULL rows under SQL's
        # three-valued logic, undercounting "existing rows left untouched".
        pre_existing_daily539_unchanged = conn.execute(
            "SELECT COUNT(*) FROM strategy_prediction_replays "
            "WHERE lottery_type = 'DAILY_539' AND CAST(target_draw AS INTEGER) <= ? "
            "AND controlled_apply_id IS NOT ?",
            (int(pre_snapshot["daily539_latest_replayed_target_draw"] or 0), manifest["controlled_apply_id"]),
        ).fetchone()[0]
    finally:
        conn.close()

    pre_daily539 = pre_snapshot["strategy_prediction_replays_count_by_lottery"].get(LOTTERY_TYPE, 0)
    post_daily539 = post_snapshot["strategy_prediction_replays_count_by_lottery"].get(LOTTERY_TYPE, 0)
    pre_big_lotto = pre_snapshot["strategy_prediction_replays_count_by_lottery"].get("BIG_LOTTO", 0)
    pre_power_lotto = pre_snapshot["strategy_prediction_replays_count_by_lottery"].get("POWER_LOTTO", 0)

    invariants_checked = {
        "inserted_row_count_matches_manifest": apply_result["inserted"] == manifest["expected_inserted_rows"],
        "daily539_count_increased_by_expected_amount": (post_daily539 - pre_daily539) == manifest["expected_inserted_rows"],
        "big_lotto_unchanged": big_lotto_after == pre_big_lotto,
        "power_lotto_unchanged": power_lotto_after == pre_power_lotto,
        "no_existing_daily539_rows_touched": pre_existing_daily539_unchanged == pre_daily539,
        "new_rows_cover_exactly_target_draws": sorted(inserted_by_draw.keys()) == sorted(manifest["target_draw_ids"]),
    }
    return {
        "post_write_snapshot": post_snapshot,
        "inserted_rows_by_draw": inserted_by_draw,
        "invariants_checked": invariants_checked,
        "all_invariants_pass": all(invariants_checked.values()),
    }


def run_write(db_path: Path | str) -> dict[str, Any]:
    """Full pipeline: pre-snapshot -> manifest -> dry-run generation ->
    consistency check -> transactional apply -> post-snapshot -> invariants."""
    db_hash_before = _file_sha256(db_path)

    preview = build_dry_run_preview(db_path)
    if not preview["manifest_consistent"]:
        raise RuntimeError(f"Manifest inconsistent, refusing to write: {preview['problems']}")
    if not preview["matches_manifest_expected_count"]:
        raise RuntimeError("Dry-run row count does not match manifest expected count, refusing to write.")

    manifest = preview["manifest"]
    rows = preview["rows"]
    pre_snapshot = preview["pre_write_snapshot"]

    apply_result = apply_rows_transactional(
        db_path, rows, expected_pre_count_daily539=pre_snapshot["strategy_prediction_replays_count_by_lottery"].get(LOTTERY_TYPE, 0)
    )

    db_hash_after = _file_sha256(db_path)
    verification = verify_post_write(db_path, pre_snapshot, manifest, apply_result)
    all_invariants_pass = verification["all_invariants_pass"]

    return {
        "task_id": TASK_ID,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "classification": (
            "P540B_DB_WRITE_COMPLETE_PR_OPENED_WAITING_OWNER_MERGE_AUTHORIZATION"
            if all_invariants_pass
            else "P540B_BLOCKED_DB_WRITE_MISMATCH"
        ),
        "pre_write_snapshot": pre_snapshot,
        "manifest": manifest,
        "write_execution_summary": apply_result,
        "post_write_snapshot": verification["post_write_snapshot"],
        "inserted_rows_by_draw": verification["inserted_rows_by_draw"],
        "invariants_checked": verification["invariants_checked"],
        "all_invariants_pass": all_invariants_pass,
        "db_access": {
            "db_path": str(db_path),
            "db_sha256_before": db_hash_before,
            "db_sha256_after": db_hash_after,
            "db_changed": db_hash_before != db_hash_after,
        },
        "rollback_location": manifest["rollback_method"],
        "recommended_next_task": (
            "P540C_BIGLOTTO_POWERLOTTO_INCREMENTAL_REPLAY_GENERATION (still short of "
            "MINIMUM_SUPPORT_DRAWS_FLOOR per P540A; wait for more official draws) or "
            "P540D_RESOLVE_EXCLUDED_STRATEGIES (recover/clarify daily539_f4cold_3bet/5bet and "
            "the 3 excluded bet_index=2,3 carve-outs before including them in a future backfill)"
        ),
        "disclaimer_en": DISCLAIMER_EN,
    }


def render_markdown(result: dict[str, Any]) -> str:
    lines: list[str] = []
    add = lines.append
    add("# P540B — DAILY_539 Incremental Replay Generation (Manifested DB Write)")
    add("")
    add(f"> {DISCLAIMER_EN}")
    add("")
    add(f"classification: `{result['classification']}`")
    add("")
    add("## Manifest")
    add("")
    m = result["manifest"]
    add(f"- target_lottery: `{m['target_lottery']}`")
    add(f"- target_draw_count: `{m['target_draw_count']}`")
    add(f"- in_scope_strategy_id_count: `{m['in_scope_strategy_id_count']}`")
    add(f"- expected_inserted_rows: `{m['expected_inserted_rows']}`")
    add(f"- controlled_apply_id: `{m['controlled_apply_id']}`")
    add("")
    add("## Write Execution Summary")
    add("")
    add(f"- inserted: `{result['write_execution_summary']['inserted']}`")
    add(f"- duplicates: `{result['write_execution_summary']['duplicates']}`")
    add(f"- committed: `{result['write_execution_summary']['committed']}`")
    add("")
    add("## Invariants Checked")
    add("")
    for k, v in result["invariants_checked"].items():
        add(f"- {k}: `{v}`")
    add("")
    add("## DB Access")
    add("")
    add(f"- db_changed: `{result['db_access']['db_changed']}`")
    add(f"- db_sha256_before: `{result['db_access']['db_sha256_before'][:16]}...`")
    add(f"- db_sha256_after: `{result['db_access']['db_sha256_after'][:16]}...`")
    add("")
    add("## Excluded From This Manifest")
    add("")
    for sid, reason in m["excluded_strategy_ids"].items():
        add(f"- **{sid}** (entire strategy excluded): {reason}")
    for sid, reason in m["excluded_bet_indices"].items():
        add(f"- **{sid}** (bet_index 2+ excluded): {reason}")
    add("")
    add("## Rollback")
    add("")
    add(f"`{result['rollback_location']}`")
    add("")
    add("## Recommended Next Task")
    add("")
    add(result["recommended_next_task"])
    add("")
    return "\n".join(lines)


def write_artifacts(result: dict[str, Any], out_json: Path, out_md: Path) -> None:
    if out_json.exists():
        raise FileExistsError(f"refusing to overwrite existing artifact: {out_json}")
    if out_md.exists():
        raise FileExistsError(f"refusing to overwrite existing artifact: {out_md}")
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(result, ensure_ascii=False, indent=2, default=str) + "\n", encoding="utf-8")
    out_md.write_text(render_markdown(result) + "\n", encoding="utf-8")


def _default_dated_paths() -> tuple[Path, Path]:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d")
    json_path = OUTPUT_DIR / f"p540b_daily539_incremental_replay_generation_{stamp}.json"
    md_path = OUTPUT_DIR / f"p540b_daily539_incremental_replay_generation_{stamp}.md"
    return json_path, md_path


def main(argv: list[str] | None = None) -> int:
    default_json, default_md = _default_dated_paths()
    parser = argparse.ArgumentParser(description="P540B DAILY_539 incremental replay generation")
    parser.add_argument("--db", default=str(DEFAULT_DB_PATH))
    parser.add_argument("--mode", choices=["manifest", "dry-run", "apply"], default="dry-run")
    parser.add_argument("--out-json", default=str(default_json))
    parser.add_argument("--out-md", default=str(default_md))
    args = parser.parse_args(argv)

    if args.mode == "manifest":
        conn = _open_ro(args.db)
        try:
            pre_snapshot = build_pre_write_snapshot(conn)
            manifest = build_manifest(pre_snapshot, _build_adapters())
        finally:
            conn.close()
        print(json.dumps(manifest, indent=2, ensure_ascii=False))
        return 0

    if args.mode == "dry-run":
        preview = build_dry_run_preview(args.db)
        print(
            json.dumps(
                {
                    "manifest_consistent": preview["manifest_consistent"],
                    "row_count": preview.get("row_count"),
                    "matches_manifest_expected_count": preview.get("matches_manifest_expected_count"),
                    "predicted_count": preview.get("predicted_count"),
                    "error_count": preview.get("error_count"),
                },
                indent=2,
            )
        )
        return 0

    # apply
    result = run_write(args.db)
    write_artifacts(result, Path(args.out_json), Path(args.out_md))
    print(json.dumps({"classification": result["classification"], "out_json": args.out_json}, ensure_ascii=False))
    return 0 if result["all_invariants_pass"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
