"""
draw_no_hygiene.py — Centralised draw_no validation helpers
=============================================================

Production draw_no: purely numeric AND within the valid range for the game
type, e.g. "114001" or "115000105" for DAILY_539.

Test / synthetic draw_no: starts with one of the known test prefixes, is a
sentinel value (PENDING / UNKNOWN), or is a numeric string whose value falls
outside the valid production range (e.g. 9300279486 — generated by test
harnesses that use Unix-timestamp-derived identifiers).

All modules that need to distinguish real draws from synthetic ones should
import from here rather than hard-coding individual LIKE clauses.

Rules
-----
  is_production_draw_no(draw_no, game_type) -> bool
      True  only for non-empty purely-numeric strings within the game's
      valid draw_no range.

  is_test_draw_no(draw_no, game_type) -> bool
      True  for known test/synthetic prefixes, sentinel values, and any
      numeric draw_no that fails the range check.

SQL helper
----------
  production_draw_no_sql_filter(column, game_type) -> str
      Returns a WHERE fragment that keeps only production draw_nos.
      Embed as: f"AND {production_draw_no_sql_filter()}"

Per-game draw_no ranges
-----------------------
  DAILY_539 (今彩539):
      Draw numbers follow the ROC-era sequential format.
      Real examples: 114001 (6 digits), 115000104 (9 digits).
      Valid range : 1_000 – 999_999_999  (4–9 digits)
      Rejects     : 9300279486 (10 digits, synthetic/test harness artefact)

  Other game types: same 4–9 digit rule applies until a tighter range is
  established from observed data.

2026-04-29  Created (H6 draw_no hygiene guard)
2026-04-30  Strengthened: added per-game-type numeric range check to reject
            synthetic high-value draw_nos (e.g. 9300279486, 9300297780).
"""
from __future__ import annotations

import re
from typing import Tuple

# ── test prefixes (order does not matter — all checked via str.startswith) ───
_TEST_PREFIXES: Tuple[str, ...] = (
    "AUTO_",
    "S1_",
    "E2E_",
    "RB_",
    "RBISO_",
    "TEST_",
    "MOCK_",
)

# Sentinel values that are never valid draw identifiers
_SENTINEL_VALUES: Tuple[str, ...] = (
    "PENDING",
    "UNKNOWN",
)

# Production draw_no: 1 or more decimal digits, nothing else
_PRODUCTION_RE = re.compile(r"^\d+$")

# ── Per-game-type draw_no value range ────────────────────────────────────────
# DAILY_539: ROC sequential draw numbers, currently 6–9 digits.
# Upper bound of 999_999_999 (max 9-digit integer) rejects 10-digit synthetic
# values such as 9300279486 which were generated by test harnesses using
# Unix-timestamp offsets.
_DRAW_NO_MIN: int = 1_000           # 4 digits (historical buffer)
_DRAW_NO_MAX: int = 999_999_999     # 9 digits — enough for ROC year up to ~999


def is_production_draw_no(draw_no: str, game_type: str = "DAILY_539") -> bool:
    """Return True iff *draw_no* is a legitimate production draw number.

    Checks:
      1. Non-empty purely-numeric string (no prefix/suffix chars).
      2. Numeric value within the valid range for *game_type*.

    Real DAILY_539 examples that pass: "114001", "115000104", "115000105".
    Synthetic examples that fail: "9300279486" (10 digits, > 999_999_999).
    """
    if not draw_no or not isinstance(draw_no, str):
        return False
    if not _PRODUCTION_RE.match(draw_no):
        return False
    # Range check — rejects synthetic 10-digit timestamp-derived draw_nos
    val = int(draw_no)
    return _DRAW_NO_MIN <= val <= _DRAW_NO_MAX


def is_test_draw_no(draw_no: str, game_type: str = "DAILY_539") -> bool:
    """Return True iff *draw_no* is a synthetic/test identifier.

    Covers:
      - Known prefixes: AUTO_, S1_, E2E_, RB_, RBISO_, TEST_, MOCK_
      - Sentinel values: PENDING, UNKNOWN (case-insensitive)
      - Any purely-numeric string that falls outside the valid production
        range (e.g. 9300279486 → synthetic/test harness artefact)
      - Any non-numeric string not matching a known prefix (catch-all)
    """
    if not draw_no or not isinstance(draw_no, str):
        return True  # empty / None → treat as test
    upper = draw_no.upper()
    if upper in _SENTINEL_VALUES:
        return True
    for prefix in _TEST_PREFIXES:
        if upper.startswith(prefix):
            return True
    # Numeric draw_nos that fall outside the production range are synthetic
    return not is_production_draw_no(draw_no, game_type)


def production_draw_no_sql_filter(column: str = "draw_no", game_type: str = "DAILY_539") -> str:
    """Return a SQL WHERE fragment (no leading AND) that passes only production draw_nos.

    SQLite strategy:
      - Round-trip check ensures the string is *purely* numeric.
      - Value bounds reject synthetic high-value draw_nos generated by test
        harnesses (e.g. 9300279486, a Unix-timestamp-derived identifier).

    Valid range (all game types): 1_000 – 999_999_999 (4–9 digits).

    Usage::

        sql = f\"\"\"
            SELECT draw_no FROM live_strategy_predictions
            WHERE game_type=? AND strategy_name=?
              AND {production_draw_no_sql_filter()}
            ORDER BY generated_at DESC LIMIT 1
        \"\"\"
    """
    return (
        f"(CAST({column} AS INTEGER) >= {_DRAW_NO_MIN}"
        f" AND CAST({column} AS INTEGER) <= {_DRAW_NO_MAX}"
        f" AND CAST(CAST({column} AS INTEGER) AS TEXT) = {column})"
    )
