"""
P255B — Ingest Write Guard Design

Design-only artifact script.  Converts P255A findings into a concrete
specification for future P255C implementation.

Produces:
  outputs/research/p255b_ingest_write_guard_design_20260608.json
  outputs/research/p255b_ingest_write_guard_design_20260608.md

No DB write, no code change, no registry mutation, no strategy promotion.
Authorization: Authorize P255B Ingest Write Guard Design
"""

import json
import os
from datetime import datetime, timezone

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_OUT_DIR   = os.path.join(_REPO_ROOT, "outputs", "research")
_DATE_TAG  = "20260608"
_JSON_OUT  = os.path.join(_OUT_DIR, f"p255b_ingest_write_guard_design_{_DATE_TAG}.json")
_MD_OUT    = os.path.join(_OUT_DIR, f"p255b_ingest_write_guard_design_{_DATE_TAG}.md")
os.makedirs(_OUT_DIR, exist_ok=True)

# ---------------------------------------------------------------------------
# P255A dependency reference
# ---------------------------------------------------------------------------

P255A_DEPENDENCY = {
    "artifact": f"outputs/research/p255a_ingest_backfill_safety_audit_{_DATE_TAG}.json",
    "pr": 363,
    "classification": "INGEST_BACKFILL_SAFETY_AUDIT_COMPLETE",
    "key_findings": {
        "write_capable_paths": 5,
        "auto_trigger_risks": 6,
        "guardrails_recommended": 8,
        "critical_gap_1": "BackfillRequest.dry_run defaults to False — any omitted caller writes to DB",
        "critical_gap_2": "Frontend confirmation gate is UI-only; server has no authorization layer",
    },
    "verified": True,
}

# ---------------------------------------------------------------------------
# G01: default dry_run=True
# ---------------------------------------------------------------------------

G01 = {
    "id": "G01",
    "priority": "P0",
    "title": "Change BackfillRequest.dry_run default to True",
    "current_state": {
        "file": "lottery_api/routes/ingest.py",
        "line": 44,
        "current_code": "dry_run: bool = False",
        "risk": "Any POST to /api/ingest/backfill that omits dry_run writes to DB",
    },
    "proposed_default": True,
    "proposed_code": "dry_run: bool = True",
    "behavior_when_omitted": "Treated as dry_run=True (safe preview only; no DB write)",
    "behavior_for_write": "Caller must explicitly set dry_run=False AND supply apply_confirmed=True",
    "backward_compatibility": {
        "breaking_for": "Any existing caller that relies on dry_run=False being the default",
        "safe_for": "All existing test clients (they pass dry_run=True explicitly)",
        "migration_action": "Audit all callers and ensure explicit dry_run=False where writes are intended",
    },
    "error_semantics": {
        "dry_run_false_without_confirm": {
            "http_status": 422,
            "body": {
                "error": "write_not_confirmed",
                "message": "dry_run=False requires apply_confirmed=True and a valid confirm_token",
                "hint": "Run with dry_run=True first to get a preview and confirm_token",
            },
        },
    },
    "applies_to": ["POST /api/ingest/backfill", "POST /api/ingest/fetch-latest (insert_if_new=True)"],
    "implementation_done": False,
}

# ---------------------------------------------------------------------------
# G02: server-side confirm token
# ---------------------------------------------------------------------------

G02 = {
    "id": "G02",
    "priority": "P0",
    "title": "Require server-side confirm token for any non-dry-run write",
    "rationale": (
        "The frontend confirmation gate (bfConfirmCheck) is UI-only JavaScript. "
        "A direct HTTP POST bypasses it entirely. "
        "The server must independently validate that the caller has explicitly opted into a write."
    ),
    "new_request_fields": {
        "apply_confirmed": {
            "type": "bool",
            "default": False,
            "required_for_write": True,
            "description": "Must be True for dry_run=False to be accepted",
        },
        "confirm_token": {
            "type": "Optional[str]",
            "default": None,
            "required_for_write": True,
            "description": (
                "Opaque token generated by a prior dry-run response. "
                "Encodes: lottery_type + expected_insert_count + timestamp + HMAC. "
                "Server validates token has not expired (TTL=300s) and matches request context."
            ),
            "token_format": "p255-{lottery_type}-{expected_count}-{unix_ts}-{hmac_sha256[:16]}",
            "token_ttl_seconds": 300,
        },
        "requested_by": {
            "type": "str",
            "default": "unknown",
            "description": "Caller identifier for audit log (e.g. 'ui', 'cli', 'script:p255c')",
        },
        "reason": {
            "type": "str",
            "default": "",
            "description": "Human-readable reason for write (e.g. 'fetcher repair backfill 2026-06-08')",
        },
        "expected_insert_count": {
            "type": "Optional[int]",
            "default": None,
            "description": (
                "Number of draws the caller expects to insert, from prior dry-run. "
                "If provided and actual count differs by >0, server returns 409 Conflict."
            ),
        },
    },
    "server_validation_logic": [
        "if dry_run is True: skip all token validation (read-only path)",
        "if dry_run is False and apply_confirmed is not True: return 422 write_not_confirmed",
        "if dry_run is False and confirm_token is None: return 422 missing_confirm_token",
        "if dry_run is False and token is expired (>TTL): return 422 token_expired",
        "if dry_run is False and token HMAC invalid: return 422 invalid_confirm_token",
        "if dry_run is False and expected_insert_count provided and actual differs: return 409 count_mismatch",
        "if all checks pass: proceed with write",
    ],
    "dry_run_response_additions": {
        "confirm_token": "Generated and returned in dry_run=True response for use in apply call",
        "token_expires_at": "ISO-8601 timestamp when confirm_token expires",
        "expected_insert_count": "Number of draws that would be inserted in apply call",
    },
    "invalid_token_response": {
        "http_status": 422,
        "body": {
            "error": "invalid_confirm_token",
            "message": "The confirm_token is missing, invalid, or expired. Re-run dry_run=True to get a fresh token.",
            "token_ttl_seconds": 300,
        },
    },
    "missing_token_response": {
        "http_status": 422,
        "body": {
            "error": "missing_confirm_token",
            "message": "Non-dry-run write requires confirm_token from a prior dry-run response.",
            "hint": "POST with dry_run=True first, capture confirm_token from response, then POST with dry_run=False",
        },
    },
    "count_mismatch_response": {
        "http_status": 409,
        "body": {
            "error": "count_mismatch",
            "message": "Expected N draws to insert but found M in current scan. DB may have changed since dry-run.",
            "hint": "Re-run dry_run=True to get a fresh count and confirm_token",
        },
    },
    "applies_to": ["POST /api/ingest/backfill", "POST /api/ingest/fetch-latest (insert_if_new=True)"],
    "implementation_done": False,
}

# ---------------------------------------------------------------------------
# G03: UI confirmation expectations
# ---------------------------------------------------------------------------

G03 = {
    "id": "G03",
    "priority": "P1",
    "title": "UI confirmation: write-preview-first, apply-second flow",
    "rationale": (
        "The current checkbox-based confirmation can be left checked across sessions. "
        "The modal must show exactly what will be written and reset after each operation."
    ),
    "required_flow": [
        "1. User clicks 'Dry-Run Preview' button",
        "2. Server returns dry-run summary: total, would-insert count, draw list, confirm_token, expires_at",
        "3. UI displays preview table and enables 'Apply Write' button (only if inserted_count > 0)",
        "4. User clicks 'Apply Write' → modal dialog appears",
        "5. Modal shows: 'You are about to write N draws to the database: [draw list]. This cannot be undone automatically.'",
        "6. Modal has two buttons: 'Confirm Write' and 'Cancel'",
        "7. On confirm: UI sends POST with dry_run=False, apply_confirmed=True, confirm_token from step 2",
        "8. Modal and confirmation state reset after response (success or error)",
        "9. Page load / auto-refresh MUST NEVER send POST with dry_run=False",
    ],
    "forbidden_behaviors": [
        "Sending dry_run=False on page load",
        "Sending dry_run=False on periodic auto-refresh",
        "Reusing a confirm_token across multiple apply attempts",
        "Leaving the confirmation state persistent across tab reloads",
        "Enabling 'Apply Write' without first completing a dry-run preview",
    ],
    "auto_load_constraint": {
        "GET /api/ingest/log": "ALLOWED — read-only, fires on page load",
        "POST /api/ingest/backfill (dry_run=True)": "ALLOWED if explicitly user-initiated",
        "POST /api/ingest/backfill (dry_run=False)": "FORBIDDEN on auto-load or auto-refresh",
    },
    "modal_copy_requirements": {
        "title": "Confirm Database Write",
        "body_template": "You are about to write {n} draw(s) to the {lottery_type} database. This action will be logged but cannot be automatically undone.",
        "draw_list_display": "Show each draw number, date, and numbers to be inserted",
        "action_buttons": ["Confirm Write", "Cancel"],
        "auto_close_on_success": True,
        "reset_confirm_state_after": "every operation (success or failure)",
    },
    "file_to_modify_in_p255c": "src/ui/AutoFetchManager.js",
    "implementation_done": False,
}

# ---------------------------------------------------------------------------
# G04: audit log requirements
# ---------------------------------------------------------------------------

G04 = {
    "id": "G04",
    "priority": "P1",
    "title": "Audit log requirements: every write attempt must be fully logged",
    "log_file": "lottery_api/data/ingest_log.jsonl",
    "current_log_fields": [
        "timestamp", "action", "lottery_type", "draw", "status", "message", "data"
    ],
    "required_additional_fields_for_write": {
        "dry_run": "bool — was this call dry_run or not",
        "trigger_source": "str — 'ui' | 'api_direct' | 'test' | 'script'",
        "requested_by": "str — caller identifier from BackfillRequest.requested_by",
        "reason": "str — from BackfillRequest.reason",
        "pre_count": "int — DB row count for lottery_type before write",
        "post_count": "int — DB row count for lottery_type after write (null for dry_run)",
        "inserted_draws": "list[str] — draw numbers actually inserted",
        "confirm_token_used": "str — first 8 chars of confirm_token (not full for security)",
        "expected_insert_count": "int | null — from request",
        "actual_insert_count": "int — actual inserts",
        "db_sha256_before": "str — SHA256 of DB file before write (null for dry_run)",
        "db_sha256_after": "str — SHA256 of DB file after write (null for dry_run or failure)",
        "result": "str — 'ok' | 'partial' | 'error' | 'rejected' | 'dry_run'",
    },
    "log_timing": {
        "on_write_start": "Log pre_count + db_sha256_before + confirm_token_used",
        "on_write_complete": "Log inserted_draws + post_count + db_sha256_after + result",
        "on_validation_failure": "Log rejection reason (missing token, expired, count mismatch)",
    },
    "log_entry_example": {
        "timestamp": "2026-06-08T10:14:00Z",
        "action": "backfill_apply",
        "lottery_type": "BIG_LOTTO",
        "draw": None,
        "status": "ok",
        "message": "inserted=1, skipped=0, conflict=0, failed=0",
        "data": {
            "dry_run": False,
            "trigger_source": "ui",
            "requested_by": "ui",
            "reason": "fetcher repair backfill",
            "pre_count": 22238,
            "post_count": 22239,
            "inserted_draws": ["115000059"],
            "confirm_token_used": "p255-BIG",
            "expected_insert_count": 1,
            "actual_insert_count": 1,
            "db_sha256_before": "abc123...",
            "db_sha256_after": "def456...",
            "result": "ok",
        },
    },
    "extends_existing": "IngestLogger.log() — add fields to data dict; no schema break",
    "implementation_done": False,
}

# ---------------------------------------------------------------------------
# G05: controlled-apply backup/SHA
# ---------------------------------------------------------------------------

G05 = {
    "id": "G05",
    "priority": "P1",
    "title": "Controlled-apply style DB SHA and optional backup before any write batch",
    "rationale": (
        "P254B incident showed no rollback point existed after an accidental write. "
        "Any future write path should record a verifiable pre-write state."
    ),
    "required_steps_before_insert": [
        "1. Compute SHA256 of lottery_api/data/lottery_v2.db → pre_sha",
        "2. Log pre_sha to ingest_log (G04 audit entry)",
        "3. Optional: if INGEST_BACKUP_ON_WRITE=true, call sqlite3.connect(db_path).backup(backup_conn)",
        "4. Backup file name: lottery_v2_{lottery_type}_{timestamp}.db.bak",
        "5. Proceed with db_manager.insert_draws()",
        "6. Compute SHA256 post-write → post_sha",
        "7. Log post_sha + delta (post_count - pre_count) to ingest_log",
    ],
    "sha256_implementation": {
        "algorithm": "hashlib.sha256",
        "input": "open(db_path, 'rb').read()",
        "note": "For large DBs, use chunked read: update in 65536-byte blocks",
    },
    "backup_policy": {
        "env_var": "INGEST_BACKUP_ON_WRITE",
        "default": False,
        "backup_dir": "lottery_api/data/backups/",
        "retention": "Keep last 10 backups per lottery_type; auto-prune older ones",
    },
    "abort_on_sha_mismatch": {
        "scenario": "Server computes pre_sha; but pre_sha does not match expected_db_sha in request",
        "action": "Abort write; return 409 db_state_changed",
        "note": "UI can optionally send expected_db_sha from prior dry-run to enable this check",
    },
    "file_to_modify_in_p255c": "lottery_api/fetcher/backfill_engine.py :: _insert()",
    "implementation_done": False,
}

# ---------------------------------------------------------------------------
# G06: idempotency / duplicate protection
# ---------------------------------------------------------------------------

G06 = {
    "id": "G06",
    "priority": "P1",
    "title": "Server-side idempotency: per-request key and per-draw DB constraint",
    "layers": {
        "layer_1_per_request": {
            "mechanism": "idempotency_key in BackfillRequest",
            "type": "Optional[str]",
            "format": "UUID v4 or caller-generated opaque string",
            "server_behavior": (
                "Server logs idempotency_key at write start. "
                "If same key received again within TTL=60s, return 409 already_processed."
            ),
            "ttl_seconds": 60,
            "storage": "In-memory dict or ingest_log scan (simpler: log-based dedup)",
        },
        "layer_2_per_draw": {
            "mechanism": "DB UNIQUE constraint on (lottery_type, draw)",
            "current_state": "Already present — insert_draws() returns (inserted, dupes)",
            "behavior": "Duplicate draw silently becomes skipped (not error)",
            "note": "This is already implemented; G06 only adds the request-level layer",
        },
    },
    "idempotency_key_response_conflict": {
        "http_status": 409,
        "body": {
            "error": "already_processed",
            "message": "A write with this idempotency_key was already received within the last 60 seconds.",
            "hint": "Use a new idempotency_key for a fresh write attempt.",
        },
    },
    "implementation_done": False,
}

# ---------------------------------------------------------------------------
# G07: CORS hardening
# ---------------------------------------------------------------------------

G07 = {
    "id": "G07",
    "priority": "P2",
    "title": "Remove wildcard CORS origin; gate wildcard behind env-var",
    "current_state": {
        "file": "lottery_api/app.py",
        "line_range": "30-36",
        "current_origins": ["http://localhost:3000", "http://localhost:5173", "http://127.0.0.1:3000", "http://127.0.0.1:5173", "*"],
        "risk": "Wildcard allows any cross-origin page to POST to write-capable endpoints",
    },
    "proposed_origins_default": [
        "http://localhost:3000",
        "http://localhost:5173",
        "http://localhost:8081",
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
        "http://127.0.0.1:8081",
    ],
    "env_var": "INGEST_CORS_ALLOW_ALL",
    "env_default": False,
    "behavior": "If INGEST_CORS_ALLOW_ALL=true, append '*' to origins (dev override only)",
    "startup_warning": "Log WARNING if INGEST_CORS_ALLOW_ALL=true at startup",
    "file_to_modify_in_p255c": "lottery_api/app.py",
    "implementation_done": False,
}

# ---------------------------------------------------------------------------
# G08: env write gate
# ---------------------------------------------------------------------------

G08 = {
    "id": "G08",
    "priority": "P2",
    "title": "INGEST_WRITE_ENABLED env-var gate for write-capable endpoints",
    "rationale": (
        "Allows read-only monitoring (log, scan, dry-run) without exposing the write path. "
        "Maintenance windows can be opened by setting INGEST_WRITE_ENABLED=true."
    ),
    "env_var": "INGEST_WRITE_ENABLED",
    "default": False,
    "behavior_when_false": {
        "GET /api/ingest/status": "ALLOWED",
        "GET /api/ingest/scan-missing": "ALLOWED",
        "GET /api/ingest/log": "ALLOWED",
        "POST /api/ingest/backfill (dry_run=True)": "ALLOWED",
        "POST /api/ingest/backfill (dry_run=False)": "BLOCKED → 503",
        "POST /api/ingest/fetch-latest (insert_if_new=True)": "BLOCKED → 503",
        "POST /api/ingest/log/clear": "BLOCKED → 503",
    },
    "blocked_response": {
        "http_status": 503,
        "body": {
            "error": "ingest_write_disabled",
            "message": "Ingest write operations are currently disabled.",
            "hint": "Set INGEST_WRITE_ENABLED=true in the server environment to enable writes.",
        },
    },
    "startup_log": "Log INFO: INGEST_WRITE_ENABLED=false/true at startup",
    "startup_warning": "Log WARNING if INGEST_WRITE_ENABLED=true in production context",
    "file_to_modify_in_p255c": "lottery_api/routes/ingest.py (dependency injection or middleware)",
    "implementation_done": False,
}

# ---------------------------------------------------------------------------
# Request / response contract design
# ---------------------------------------------------------------------------

REQUEST_CONTRACT = {
    "endpoint": "POST /api/ingest/backfill",
    "current_schema": {
        "lottery_type": "str = 'BIG_LOTTO'",
        "draw_list": "Optional[List[str]] = None",
        "dry_run": "bool = False  ← DANGEROUS DEFAULT",
        "max_draws": "int = 30 (capped 1-500)",
    },
    "proposed_schema": {
        "lottery_type": "str = 'BIG_LOTTO'",
        "draw_list": "Optional[List[str]] = None",
        "dry_run": "bool = True  ← CHANGED DEFAULT (G01)",
        "max_draws": "int = 30 (capped 1-500)",
        "apply_confirmed": "bool = False  ← NEW (G02)",
        "confirm_token": "Optional[str] = None  ← NEW (G02)",
        "requested_by": "str = 'unknown'  ← NEW (G04)",
        "reason": "str = ''  ← NEW (G04)",
        "expected_insert_count": "Optional[int] = None  ← NEW (G02/G05)",
        "idempotency_key": "Optional[str] = None  ← NEW (G06)",
    },
    "validation_order": [
        "1. Check INGEST_WRITE_ENABLED (G08) — if false and dry_run=False, return 503",
        "2. Check G01: if dry_run=False, require apply_confirmed=True",
        "3. Check G02: if dry_run=False, require confirm_token (not None, not expired, HMAC valid)",
        "4. Check G06: if idempotency_key present, check for recent duplicate",
        "5. Compute pre_sha (G05) and log audit entry start (G04)",
        "6. Proceed with BackfillEngine.run()",
        "7. Log audit entry complete (G04) with post_sha",
    ],
}

RESPONSE_CONTRACT = {
    "dry_run_response": {
        "success": True,
        "summary": {
            "lottery_type": "str",
            "dry_run": True,
            "total": "int",
            "inserted": "int (would-be-inserted count)",
            "skipped": "int",
            "conflict": "int",
            "failed": "int",
            "details": "list[dict] per draw",
        },
        "write_guard": {
            "confirm_token": "str (generated token for apply call)",
            "token_expires_at": "ISO-8601 (now + 300s)",
            "expected_insert_count": "int (same as inserted count)",
        },
    },
    "apply_response": {
        "success": True,
        "summary": {
            "lottery_type": "str",
            "dry_run": False,
            "total": "int",
            "inserted": "int",
            "skipped": "int",
            "conflict": "int",
            "failed": "int",
            "details": "list[dict] per draw",
        },
        "write_guard": {
            "db_sha256_before": "str",
            "db_sha256_after": "str",
            "pre_count": "int",
            "post_count": "int",
            "idempotency_key": "str | null",
        },
    },
    "error_responses": {
        "422_write_not_confirmed": "dry_run=False without apply_confirmed=True",
        "422_missing_confirm_token": "dry_run=False without confirm_token",
        "422_invalid_confirm_token": "token is malformed or HMAC invalid",
        "422_token_expired": "token TTL exceeded (>300s since dry-run)",
        "409_count_mismatch": "expected_insert_count != actual pending count",
        "409_already_processed": "idempotency_key seen within last 60s",
        "409_db_state_changed": "pre_sha does not match expected_db_sha",
        "503_write_disabled": "INGEST_WRITE_ENABLED=false",
    },
}

FAILURE_MODES = [
    {
        "id": "F01",
        "scenario": "Caller sends POST /api/ingest/backfill with no dry_run field",
        "current_behavior": "dry_run=False → WRITES to DB (incident path)",
        "proposed_behavior": "dry_run=True (new default) → dry-run preview only",
        "guard": "G01",
    },
    {
        "id": "F02",
        "scenario": "Caller sends dry_run=False without apply_confirmed or confirm_token",
        "current_behavior": "Writes to DB (no server validation)",
        "proposed_behavior": "422 write_not_confirmed / 422 missing_confirm_token",
        "guard": "G02",
    },
    {
        "id": "F03",
        "scenario": "Confirm token expired (user waited >5 min between dry-run and apply)",
        "current_behavior": "N/A (no token system)",
        "proposed_behavior": "422 token_expired; user must re-run dry-run",
        "guard": "G02",
    },
    {
        "id": "F04",
        "scenario": "DB changed between dry-run and apply (another agent inserted draws)",
        "current_behavior": "Silently inserts or skips — no warning to caller",
        "proposed_behavior": "409 count_mismatch if expected_insert_count provided",
        "guard": "G02/G05",
    },
    {
        "id": "F05",
        "scenario": "Network retry sends same apply request twice",
        "current_behavior": "Second call silently skips duplicates (DB UNIQUE constraint)",
        "proposed_behavior": "409 already_processed if idempotency_key matches within TTL",
        "guard": "G06",
    },
    {
        "id": "F06",
        "scenario": "Frontend auto-refresh or page reload triggers write",
        "current_behavior": "Possible if JS state is dirty (confirmed checkbox left checked)",
        "proposed_behavior": "FORBIDDEN by G03 contract; server requires confirm_token from fresh dry-run",
        "guard": "G02/G03",
    },
    {
        "id": "F07",
        "scenario": "INGEST_WRITE_ENABLED=false and someone tries to write",
        "current_behavior": "N/A (env gate does not exist)",
        "proposed_behavior": "503 ingest_write_disabled",
        "guard": "G08",
    },
    {
        "id": "F08",
        "scenario": "Missing confirm_token (direct API call bypassing UI)",
        "current_behavior": "Writes to DB with no additional check",
        "proposed_behavior": "422 missing_confirm_token",
        "guard": "G02",
    },
]

# ---------------------------------------------------------------------------
# Future P255C implementation scope
# ---------------------------------------------------------------------------

P255C_SCOPE = {
    "task_id": "P255C",
    "title": "Implement P255B ingest write guard specification",
    "authorization_required": "Separate explicit user authorization before P255C can start",
    "implementation_done": False,
    "scope": {
        "files_to_modify": [
            "lottery_api/routes/ingest.py — BackfillRequest schema + validation logic",
            "lottery_api/fetcher/backfill_engine.py — pre/post SHA, backup hook",
            "lottery_api/fetcher/ingest_logger.py — extended log fields",
            "lottery_api/app.py — CORS env-var gate",
            "src/ui/AutoFetchManager.js — modal confirmation flow + dry_run=True default",
        ],
        "files_to_create": [
            "lottery_api/utils/write_guard.py — confirm_token generation/validation, idempotency cache",
            "lottery_api/utils/db_sha.py — SHA256 + backup utilities",
        ],
        "new_tests": [
            "tests/test_p255c_write_guard_integration.py — TestClient tests for all G01-G08 paths",
        ],
        "no_db_schema_change": True,
        "no_strategy_change": True,
        "no_registry_change": True,
    },
    "pre_conditions": [
        "P255B design artifact reviewed and approved",
        "Explicit user authorization phrase received",
        "P247G guard baseline remains 22239/2114 before implementation",
        "All prior regression tests pass before starting",
    ],
    "estimated_affected_test_count": "~20-40 new tests for write-guard paths",
    "not_in_p255c_scope": [
        "Live backfill execution",
        "Strategy promotion",
        "Registry changes",
        "DB schema migration",
        "Prediction improvement",
    ],
}

# ---------------------------------------------------------------------------
# Current accepted baseline (carried forward from P255A)
# ---------------------------------------------------------------------------

CURRENT_ACCEPTED_BASELINE = {
    "BIG_LOTTO_raw": 22239,
    "BIG_LOTTO_canonical": 2114,
    "BIG_LOTTO_add_on": 19100,
    "POWER_LOTTO_raw": 1917,
    "DAILY_539_raw": 5882,
    "strategy_prediction_replays": 94924,
    "source": "PR #360 ACCEPT_BACKFILL_DB_DRIFT_2026_0608",
    "stale_must_not_reuse": {
        "BIG_LOTTO_raw_stale": 22238,
        "BIG_LOTTO_canonical_stale": 2113,
    },
}

# ---------------------------------------------------------------------------
# Main artifact
# ---------------------------------------------------------------------------

ARTIFACT = {
    "schema_version": "1.0",
    "task_id": "P255B",
    "classification": "INGEST_WRITE_GUARD_DESIGN_COMPLETE",
    "date": "2026-06-08",
    "task_type": "Type B design-only",
    "explicit_authorization": "Authorize P255B Ingest Write Guard Design",
    "generated_at": datetime.now(timezone.utc).isoformat(),

    "phase0_summary": {
        "repo": "/Users/kelvin/Kelvin-WorkSpace/LotteryNew",
        "branch": "main",
        "HEAD": "3bcf767c4efb5ed1625edbafac396cc0b792b31e",
        "HEAD_equals_origin_main": True,
        "all_stop_conditions_clear": True,
    },

    "p255a_dependency_verified": True,
    "p255a_dependency": P255A_DEPENDENCY,

    "design_scope": {
        "task": "Convert P255A audit findings (G01-G08) into a concrete implementable specification",
        "does_not_include": [
            "API behavior changes",
            "Frontend modifications",
            "DB writes",
            "Strategy promotion",
            "Registry changes",
        ],
        "p255c_authorization_required": True,
    },

    "guardrail_designs": {
        "G01_default_dry_run_true": G01,
        "G02_server_side_confirm_token": G02,
        "G03_ui_confirmation": G03,
        "G04_audit_log": G04,
        "G05_backup_sha_integrity": G05,
        "G06_idempotency": G06,
        "G07_cors_hardening": G07,
        "G08_env_write_gate": G08,
    },

    "request_contract_design": REQUEST_CONTRACT,
    "response_contract_design": RESPONSE_CONTRACT,
    "failure_mode_design": FAILURE_MODES,

    "future_p255c_implementation_scope": P255C_SCOPE,

    "current_accepted_baseline": CURRENT_ACCEPTED_BASELINE,

    "non_actions": [
        "No DB write performed",
        "No API behavior changed",
        "No frontend modified",
        "No fetcher code changed",
        "No registry mutation",
        "No strategy promotion",
        "No betting advice",
        "No P247G constants changed",
        "No P255C implementation started",
    ],

    "no_db_write_confirmed": True,
    "no_registry_mutation_confirmed": True,
    "no_strategy_promotion_confirmed": True,
    "no_betting_advice_confirmed": True,

    "recommended_next_task": (
        "HOLD.  P255B design-only artifact is complete.  "
        "P255C implementation requires a separate explicit user authorization.  "
        "No action should be taken on the write guard design without that authorization."
    ),

    "final_decision": (
        "HOLD.  P255B design is complete.  G01-G08 specifications are documented.  "
        "No code was modified.  No DB write occurred.  "
        "P255C implementation requires: 'Authorize P255C Ingest Write Guard Implementation'.  "
        "System returns to WAITING_FOR_USER_AUTHORIZATION."
    ),
}


# ---------------------------------------------------------------------------
# Markdown builder
# ---------------------------------------------------------------------------

def _build_markdown(a: dict) -> str:
    lines = []
    lines.append("# P255B — Ingest Write Guard Design")
    lines.append(
        "\n**Date:** 2026-06-08  \n**Task Type:** Type B design-only  \n"
        "**Authorization:** Authorize P255B Ingest Write Guard Design  \n"
        "**Classification:** `INGEST_WRITE_GUARD_DESIGN_COMPLETE`\n"
    )

    lines.append("## Executive Summary\n")
    lines.append(
        "P255B converts the P255A audit findings into a concrete implementable write-guard "
        "specification.  The design covers 8 guardrails (G01-G08), a revised BackfillRequest "
        "schema, a two-phase dry-run→apply flow with HMAC-based confirm tokens, extended audit "
        "logging, pre-write SHA checkpointing, idempotency protection, CORS hardening, and an "
        "environment-gated write enable flag.  "
        "No code was modified.  P255C implementation requires separate explicit authorization.\n"
    )

    lines.append("## Background from P255A\n")
    p = a["p255a_dependency"]
    lines.append(f"- P255A PR: [#{p['pr']}](https://github.com/kelvinhuang0327/number-pattern-research/pull/{p['pr']})")
    for k, v in p["key_findings"].items():
        lines.append(f"- {k}: {v}")
    lines.append("")

    lines.append("## Guardrail Design Table\n")
    lines.append("| ID | Priority | Title | Implementation Done |")
    lines.append("|---|---|---|:---:|")
    for gid, g in a["guardrail_designs"].items():
        lines.append(f"| {g['id']} | {g['priority']} | {g['title']} | NO |")
    lines.append("")

    lines.append("## G01 — Default dry_run=True\n")
    g = a["guardrail_designs"]["G01_default_dry_run_true"]
    lines.append(f"**Current:** `{g['current_state']['current_code']}` — {g['current_state']['risk']}")
    lines.append(f"\n**Proposed:** `{g['proposed_code']}`")
    lines.append(f"\n**When dry_run omitted:** {g['behavior_when_omitted']}")
    lines.append(f"\n**Write path:** {g['behavior_for_write']}\n")
    lines.append("**Backward compatibility:**")
    bc = g["backward_compatibility"]
    lines.append(f"- Breaking for: {bc['breaking_for']}")
    lines.append(f"- Safe for: {bc['safe_for']}")
    lines.append(f"- Action: {bc['migration_action']}\n")
    err = g["error_semantics"]["dry_run_false_without_confirm"]
    lines.append(f"**Error (dry_run=False without confirm):** HTTP {err['http_status']} — `{err['body']['error']}`\n")

    lines.append("## G02 — Server-Side Confirm Token\n")
    g = a["guardrail_designs"]["G02_server_side_confirm_token"]
    lines.append(f"{g['rationale']}\n")
    lines.append("**New BackfillRequest fields:**\n")
    lines.append("| Field | Type | Default | Purpose |")
    lines.append("|---|---|---|---|")
    for field, spec in g["new_request_fields"].items():
        lines.append(f"| `{field}` | `{spec['type']}` | `{spec['default']}` | {spec['description'][:60]}... |")
    lines.append("")
    lines.append("**Server validation order:**")
    for step in g["server_validation_logic"]:
        lines.append(f"- {step}")
    lines.append("\n**Token format:** `" + g["new_request_fields"]["confirm_token"]["token_format"] + "`")
    lines.append(f"\n**Token TTL:** {g['new_request_fields']['confirm_token']['token_ttl_seconds']}s\n")
    lines.append("**Error responses:**")
    lines.append(f"- Missing token: HTTP 422 `missing_confirm_token`")
    lines.append(f"- Invalid token: HTTP 422 `invalid_confirm_token`")
    lines.append(f"- Count mismatch: HTTP 409 `count_mismatch`\n")

    lines.append("## Request / Response Contract Proposal\n")
    rc = a["request_contract_design"]
    lines.append("**Proposed BackfillRequest schema:**\n```")
    for field, spec in rc["proposed_schema"].items():
        lines.append(f"  {field}: {spec}")
    lines.append("```\n")
    lines.append("**Validation order:**")
    for step in rc["validation_order"]:
        lines.append(f"- {step}")
    lines.append("")
    rsp = a["response_contract_design"]
    lines.append("**Dry-run response additions (write_guard block):**")
    for k, v in rsp["dry_run_response"]["write_guard"].items():
        lines.append(f"- `{k}`: {v}")
    lines.append("\n**Apply response additions (write_guard block):**")
    for k, v in rsp["apply_response"]["write_guard"].items():
        lines.append(f"- `{k}`: {v}")
    lines.append("\n**Error response codes:**")
    for code, desc in rsp["error_responses"].items():
        lines.append(f"- `{code}`: {desc}")
    lines.append("")

    lines.append("## UI Confirmation Expectations (G03)\n")
    g = a["guardrail_designs"]["G03_ui_confirmation"]
    lines.append("**Required flow:**")
    for step in g["required_flow"]:
        lines.append(f"- {step}")
    lines.append("\n**Forbidden behaviors:**")
    for fb in g["forbidden_behaviors"]:
        lines.append(f"- {fb}")
    lines.append("\n**Modal copy requirements:**")
    mc = g["modal_copy_requirements"]
    lines.append(f"- Title: \"{mc['title']}\"")
    lines.append(f"- Body template: \"{mc['body_template']}\"")
    lines.append(f"- Buttons: {mc['action_buttons']}\n")

    lines.append("## Audit Log Requirements (G04)\n")
    g = a["guardrail_designs"]["G04_audit_log"]
    lines.append(f"**Log file:** `{g['log_file']}`\n")
    lines.append("**Required additional fields per write attempt:**")
    for field, desc in g["required_additional_fields_for_write"].items():
        lines.append(f"- `{field}`: {desc}")
    lines.append("")

    lines.append("## Backup / SHA / Integrity Requirements (G05)\n")
    g = a["guardrail_designs"]["G05_backup_sha_integrity"]
    lines.append("**Required steps before any DB insert:**")
    for step in g["required_steps_before_insert"]:
        lines.append(f"- {step}")
    bp = g["backup_policy"]
    lines.append(f"\n**Backup policy:** env `{bp['env_var']}` (default: {bp['default']}), dir `{bp['backup_dir']}`, retention: {bp['retention']}\n")

    lines.append("## Idempotency / Duplicate Guard (G06)\n")
    g = a["guardrail_designs"]["G06_idempotency"]
    for layer, spec in g["layers"].items():
        lines.append(f"**{layer}:** {spec['mechanism']} — TTL {spec.get('ttl_seconds', 'N/A')}s")
    lines.append("")

    lines.append("## Lower-Priority Guardrails\n")
    g7 = a["guardrail_designs"]["G07_cors_hardening"]
    lines.append(f"**G07 [P2] CORS:** Remove `'*'` from origins. Gate behind `{g7['env_var']}` env-var (default: {g7['env_default']}).\n")
    g8 = a["guardrail_designs"]["G08_env_write_gate"]
    lines.append(f"**G08 [P2] Write Gate:** `{g8['env_var']}` env-var (default: {g8['default']}). When false, write-capable endpoints return HTTP 503.\n")

    lines.append("## Failure Mode Design\n")
    lines.append("| ID | Scenario | Current | Proposed | Guard |")
    lines.append("|---|---|---|---|---|")
    for f in a["failure_mode_design"]:
        lines.append(f"| {f['id']} | {f['scenario'][:50]} | {f['current_behavior'][:40]} | {f['proposed_behavior'][:40]} | {f['guard']} |")
    lines.append("")

    lines.append("## Future P255C Implementation Scope\n")
    p255c = a["future_p255c_implementation_scope"]
    lines.append(f"**Authorization required:** `Authorize P255C Ingest Write Guard Implementation`\n")
    lines.append(f"**Implementation done:** {p255c['implementation_done']} (P255B is design-only)\n")
    lines.append("**Files to modify in P255C:**")
    for f in p255c["scope"]["files_to_modify"]:
        lines.append(f"- {f}")
    lines.append("\n**Files to create in P255C:**")
    for f in p255c["scope"]["files_to_create"]:
        lines.append(f"- {f}")
    lines.append("\n**Pre-conditions before P255C:**")
    for pc in p255c["pre_conditions"]:
        lines.append(f"- {pc}")
    lines.append("")

    lines.append("## Current Accepted Baseline\n")
    bl = a["current_accepted_baseline"]
    lines.append("| Table / View | Count |")
    lines.append("|---|---:|")
    lines.append(f"| BIG_LOTTO raw draws | {bl['BIG_LOTTO_raw']:,} |")
    lines.append(f"| BIG_LOTTO canonical draws | {bl['BIG_LOTTO_canonical']:,} |")
    lines.append(f"| BIG_LOTTO ADD_ON excluded | {bl['BIG_LOTTO_add_on']:,} |")
    lines.append(f"| POWER_LOTTO raw draws | {bl['POWER_LOTTO_raw']:,} |")
    lines.append(f"| DAILY_539 raw draws | {bl['DAILY_539_raw']:,} |")
    lines.append(f"| strategy_prediction_replays | {bl['strategy_prediction_replays']:,} |\n")

    lines.append("## Explicit Non-Actions\n")
    for na in a["non_actions"]:
        lines.append(f"- {na}")
    lines.append("")

    lines.append("## Recommended Next Task\n")
    lines.append(f"{a['recommended_next_task']}\n")

    lines.append("## Required Completion Check\n")
    lines.append("| Item | Status |")
    lines.append("|---|---|")
    lines.append("| Completed | YES |")
    lines.append("| Test Result | see pytest run |")
    lines.append("| Single Blocking Issue | NONE |")
    lines.append("| Modified Files | 4 (analysis + json + md + test) |")
    lines.append("| No DB write | YES |")
    lines.append("| No code change | YES |")
    lines.append("| Final Classification | `INGEST_WRITE_GUARD_DESIGN_COMPLETE` |")
    lines.append("| Strong Model Needed | NO |")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    md = _build_markdown(ARTIFACT)

    with open(_JSON_OUT, "w", encoding="utf-8") as f:
        json.dump(ARTIFACT, f, indent=2, ensure_ascii=False)
    print(f"JSON: {_JSON_OUT}")

    with open(_MD_OUT, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"MD:   {_MD_OUT}")

    print(f"\nSummary:")
    print(f"  Guardrail designs    : {len(ARTIFACT['guardrail_designs'])}")
    print(f"  Failure modes        : {len(ARTIFACT['failure_mode_design'])}")
    print(f"  No DB write          : {ARTIFACT['no_db_write_confirmed']}")
    print(f"  Classification       : {ARTIFACT['classification']}")
    print(f"  Final decision       : HOLD")


if __name__ == "__main__":
    main()
