#!/usr/bin/env python3
"""
H6 Production Observation Check
================================
Usage:
    python3 scripts/h6_observation_check.py           # human-readable
    python3 scripts/h6_observation_check.py --json    # machine-readable JSON

Reads directly from SQLite + local files — works even if the backend is down.
Returns exit code 0 (OK), 1 (WATCH), or 2 (ACTION_REQUIRED).
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import sqlite3
import sys
from datetime import datetime, timezone

# ── Project root ────────────────────────────────────────────────────────────
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(_SCRIPT_DIR)

# ── Constants ────────────────────────────────────────────────────────────────
DB_PATH = os.path.join(PROJECT_ROOT, "runtime", "agent_orchestrator", "orchestrator.db")
REPORT_DIR = os.path.join(PROJECT_ROOT, "runtime", "h6_daily_reports")
DAEMON_STATE_PATH = os.path.join(
    PROJECT_ROOT, "runtime", "agent_orchestrator", "locks", "copilot_daemon_state.json"
)

H6_STRATEGY_ID = "H6_gate_mk20\u2192ew85"   # H6_gate_mk20→ew85
GAME_TYPE = "DAILY_539"

DAEMON_HEARTBEAT_TTL = int(os.environ.get("COPILOT_DAEMON_HEARTBEAT_TTL", "45"))

# Rollback / edge thresholds (mirrors h6_live_monitor.py)
ROLLBACK_EDGE_THRESHOLD = -0.02


# ────────────────────────────────────────────────────────────────────────────
# Helpers
# ────────────────────────────────────────────────────────────────────────────

def _production_draw_filter(col: str) -> str:
    """SQL fragment: keep only production draw_no / draw_id rows.

    Applies the same range as draw_no_hygiene.production_draw_no_sql_filter:
      - purely numeric (round-trip cast)
      - value in [1_000, 999_999_999]  (4–9 digits, rejects 10-digit synthetic
        test values like 9300279486 generated by timestamp-based harnesses)
    """
    return (
        f"(CAST({col} AS INTEGER) >= 1000"
        f" AND CAST({col} AS INTEGER) <= 999999999"
        f" AND CAST(CAST({col} AS INTEGER) AS TEXT) = {col})"
    )


def _is_process_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
        return True
    except (ProcessLookupError, PermissionError):
        return False


def _db_conn() -> sqlite3.Connection:
    if not os.path.exists(DB_PATH):
        raise FileNotFoundError(f"DB not found: {DB_PATH}")
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


# ────────────────────────────────────────────────────────────────────────────
# Section collectors
# ────────────────────────────────────────────────────────────────────────────

def _collect_strategy_state(conn: sqlite3.Connection) -> dict:
    row = conn.execute(
        "SELECT * FROM active_strategy_state WHERE game_type=?", (GAME_TYPE,)
    ).fetchone()
    if row is None:
        return {
            "active_strategy": None,
            "shadow_strategy": None,
            "rollback_status": None,
            "rollback_triggered": None,
            "planner_focus": None,
            "error": "no row in active_strategy_state for DAILY_539",
        }
    return {
        "active_strategy": row["active_strategy"],
        "shadow_strategy": row["shadow_strategy"],
        "rollback_status": row["rollback_status"],
        "rollback_triggered": bool(row["rollback_triggered"]),
        "planner_focus": row["planner_focus"] if "planner_focus" in row.keys() else None,
    }


def _collect_live_metrics(conn: sqlite3.Connection) -> dict:
    row = conn.execute(
        "SELECT * FROM active_strategy_state WHERE game_type=?", (GAME_TYPE,)
    ).fetchone()
    if row is None:
        return {"error": "no active_strategy_state row"}

    keys = row.keys()
    return {
        "live_30p_edge": row["live_30p_edge"] if "live_30p_edge" in keys else None,
        "live_50p_edge": row["live_50p_edge"] if "live_50p_edge" in keys else None,
        "consecutive_negative_30p": (
            row["consecutive_negative_30p"] if "consecutive_negative_30p" in keys else None
        ),
        "current_regime": row["current_regime"] if "current_regime" in keys else None,
        "bear_regime_warning": (
            bool(row["bear_regime_warning"]) if "bear_regime_warning" in keys else None
        ),
    }


def _collect_latest_report() -> dict:
    """Scan REPORT_DIR for most recent *.json and extract key fields."""
    if not os.path.isdir(REPORT_DIR):
        return {
            "latest_h6_risk_level": None,
            "latest_h6_action_recommendation": None,
            "latest_h6_daily_report_path": None,
            "error": f"report dir missing: {REPORT_DIR}",
        }
    # Prefer reports with numeric draw_no in filename; skip test-named and UNKNOWN
    all_json = sorted(glob.glob(os.path.join(REPORT_DIR, "H6_DAILY_*.json")), reverse=True)

    def _draw_no_from_path(p: str) -> str:
        """Extract draw_no from filename H6_DAILY_539_REPORT_<draw_no>.json"""
        base = os.path.splitext(os.path.basename(p))[0]
        prefix = "H6_DAILY_539_REPORT_"
        if base.startswith(prefix):
            return base[len(prefix):]
        # generic fallback: take last _-separated segment
        return base.split("_")[-1]

    def _is_production_report(p: str) -> bool:
        dn = _draw_no_from_path(p)
        return dn.isdigit()

    chosen = None
    for p in all_json:
        if _is_production_report(p):
            chosen = p
            break
    # Fall back to UNKNOWN only if no production report exists
    if chosen is None and all_json:
        chosen = next(
            (p for p in all_json if "UNKNOWN" in os.path.basename(p)),
            all_json[0],  # last resort: any file
        )

    if chosen is None:
        return {
            "latest_h6_risk_level": None,
            "latest_h6_action_recommendation": None,
            "latest_h6_daily_report_path": None,
        }
    try:
        with open(chosen, encoding="utf-8") as f:
            report = json.load(f)
        # Field path varies slightly across report schema versions
        risk_level = (
            report.get("risk_assessment", {}).get("risk_level")
            or report.get("risk_level")
        )
        action = (
            report.get("action_recommendation", {}).get("action")
            or report.get("action_recommendation")
            or report.get("action")
        )
        return {
            "latest_h6_risk_level": risk_level,
            "latest_h6_action_recommendation": action,
            "latest_h6_daily_report_path": chosen,
        }
    except Exception as exc:
        return {
            "latest_h6_risk_level": None,
            "latest_h6_action_recommendation": None,
            "latest_h6_daily_report_path": chosen,
            "error": f"failed to parse report: {exc}",
        }


def _collect_data_hygiene(conn: sqlite3.Connection) -> dict:
    prod_pred_filter = _production_draw_filter("draw_no")
    prod_out_filter = _production_draw_filter("draw_id")

    non_numeric_pred = conn.execute(
        f"SELECT COUNT(*) FROM live_strategy_predictions WHERE game_type=? AND NOT {prod_pred_filter}",
        (GAME_TYPE,),
    ).fetchone()[0]

    non_numeric_out = conn.execute(
        f"SELECT COUNT(*) FROM live_strategy_outcomes WHERE game_type=? AND NOT {prod_out_filter}",
        (GAME_TYPE,),
    ).fetchone()[0]

    # CTO backlog items caused by H6 test draw_no
    # finding_id pattern: h6_alert:DAILY_539:<draw_no>
    # Test draw_nos contain non-numeric prefixes e.g. AUTO_, S1_, T4_BAD_, E2E_, etc.
    h6_test_cto = conn.execute(
        r"""SELECT COUNT(*) FROM cto_backlog_items
           WHERE finding_id LIKE 'h6_alert:%'
             AND (
                 finding_id LIKE '%AUTO\_%' ESCAPE '\' OR
                 finding_id LIKE '%S1\_%' ESCAPE '\' OR
                 finding_id LIKE '%E2E\_%' ESCAPE '\' OR
                 finding_id LIKE '%RB\_%' ESCAPE '\' OR
                 finding_id LIKE '%RBISO\_%' ESCAPE '\' OR
                 finding_id LIKE '%TEST\_%' ESCAPE '\' OR
                 finding_id LIKE '%MOCK\_%' ESCAPE '\' OR
                 finding_id LIKE '%T4\_%' ESCAPE '\' OR
                 finding_id LIKE '%PENDING' OR
                 finding_id LIKE '%UNKNOWN'
             )
        """,
    ).fetchone()[0]

    # H6 tasks in RUNNING state that match rollback keywords (orphan detection)
    h6_running_rollback = conn.execute(
        """SELECT COUNT(*) FROM agent_tasks
           WHERE status='RUNNING'
             AND (title LIKE '%rollback%' OR title LIKE '%ROLLBACK%'
                  OR slug LIKE '%rollback%')
        """,
    ).fetchone()[0]

    return {
        "non_numeric_predictions_count": non_numeric_pred,
        "non_numeric_outcomes_count": non_numeric_out,
        "h6_test_cto_backlog_count": h6_test_cto,
        "h6_running_rollback_task_count": h6_running_rollback,
    }


def _collect_scheduler_health(conn: sqlite3.Connection) -> dict:
    # Queued research tasks older than 5 minutes
    queued_research_over_5min = conn.execute(
        """SELECT COUNT(*) FROM agent_tasks
           WHERE status='QUEUED'
             AND (worker_type='research' OR worker_type IS NULL)
             AND created_at < datetime('now', '-5 minutes')
        """,
    ).fetchone()[0]

    # Active locks (any row in agent_locks)
    active_locks = conn.execute("SELECT COUNT(*) FROM agent_locks").fetchone()[0]

    # Daemon status from state file
    daemon_running = False
    daemon_status = "unknown"
    daemon_pid = None
    if os.path.exists(DAEMON_STATE_PATH):
        try:
            with open(DAEMON_STATE_PATH, encoding="utf-8") as f:
                state = json.load(f)
            pid = state.get("pid")
            heartbeat_at = state.get("heartbeat_at")
            daemon_pid = pid
            daemon_status = state.get("status", "unknown")
            if pid and heartbeat_at and _is_process_alive(pid):
                last = datetime.fromisoformat(heartbeat_at)
                stale = (datetime.now(timezone.utc) - last).total_seconds() > DAEMON_HEARTBEAT_TTL
                daemon_running = not stale
                if stale:
                    daemon_status = "stale"
        except Exception:
            pass

    return {
        "copilot_daemon_running": daemon_running,
        "copilot_daemon_pid": daemon_pid,
        "copilot_daemon_status": daemon_status,
        "queued_research_over_5min_count": queued_research_over_5min,
        "active_locks_count": active_locks,
    }


# ────────────────────────────────────────────────────────────────────────────
# Verdict logic
# ────────────────────────────────────────────────────────────────────────────

def _compute_verdict(
    strategy_state: dict,
    live_metrics: dict,
    latest_report: dict,
    data_hygiene: dict,
    scheduler_health: dict,
) -> tuple[str, list[str]]:
    """
    Returns (verdict, reasons).
    verdict: "OK" | "WATCH" | "ACTION_REQUIRED"
    """
    reasons: list[str] = []
    verdict = "OK"

    def _promote(level: str, reason: str) -> None:
        nonlocal verdict
        reasons.append(reason)
        if level == "ACTION_REQUIRED":
            verdict = "ACTION_REQUIRED"
        elif level == "WATCH" and verdict == "OK":
            verdict = "WATCH"

    # ── Strategy state ────────────────────────────────────────────────────
    rollback_status = strategy_state.get("rollback_status")
    if rollback_status is None:
        _promote("ACTION_REQUIRED", "active_strategy_state row missing for DAILY_539")
    elif rollback_status != "ACTIVE":
        _promote("ACTION_REQUIRED", f"rollback_status={rollback_status!r} (expected ACTIVE)")

    if strategy_state.get("rollback_triggered"):
        _promote("ACTION_REQUIRED", "rollback_triggered=true")

    # ── Live metrics ──────────────────────────────────────────────────────
    edge_30 = live_metrics.get("live_30p_edge")
    if edge_30 is not None and edge_30 < ROLLBACK_EDGE_THRESHOLD:
        _promote("ACTION_REQUIRED", f"live_30p_edge={edge_30:.4f} < {ROLLBACK_EDGE_THRESHOLD}")

    consec = live_metrics.get("consecutive_negative_30p")
    if consec is not None:
        if consec >= 7:
            _promote("ACTION_REQUIRED", f"consecutive_negative_30p={consec} >= 7")
        elif consec >= 5:
            _promote("WATCH", f"consecutive_negative_30p={consec} >= 5")

    if live_metrics.get("bear_regime_warning"):
        _promote("WATCH", "bear_regime_warning=true")

    if live_metrics.get("current_regime") == "BEAR":
        _promote("WATCH", "current_regime=BEAR")

    # ── Latest report ─────────────────────────────────────────────────────
    risk_level = latest_report.get("latest_h6_risk_level")
    if risk_level == "HIGH":
        _promote("ACTION_REQUIRED", "latest_h6_risk_level=HIGH")
    elif risk_level == "MEDIUM":
        _promote("WATCH", "latest_h6_risk_level=MEDIUM")

    action = latest_report.get("latest_h6_action_recommendation")
    if action in ("ROLLBACK_ACTIVE", "MANUAL_REVIEW_REQUIRED"):
        _promote("ACTION_REQUIRED", f"latest_h6_action_recommendation={action!r}")
    elif action == "PREPARE_ROLLBACK":
        _promote("WATCH", "latest_h6_action_recommendation=PREPARE_ROLLBACK")

    # ── Data hygiene ──────────────────────────────────────────────────────
    if data_hygiene.get("non_numeric_predictions_count", 0) > 0:
        n = data_hygiene["non_numeric_predictions_count"]
        _promote("ACTION_REQUIRED", f"non_numeric_predictions_count={n} (DB contaminated)")

    if data_hygiene.get("non_numeric_outcomes_count", 0) > 0:
        n = data_hygiene["non_numeric_outcomes_count"]
        _promote("ACTION_REQUIRED", f"non_numeric_outcomes_count={n} (DB contaminated)")

    if data_hygiene.get("h6_test_cto_backlog_count", 0) > 0:
        n = data_hygiene["h6_test_cto_backlog_count"]
        _promote("ACTION_REQUIRED", f"h6_test_cto_backlog_count={n} (test draw leaked to CTO backlog)")

    # ── Scheduler health ──────────────────────────────────────────────────
    if not scheduler_health.get("copilot_daemon_running", False):
        _promote("ACTION_REQUIRED", "copilot_daemon is not running / stale heartbeat")

    qr = scheduler_health.get("queued_research_over_5min_count", 0)
    if qr > 3:
        _promote("ACTION_REQUIRED", f"queued_research_over_5min_count={qr} (severe backlog)")
    elif qr > 0:
        _promote("WATCH", f"queued_research_over_5min_count={qr}")

    locks = scheduler_health.get("active_locks_count", 0)
    if locks > 2:
        _promote("WATCH", f"active_locks_count={locks}")

    return verdict, reasons


# ────────────────────────────────────────────────────────────────────────────
# Output
# ────────────────────────────────────────────────────────────────────────────

def _exit_code(verdict: str) -> int:
    return {"OK": 0, "WATCH": 1, "ACTION_REQUIRED": 2}.get(verdict, 2)


def _print_human(result: dict) -> None:
    ss = result["strategy_state"]
    lm = result["live_metrics"]
    lr = result["latest_report"]
    dh = result["data_hygiene"]
    sh = result["scheduler_health"]
    verdict = result["observation_verdict"]
    reasons = result["verdict_reasons"]

    RESET = "\033[0m"
    BOLD = "\033[1m"
    GREEN = "\033[32m"
    YELLOW = "\033[33m"
    RED = "\033[31m"
    verdict_color = {"OK": GREEN, "WATCH": YELLOW, "ACTION_REQUIRED": RED}.get(verdict, RESET)

    print(f"\n{BOLD}╔══ H6 Production Observation Check ══╗{RESET}")
    ts = result.get("checked_at", "")
    print(f"  checked_at : {ts}")
    print()

    print(f"{BOLD}── Strategy State ────────────────────{RESET}")
    print(f"  active_strategy     : {ss.get('active_strategy')}")
    print(f"  shadow_strategy     : {ss.get('shadow_strategy')}")
    print(f"  rollback_status     : {ss.get('rollback_status')}")
    print(f"  rollback_triggered  : {ss.get('rollback_triggered')}")
    print(f"  planner_focus       : {ss.get('planner_focus')}")
    print()

    print(f"{BOLD}── Live Metrics ──────────────────────{RESET}")
    print(f"  live_30p_edge             : {lm.get('live_30p_edge')}")
    print(f"  live_50p_edge             : {lm.get('live_50p_edge')}")
    print(f"  consecutive_negative_30p  : {lm.get('consecutive_negative_30p')}")
    print(f"  current_regime            : {lm.get('current_regime')}")
    print(f"  bear_regime_warning       : {lm.get('bear_regime_warning')}")
    print()

    print(f"{BOLD}── Latest Report ─────────────────────{RESET}")
    print(f"  risk_level          : {lr.get('latest_h6_risk_level')}")
    print(f"  action              : {lr.get('latest_h6_action_recommendation')}")
    print(f"  report_path         : {lr.get('latest_h6_daily_report_path')}")
    if "error" in lr:
        print(f"  [warning]           : {lr['error']}")
    print()

    print(f"{BOLD}── Data Hygiene ──────────────────────{RESET}")
    print(f"  non_numeric_predictions  : {dh.get('non_numeric_predictions_count')}")
    print(f"  non_numeric_outcomes     : {dh.get('non_numeric_outcomes_count')}")
    print(f"  h6_test_cto_backlog      : {dh.get('h6_test_cto_backlog_count')}")
    print(f"  h6_running_rollback_task : {dh.get('h6_running_rollback_task_count')}")
    print()

    print(f"{BOLD}── Scheduler Health ──────────────────{RESET}")
    daemon_icon = "✓" if sh.get("copilot_daemon_running") else "✗"
    print(f"  copilot_daemon_running   : {daemon_icon} ({sh.get('copilot_daemon_status')} pid={sh.get('copilot_daemon_pid')})")
    print(f"  queued_research_>5min    : {sh.get('queued_research_over_5min_count')}")
    print(f"  active_locks             : {sh.get('active_locks_count')}")
    print()

    print(f"{BOLD}══ Observation Verdict ═══════════════{RESET}")
    print(f"  {verdict_color}{BOLD}{verdict}{RESET}")
    if reasons:
        print("  Reasons:")
        for r in reasons:
            print(f"    • {r}")
    else:
        print("  All checks passed.")
    print()


# ────────────────────────────────────────────────────────────────────────────
# Entry point
# ────────────────────────────────────────────────────────────────────────────

def run_check() -> dict:
    conn = _db_conn()
    try:
        strategy_state = _collect_strategy_state(conn)
        live_metrics = _collect_live_metrics(conn)
        data_hygiene = _collect_data_hygiene(conn)
        scheduler_health = _collect_scheduler_health(conn)
    finally:
        conn.close()

    latest_report = _collect_latest_report()

    verdict, reasons = _compute_verdict(
        strategy_state, live_metrics, latest_report, data_hygiene, scheduler_health
    )

    return {
        "checked_at": datetime.now().isoformat(timespec="seconds"),
        "strategy_state": strategy_state,
        "live_metrics": live_metrics,
        "latest_report": latest_report,
        "data_hygiene": data_hygiene,
        "scheduler_health": scheduler_health,
        "observation_verdict": verdict,
        "verdict_reasons": reasons,
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="H6 Production Observation Check",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--json", action="store_true", dest="output_json",
        help="Output machine-readable JSON",
    )
    args = parser.parse_args()

    try:
        result = run_check()
    except FileNotFoundError as exc:
        msg = {"error": str(exc), "observation_verdict": "ACTION_REQUIRED"}
        if args.output_json:
            print(json.dumps(msg, ensure_ascii=False, indent=2))
        else:
            print(f"ERROR: {exc}")
        sys.exit(2)

    if args.output_json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        _print_human(result)

    sys.exit(_exit_code(result["observation_verdict"]))


if __name__ == "__main__":
    main()
