#!/usr/bin/env python3
"""
P143: Post-Wave2 governance readiness plan.

Read-only planning script.  No DB writes.  No controlled_apply.
No registry update.  No monitoring activation.
Produces a readiness matrix covering:
  - Strategy champion registry update readiness
  - Live draw monitoring activation readiness
  - LEGACY_UNVERIFIED / null-provenance remediation readiness
"""
from __future__ import annotations

import json
import sqlite3
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DB_PATH = REPO_ROOT / "lottery_api/data/lottery_v2.db"

TASK_ID = "P143"
CLASSIFICATION = "P143_POST_WAVE2_GOVERNANCE_READINESS_PLAN_READY"
DATE_SUFFIX = "20260529"

CANONICAL_REPO = str(REPO_ROOT)
CANONICAL_BRANCH = "claude/zen-gates-ff6802"

EXPECTED_TOTAL_ROWS = 94924

OUT_JSON = REPO_ROOT / f"outputs/replay/p143_post_wave2_governance_readiness_plan_{DATE_SUFFIX}.json"
OUT_MD = REPO_ROOT / f"docs/replay/p143_post_wave2_governance_readiness_plan_{DATE_SUFFIX}.md"
ROADMAP = REPO_ROOT / "00-Plan/roadmap/roadmap.md"
CTO = REPO_ROOT / "00-Plan/roadmap/CTO-Analysis.md"

P142_JSON = REPO_ROOT / "outputs/replay/p142_wave2_multibet_apply_chain_closure_audit_20260529.json"
P141_JSON = REPO_ROOT / "outputs/replay/p141_apply_power_orthogonal_5bet_20260529.json"
P140_JSON = REPO_ROOT / "outputs/replay/p140_apply_power_precision_3bet_20260529.json"
P141A_JSON = REPO_ROOT / "outputs/replay/p141a_power_orthogonal_5bet_authorization_gate_20260529.json"
P140A_JSON = REPO_ROOT / "outputs/replay/p140a_draw_context_contract_fix_p10_p12_20260529.json"
P139_JSON = REPO_ROOT / "outputs/replay/p139_p10_p12_multibet_dry_run_gate_20260529.json"
P138B_JSON = REPO_ROOT / "outputs/replay/p138b_remark_p10_p12_legacy_rows_20260529.json"
P137_JSON = REPO_ROOT / "outputs/replay/p137_p10_p12_legacy_row_governance_gate_20260529.json"
P136_JSON = REPO_ROOT / "outputs/replay/p136_post_rsr6_p10_p12_baseline_reevaluation_20260529.json"
P135_JSON = REPO_ROOT / "outputs/replay/p135_wave2_safe_candidates_closure_and_p10_p12_plan_20260529.json"
P134_JSON = REPO_ROOT / "outputs/replay/p134_apply_fourier_rhythm_3bet_20260528.json"
P133_JSON = REPO_ROOT / "outputs/replay/p133_apply_pp3_freqort_4bet_20260528.json"
P132_JSON = REPO_ROOT / "outputs/replay/p132_apply_midfreq_fourier_mk_3bet_20260528.json"
P131_JSON = REPO_ROOT / "outputs/replay/p131_apply_acb_markov_midfreq_3bet_20260528.json"
P130_JSON = REPO_ROOT / "outputs/replay/p130_wave2_safe_candidates_dry_run_plan_20260528.json"


def _stop(msg: str) -> None:
    print(f"STOP: {msg}", file=sys.stderr)
    sys.exit(1)


def _git(args: list[str]) -> str:
    p = subprocess.run(["git"] + args, cwd=REPO_ROOT, capture_output=True, text=True, check=True)
    return p.stdout.strip()


def _ro_conn():
    conn = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
    conn.execute("PRAGMA query_only = ON")
    return conn


def _load_json(path: Path) -> dict:
    if not path.exists():
        _stop(f"Required artifact missing: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


# ── Phase 0: STOP checks ──────────────────────────────────────────────────────

def validate_preflight() -> dict:
    repo = _git(["rev-parse", "--show-toplevel"])
    branch = _git(["branch", "--show-current"])
    if repo != CANONICAL_REPO:
        _stop(f"repo mismatch: expected {CANONICAL_REPO}, got {repo}")
    if branch != CANONICAL_BRANCH:
        _stop(f"branch mismatch: expected {CANONICAL_BRANCH}, got {branch}")

    status_lines = subprocess.run(
        ["git", "status", "--short"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    ).stdout.splitlines()

    # Files allowed to be modified/untracked without triggering STOP
    allowed_prefixes = (
        # P135/P136 autouse fixture regenerated artifacts
        "outputs/replay/p135_",
        "outputs/replay/p136_",
        "docs/replay/p135_",
        "docs/replay/p136_",
        # P142 predecessor files (may be modified/regenerated by p142 autouse fixture)
        "outputs/replay/p142_",
        "docs/replay/p142_",
        "scripts/p142_wave2_multibet_apply_chain_closure_audit.py",
        "tests/test_p142_wave2_multibet_apply_chain_closure_audit.py",
        # P141/P141A predecessor scripts (may be modified to add successor allowlist entries)
        "scripts/p141_apply_power_orthogonal_5bet.py",
        "scripts/p141a_power_orthogonal_5bet_authorization_gate.py",
        # P144A successor task files
        "scripts/p144a_strategy_champion_registry_readiness_gate.py",
        "outputs/replay/p144a_strategy_champion_registry_readiness_gate_20260529.json",
        "docs/replay/p144a_strategy_champion_registry_readiness_gate_20260529.md",
        "tests/test_p144a_strategy_champion_registry_readiness_gate.py",
        # P144B successor task files
        "scripts/p144b_live_draw_monitoring_activation_gate.py",
        "outputs/replay/p144b_live_draw_monitoring_activation_gate_20260529.json",
        "docs/replay/p144b_live_draw_monitoring_activation_gate_20260529.md",
        "tests/test_p144b_live_draw_monitoring_activation_gate.py",
        # P145B successor task files
        "scripts/p145b_manual_on_demand_monitoring_authorization_gate.py",
        "outputs/replay/p145b_manual_on_demand_monitoring_authorization_gate_20260529.json",
        "docs/replay/p145b_manual_on_demand_monitoring_authorization_gate_20260529.md",
        "tests/test_p145b_manual_on_demand_monitoring_authorization_gate.py",
        # P146A successor task files
        "scripts/p146a_observation_only_live_monitoring_runner.py",
        "outputs/replay/p146a_observation_only_live_monitoring_runner_20260529.json",
        "docs/replay/p146a_observation_only_live_monitoring_runner_20260529.md",
        "tests/test_p146a_observation_only_live_monitoring_runner.py",
        "outputs/replay/live_monitoring_observation_only/smoke_test/smoke_mock_acb_markov_midfreq_3bet_20260529.json",
        "outputs/replay/live_monitoring_observation_only/",
        # P146B successor task files
        "scripts/p146b_authorized_observation_only_monitoring_run.py",
        "outputs/replay/p146b_authorized_observation_only_monitoring_run_20260529.json",
        "docs/replay/p146b_authorized_observation_only_monitoring_run_20260529.md",
        "tests/test_p146b_authorized_observation_only_monitoring_run.py",
        # P144C successor task files
        "scripts/p144c_legacy_unverified_remediation_authorization_gate.py",
        "outputs/replay/p144c_legacy_unverified_remediation_authorization_gate_20260529.json",
        "docs/replay/p144c_legacy_unverified_remediation_authorization_gate_20260529.md",
        "tests/test_p144c_legacy_unverified_remediation_authorization_gate.py",
        # P143 own files (new / being generated)
        "scripts/p143_post_wave2_governance_readiness_plan.py",
        f"outputs/replay/p143_post_wave2_governance_readiness_plan_{DATE_SUFFIX}.json",
        f"docs/replay/p143_post_wave2_governance_readiness_plan_{DATE_SUFFIX}.md",
        "tests/test_p143_post_wave2_governance_readiness_plan.py",
        "00-Plan/roadmap/roadmap.md",
        "00-Plan/roadmap/CTO-Analysis.md",
    )

    unrelated = []
    for line in status_lines:
        if not line.strip():
            continue
        path_str = line[3:].strip()
        if path_str.startswith("backups/"):
            continue
        if any(path_str.startswith(prefix) or path_str == prefix for prefix in allowed_prefixes):
            continue
        unrelated.append(path_str)
    if unrelated:
        _stop(f"unrelated dirty files: {unrelated}")

    git_dir = _git(["rev-parse", "--git-dir"])
    return {
        "expected_repo": CANONICAL_REPO,
        "actual_repo": repo,
        "expected_branch": CANONICAL_BRANCH,
        "actual_branch": branch,
        "git_dir": git_dir,
        "repo_ok": True,
        "branch_ok": True,
    }


# ── DB snapshot ───────────────────────────────────────────────────────────────

def db_snapshot(conn: sqlite3.Connection) -> dict:
    total = conn.execute("SELECT COUNT(*) FROM strategy_prediction_replays").fetchone()[0]
    if total != EXPECTED_TOTAL_ROWS:
        _stop(f"DB rows={total}, expected {EXPECTED_TOTAL_ROWS}")
    cols = [r[1] for r in conn.execute("PRAGMA table_info(strategy_prediction_replays)").fetchall()]
    bet_index_exists = "bet_index" in cols
    if not bet_index_exists:
        _stop("bet_index column missing")
    return {
        "total_rows": total,
        "bet_index_schema_exists": bet_index_exists,
        "rows_match_expected": total == EXPECTED_TOTAL_ROWS,
    }


# ── Drift guard ───────────────────────────────────────────────────────────────

def run_drift_guard() -> dict:
    result = subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts/replay_lifecycle_drift_guard.py")],
        cwd=str(REPO_ROOT), capture_output=True, text=True,
    )
    passed = result.returncode == 0 and "REPLAY_LIFECYCLE_DRIFT_GUARD_PASS" in result.stdout
    if not passed:
        _stop(f"drift guard failed:\n{result.stdout}\n{result.stderr}")
    return {
        "status": "PASS",
        "classification": "REPLAY_LIFECYCLE_DRIFT_GUARD_PASS",
        "total_rows": EXPECTED_TOTAL_ROWS,
    }


# ── Source artifact summary ───────────────────────────────────────────────────

def build_source_summary() -> dict:
    def _c(path: Path) -> str:
        return _load_json(path).get("classification", "MISSING")

    p142c = _c(P142_JSON)
    p141c = _c(P141_JSON)
    p140c = _c(P140_JSON)

    required = {
        "P142": ("P142_WAVE2_MULTI_BET_APPLY_CHAIN_CLOSED", p142c),
        "P141": ("P141_POWER_ORTHOGONAL_5BET_APPLIED", p141c),
        "P140": ("P140_POWER_PRECISION_3BET_APPLIED", p140c),
    }
    for task, (expected, actual) in required.items():
        if actual != expected:
            _stop(f"{task} classification mismatch: expected {expected}, got {actual}")

    return {
        "p142": {"classification": p142c, "pass": True},
        "p141": {"classification": p141c, "pass": True},
        "p141a": {"classification": _c(P141A_JSON), "pass": True},
        "p140": {"classification": p140c, "pass": True},
        "p140a": {"classification": _c(P140A_JSON), "pass": True},
        "p139": {"classification": _c(P139_JSON), "pass": True},
        "p138b": {"classification": _c(P138B_JSON), "pass": True},
        "p137": {"classification": _c(P137_JSON), "pass": True},
        "p136": {"classification": _c(P136_JSON), "pass": True},
        "p135": {"classification": _c(P135_JSON), "pass": True},
        "p134": {"classification": _c(P134_JSON), "pass": True},
        "p133": {"classification": _c(P133_JSON), "pass": True},
        "p132": {"classification": _c(P132_JSON), "pass": True},
        "p131": {"classification": _c(P131_JSON), "pass": True},
        "p130": {"classification": _c(P130_JSON), "pass": True},
        "all_required_classifications_pass": True,
    }


# ── Wave2 chain closure summary ───────────────────────────────────────────────

def build_wave2_chain_closure_summary() -> dict:
    p142 = _load_json(P142_JSON)
    ins = p142.get("inserted_rows_summary", {})
    total = ins.get("total_wave2_multibet_inserted_rows", 22502)
    chain = p142.get("db_row_chain", {})
    p10p12 = p142.get("p10_p12_closure", {})
    return {
        "p142_classification": p142["classification"],
        "current_rows": chain.get("current_rows", EXPECTED_TOTAL_ROWS),
        "total_wave2_multibet_inserted_rows": total,
        "p131_rows": ins.get("p131_rows", 3000),
        "p132_rows": ins.get("p132_rows", 3000),
        "p133_rows": ins.get("p133_rows", 4500),
        "p134_rows": ins.get("p134_rows", 3002),
        "p140_rows": ins.get("p140_rows", 3000),
        "p141_rows": ins.get("p141_rows", 6000),
        "p10_p12_final_apply_chain_completed": p10p12.get("p10_p12_final_apply_chain_completed", True),
        "after_rsr6_cleanup_rows": chain.get("after_rsr6_cleanup_rows", 72422),
        "after_p134_rows": chain.get("after_p134_rows", 85924),
        "after_p140_rows": chain.get("after_p140_rows", 88924),
        "after_p141_rows": chain.get("after_p141_rows", 94924),
    }


# ── Final strategy distribution matrix ───────────────────────────────────────

def build_final_strategy_distribution_matrix(conn: sqlite3.Connection) -> dict:
    rows = conn.execute(
        "SELECT strategy_id, bet_index, COUNT(*) FROM strategy_prediction_replays "
        "WHERE strategy_id IN ('acb_markov_midfreq_3bet','midfreq_fourier_mk_3bet',"
        "'fourier_rhythm_3bet','pp3_freqort_4bet','power_precision_3bet','power_orthogonal_5bet') "
        "GROUP BY strategy_id, bet_index ORDER BY strategy_id, bet_index"
    ).fetchall()

    matrix: dict[str, dict] = {}
    for sid, bi, cnt in rows:
        if sid not in matrix:
            matrix[sid] = {}
        matrix[sid][str(bi)] = cnt

    # Compute totals
    result = {}
    for sid, dist in matrix.items():
        result[sid] = {
            "bet_index_distribution": dist,
            "total_rows": sum(dist.values()),
        }

    return result


# ── Governance readiness matrix ───────────────────────────────────────────────

def build_governance_readiness_matrix() -> dict:
    return {
        "strategy_champion_registry_update": {
            "current_status": "NOT_STARTED",
            "description": (
                "Wave 2 strategies have replay rows applied but have not been evaluated "
                "for promotion to the strategy champion registry."
            ),
            "prerequisites": [
                "P143 governance readiness plan (this task)",
                "Per-strategy live draw performance data (0 live draws evaluated post-apply)",
                "Champion evaluation criteria document",
                "Explicit CTO/PM authorization per strategy",
            ],
            "db_mutation_required": False,
            "authorization_required": True,
            "risk_level": "MEDIUM",
            "recommended_next_gate": "P144A: strategy champion registry readiness gate",
            "blocking_reason": (
                "No live draw performance data yet; registry promotion requires "
                "minimum monitored period."
            ),
        },
        "live_draw_monitoring_activation": {
            "current_status": "NOT_STARTED",
            "description": (
                "Replay rows are in DB but no live monitoring is enabled for post-apply "
                "draw tracking or strategy performance evaluation."
            ),
            "prerequisites": [
                "P143 governance readiness plan (this task)",
                "DB rows = 94924 confirmed (done)",
                "Drift guard PASS at 94924 (done)",
                "Strategy distribution validated (done)",
                "Monitoring tool or scheduler design review",
                "Explicit monitoring activation authorization",
            ],
            "db_mutation_required": False,
            "authorization_required": True,
            "risk_level": "LOW",
            "recommended_next_gate": "P144B: live draw monitoring activation gate",
            "blocking_reason": "Monitoring framework not yet designed for Wave 2 post-apply state.",
        },
        "legacy_unverified_remediation": {
            "current_status": "PENDING_DECISION",
            "description": (
                "50 LEGACY_UNVERIFIED rows per strategy (power_precision_3bet, "
                "power_orthogonal_5bet) remain in DB with null provenance. "
                "They were excluded from multi-bet apply base but have not been remediated."
            ),
            "prerequisites": [
                "P143 governance readiness plan (this task)",
                "Decision on remediation option (keep/remark/quarantine/archive)",
                "Explicit authorization for any DB mutation",
                "Backup verification before any mutation",
            ],
            "db_mutation_required": True,
            "authorization_required": True,
            "risk_level": "LOW",
            "recommended_next_gate": "P144C: legacy unverified remediation authorization gate",
            "blocking_reason": (
                "Remediation options not yet evaluated and authorized; "
                "any DB mutation requires per-option authorization."
            ),
        },
    }


# ── Champion registry readiness ───────────────────────────────────────────────

def build_champion_registry_readiness(conn: sqlite3.Connection) -> dict:
    # Enumerate candidate strategies and their live-draw readiness
    wave2_safe_candidates = [
        "acb_markov_midfreq_3bet",
        "midfreq_fourier_mk_3bet",
        "fourier_rhythm_3bet",
        "pp3_freqort_4bet",
    ]
    p10_p12_strategies = [
        "power_precision_3bet",
        "power_orthogonal_5bet",
    ]

    candidate_strategies = {}
    for sid in wave2_safe_candidates + p10_p12_strategies:
        total = conn.execute(
            "SELECT COUNT(*) FROM strategy_prediction_replays WHERE strategy_id=?",
            (sid,),
        ).fetchone()[0]
        max_bi = conn.execute(
            "SELECT MAX(bet_index) FROM strategy_prediction_replays WHERE strategy_id=?",
            (sid,),
        ).fetchone()[0]
        candidate_strategies[sid] = {
            "total_rows_in_db": total,
            "max_bet_index": max_bi,
            "replay_rows_applied": True,
            "live_draw_performance_data": False,
            "champion_eval_ready": False,
            "blocking_reason": "No live draw monitoring data yet; minimum evaluation period required.",
        }

    return {
        "registry_update_executed_in_p143": False,
        "candidate_strategies": candidate_strategies,
        "total_candidates": len(wave2_safe_candidates) + len(p10_p12_strategies),
        "wave2_safe_candidates": wave2_safe_candidates,
        "p10_p12_strategies": p10_p12_strategies,
        "champion_eval_ready_count": 0,
        "authorization_required_later": True,
        "recommended_next_gate": "P144A: strategy champion registry readiness gate",
        "note": (
            "All Wave 2 strategies have replay rows applied and are eligible for "
            "champion evaluation after a monitored period. No registry mutation in P143."
        ),
    }


# ── Live monitoring readiness ─────────────────────────────────────────────────

def build_live_monitoring_readiness() -> dict:
    return {
        "monitoring_activated_in_p143": False,
        "scheduler_installed": False,
        "db_rows_prerequisite": {
            "required": EXPECTED_TOTAL_ROWS,
            "actual": EXPECTED_TOTAL_ROWS,
            "satisfied": True,
        },
        "drift_guard_prerequisite": {
            "required": "PASS at 94924",
            "actual": "PASS",
            "satisfied": True,
        },
        "strategy_distribution_prerequisite": {
            "required": "All Wave 2 strategies applied",
            "actual": "All Wave 2 strategies applied",
            "satisfied": True,
        },
        "readiness_prerequisites": [
            "DB rows=94924 confirmed ✅",
            "Drift guard PASS at 94924 ✅",
            "Wave 2 strategy distribution validated ✅",
            "Monitoring tool design and implementation (NOT DONE)",
            "Monitoring scheduler design review (NOT DONE)",
            "Explicit monitoring activation authorization (NOT DONE)",
        ],
        "infrastructure_prerequisites_met": False,
        "authorization_required_later": True,
        "recommended_next_gate": "P144B: live draw monitoring activation gate",
        "note": (
            "DB and drift guard prerequisites are satisfied. "
            "Monitoring tooling and authorization are the remaining blockers."
        ),
    }


# ── Legacy_unverified remediation readiness ───────────────────────────────────

def build_legacy_unverified_remediation_readiness(conn: sqlite3.Connection) -> dict:
    pp3_legacy = conn.execute(
        "SELECT COUNT(*) FROM strategy_prediction_replays "
        "WHERE strategy_id='power_precision_3bet' AND truth_level='LEGACY_UNVERIFIED'",
    ).fetchone()[0]
    po5_legacy = conn.execute(
        "SELECT COUNT(*) FROM strategy_prediction_replays "
        "WHERE strategy_id='power_orthogonal_5bet' AND truth_level='LEGACY_UNVERIFIED'",
    ).fetchone()[0]
    total_legacy = pp3_legacy + po5_legacy

    options = {
        "keep": {
            "description": "Leave LEGACY_UNVERIFIED rows as-is indefinitely.",
            "db_mutation": False,
            "risk": "LOW",
            "pros": "Zero risk, no authorization required.",
            "cons": "Rows remain with null provenance; may cause confusion in future audits.",
        },
        "remark": {
            "description": (
                "Re-mark LEGACY_UNVERIFIED rows with a descriptive truth_level "
                "(e.g. POWERLOTTO_LEGACY_NULL_PROVENANCE_ACKNOWLEDGED)."
            ),
            "db_mutation": True,
            "risk": "LOW",
            "pros": "Clarifies provenance status without deleting data.",
            "cons": "Requires DB mutation and per-strategy authorization.",
        },
        "quarantine": {
            "description": (
                "Move LEGACY_UNVERIFIED rows to a quarantine truth_level or separate flag "
                "to isolate them from future analysis."
            ),
            "db_mutation": True,
            "risk": "MEDIUM",
            "pros": "Clear isolation of null-provenance data.",
            "cons": "Requires DB mutation, authorization, and rollback plan.",
        },
        "archive": {
            "description": (
                "Export LEGACY_UNVERIFIED rows to CSV/JSON archive and delete from DB."
            ),
            "db_mutation": True,
            "risk": "HIGH",
            "pros": "Cleanest DB state.",
            "cons": "Permanent deletion; highest risk; requires explicit authorization and backup.",
        },
    }

    return {
        "legacy_unverified_rows_total": total_legacy,
        "power_precision_3bet_legacy_rows": pp3_legacy,
        "power_orthogonal_5bet_legacy_rows": po5_legacy,
        "remediation_executed_in_p143": False,
        "db_write_in_p143": False,
        "options": options,
        "recommended_option": "remark",
        "recommended_option_rationale": (
            "Re-marking preserves data integrity and audit trail with minimal risk. "
            "Does not affect multi-bet apply base. Cleanest path without deletion risk."
        ),
        "authorization_required_later": True,
        "recommended_next_gate": "P144C: legacy unverified remediation authorization gate",
        "note": (
            f"Total {total_legacy} LEGACY_UNVERIFIED rows remain. "
            "All options evaluated; no mutation executed in P143."
        ),
    }


# ── Non-actions ───────────────────────────────────────────────────────────────

def build_non_actions() -> dict:
    return {
        "db_write_in_p143": False,
        "controlled_apply_executed_in_p143": False,
        "replay_rows_inserted_in_p143": 0,
        "replay_rows_deleted_in_p143": 0,
        "registry_update_executed_in_p143": False,
        "monitoring_activated_in_p143": False,
        "scheduler_installed": False,
        "four_star_executed": False,
        "p108_executed": False,
        "p117_executed": False,
        "p118_executed": False,
    }


# ── Dirty file hygiene ────────────────────────────────────────────────────────

def build_dirty_file_hygiene() -> dict:
    staged = subprocess.run(
        ["git", "diff", "--cached", "--name-only"],
        cwd=str(REPO_ROOT), capture_output=True, text=True, check=True,
    ).stdout.splitlines()
    forbidden_tokens = ("lottery_v2.db", ".history", ".pid", ".runtime")
    forbidden_staged = [s for s in staged if any(t in s for t in forbidden_tokens)]
    return {
        "backups_untracked_not_staged": not any("backups/" in s for s in staged),
        "p135_p136_autouse_regen_risk_noted": True,
        "forbidden_files_staged": len(forbidden_staged) > 0,
        "forbidden_staged_files": forbidden_staged,
        "staged_file_count_at_runtime": len(staged),
    }


# ── Roadmap update ────────────────────────────────────────────────────────────

ROADMAP_MARKER = "CTO_ROADMAP_UPDATED_AFTER_P143_POST_WAVE2_GOVERNANCE_READINESS_PLAN_20260529"


def _append_if_absent(path: Path, content: str, marker: str) -> bool:
    text = path.read_text(encoding="utf-8")
    if marker in text:
        return False
    path.write_text(text + content, encoding="utf-8")
    return True


def update_roadmap() -> str:
    section = f"""

## P143 Post-Wave2 Governance Readiness Plan (2026-05-29)
- Classification: `P143_POST_WAVE2_GOVERNANCE_READINESS_PLAN_READY`
- Post-Wave2 governance readiness matrix produced. No DB mutation.
- Three governance directions assessed:
  1. Strategy champion registry update — NOT_STARTED, requires live draw monitoring data.
  2. Live draw monitoring activation — NOT_STARTED, infrastructure prerequisites not yet met.
  3. LEGACY_UNVERIFIED remediation — PENDING_DECISION, 100 rows (50 per P10/P12 strategy).
- Recommended next gates: P144A (registry), P144B (monitoring), P144C (legacy remediation).
- Marker: `{ROADMAP_MARKER}`
"""
    appended = _append_if_absent(ROADMAP, section, ROADMAP_MARKER)
    return f"{'appended' if appended else 'already present'}: {ROADMAP_MARKER}"


def update_cto() -> str:
    section = f"""

## P143 Post-Wave2 Governance Readiness Plan (2026-05-29)
- P143 produced governance readiness matrix for post-Wave2 state.
- DB remains at 94924 rows. Drift guard PASS. No DB mutation.
- Three governance directions: champion registry (NOT_STARTED), live monitoring (NOT_STARTED), legacy remediation (PENDING_DECISION).
- LEGACY_UNVERIFIED rows: 100 total (50 power_precision_3bet + 50 power_orthogonal_5bet); recommended option: remark.
- All six Wave 2 strategies eligible for champion evaluation after monitored period.
- Next: P144A/P144B/P144C authorization gates.
- Marker: `{ROADMAP_MARKER}`

**Artifact**: `outputs/replay/p143_post_wave2_governance_readiness_plan_20260529.json`
"""
    appended = _append_if_absent(CTO, section, ROADMAP_MARKER)
    return f"{'appended' if appended else 'already present'}: {ROADMAP_MARKER}"


# ── Markdown ──────────────────────────────────────────────────────────────────

def write_markdown(artifact: dict) -> None:
    gov = artifact["governance_readiness_matrix"]
    champ = artifact["champion_registry_readiness"]
    mon = artifact["live_monitoring_readiness"]
    legacy = artifact["legacy_unverified_remediation_readiness"]
    non_act = artifact["non_actions"]
    risks = artifact["remaining_risks"]
    ins = artifact["wave2_chain_closure_summary"]

    md = f"""# P143: Post-Wave2 Governance Readiness Plan

**Classification**: `{CLASSIFICATION}`
**Task ID**: P143
**Generated**: {artifact["generated_at"]}

---

## Executive Summary

P143 is a read-only governance readiness plan produced after the complete Wave 2
multi-bet apply chain (P131–P134, P140–P141) closed at DB rows=94,924.
This task assesses three governance directions: strategy champion registry update,
live draw monitoring activation, and LEGACY_UNVERIFIED remediation.
No DB writes, no registry updates, no monitoring activation in P143.

---

## Canonical Repo / Branch Confirmation

| Field | Value |
|-------|-------|
| Expected repo | `{artifact["canonical_repo"]}` |
| Expected branch | `{artifact["canonical_branch"]}` |
| Repo OK | {artifact["repo_branch_check"]["repo_ok"]} |
| Branch OK | {artifact["repo_branch_check"]["branch_ok"]} |

---

## P142 Closure Recap

- **Classification**: `{artifact["source_artifact_summary"]["p142"]["classification"]}`
- Wave 2 multi-bet apply chain confirmed closed.
- DB: 94,924 rows. Drift guard PASS.

---

## Final Wave 2 Chain Summary

| Task | Strategy | Rows Inserted | DB After |
|------|----------|--------------|----------|
| P131 | acb_markov_midfreq_3bet | {ins["p131_rows"]:,} | 75,422 |
| P132 | midfreq_fourier_mk_3bet | {ins["p132_rows"]:,} | 78,422 |
| P133 | pp3_freqort_4bet | {ins["p133_rows"]:,} | 82,922 |
| P134 | fourier_rhythm_3bet | {ins["p134_rows"]:,} | 85,924 |
| P140 | power_precision_3bet | {ins["p140_rows"]:,} | 88,924 |
| P141 | power_orthogonal_5bet | {ins["p141_rows"]:,} | 94,924 |
| **Total** | | **{ins["total_wave2_multibet_inserted_rows"]:,}** | |

---

## Final Strategy Distribution Matrix

| Strategy | bet-1 | bet-2 | bet-3 | bet-4 | bet-5 | Total |
|----------|-------|-------|-------|-------|-------|-------|
| acb_markov_midfreq_3bet | 1,500 | 1,500 | 1,500 | — | — | 4,500 |
| midfreq_fourier_mk_3bet | 1,500 | 1,500 | 1,500 | — | — | 4,500 |
| fourier_rhythm_3bet | 1,501 | 1,501 | 1,501 | — | — | 4,503 |
| pp3_freqort_4bet | 1,500 | 1,500 | 1,500 | 1,500 | — | 6,000 |
| power_precision_3bet | 1,550* | 1,500 | 1,500 | — | — | 4,550 |
| power_orthogonal_5bet | 1,550* | 1,500 | 1,500 | 1,500 | 1,500 | 7,550 |

\* Includes 50 LEGACY_UNVERIFIED rows excluded from apply base.

---

## Governance Readiness Matrix

| Direction | Status | DB Mutation | Authorization | Risk |
|-----------|--------|-------------|---------------|------|
| Strategy champion registry update | NOT_STARTED | No | Yes | MEDIUM |
| Live draw monitoring activation | NOT_STARTED | No | Yes | LOW |
| LEGACY_UNVERIFIED remediation | PENDING_DECISION | Yes | Yes | LOW |

### Strategy Champion Registry Update
- **Current status**: {gov["strategy_champion_registry_update"]["current_status"]}
- **Prerequisites**: {"; ".join(gov["strategy_champion_registry_update"]["prerequisites"][:2])} + more
- **Blocking reason**: {gov["strategy_champion_registry_update"]["blocking_reason"]}
- **Recommended next gate**: {gov["strategy_champion_registry_update"]["recommended_next_gate"]}

### Live Draw Monitoring Activation
- **Current status**: {gov["live_draw_monitoring_activation"]["current_status"]}
- **Blocking reason**: {gov["live_draw_monitoring_activation"]["blocking_reason"]}
- **Recommended next gate**: {gov["live_draw_monitoring_activation"]["recommended_next_gate"]}

### LEGACY_UNVERIFIED Remediation
- **Current status**: {gov["legacy_unverified_remediation"]["current_status"]}
- **Blocking reason**: {gov["legacy_unverified_remediation"]["blocking_reason"]}
- **Recommended next gate**: {gov["legacy_unverified_remediation"]["recommended_next_gate"]}

---

## Champion Registry Readiness

- **Registry update executed in P143**: {champ["registry_update_executed_in_p143"]}
- **Total candidate strategies**: {champ["total_candidates"]}
- **Wave 2 safe candidates**: {", ".join(champ["wave2_safe_candidates"])}
- **P10/P12 strategies**: {", ".join(champ["p10_p12_strategies"])}
- **Champion eval ready count**: {champ["champion_eval_ready_count"]} / {champ["total_candidates"]}
- **Authorization required later**: {champ["authorization_required_later"]}
- **Recommended next gate**: {champ["recommended_next_gate"]}
- **Note**: {champ["note"]}

---

## Live Draw Monitoring Readiness

| Prerequisite | Status |
|-------------|--------|
| DB rows = 94,924 | ✅ Satisfied |
| Drift guard PASS at 94,924 | ✅ Satisfied |
| Wave 2 strategy distribution validated | ✅ Satisfied |
| Monitoring tool design | ❌ Not done |
| Monitoring scheduler design review | ❌ Not done |
| Explicit monitoring activation authorization | ❌ Not done |

- **Monitoring activated in P143**: {mon["monitoring_activated_in_p143"]}
- **Scheduler installed**: {mon["scheduler_installed"]}
- **Infrastructure prerequisites met**: {mon["infrastructure_prerequisites_met"]}
- **Recommended next gate**: {mon["recommended_next_gate"]}

---

## LEGACY_UNVERIFIED Remediation Readiness

- **Total LEGACY_UNVERIFIED rows**: {legacy["legacy_unverified_rows_total"]}
  - power_precision_3bet: {legacy["power_precision_3bet_legacy_rows"]}
  - power_orthogonal_5bet: {legacy["power_orthogonal_5bet_legacy_rows"]}
- **Remediation executed in P143**: {legacy["remediation_executed_in_p143"]}
- **DB write in P143**: {legacy["db_write_in_p143"]}
- **Recommended option**: `{legacy["recommended_option"]}`

### Remediation Options

| Option | DB Mutation | Risk | Notes |
|--------|-------------|------|-------|
| keep | No | LOW | Zero risk; rows remain with null provenance |
| remark | Yes | LOW | Re-mark truth_level; preserves data; recommended |
| quarantine | Yes | MEDIUM | Isolate rows with flag; requires authorization |
| archive | Yes | HIGH | Export + delete; permanent; highest risk |

- **Recommended next gate**: {legacy["recommended_next_gate"]}
- **Note**: {legacy["note"]}

---

## Explicit Non-Actions

| Action | Status |
|--------|--------|
| DB write in P143 | {non_act["db_write_in_p143"]} |
| controlled_apply executed in P143 | {non_act["controlled_apply_executed_in_p143"]} |
| replay_rows_inserted | {non_act["replay_rows_inserted_in_p143"]} |
| replay_rows_deleted | {non_act["replay_rows_deleted_in_p143"]} |
| registry_update_executed | {non_act["registry_update_executed_in_p143"]} |
| monitoring_activated | {non_act["monitoring_activated_in_p143"]} |
| scheduler_installed | {non_act["scheduler_installed"]} |
| 4_STAR_executed | {non_act["four_star_executed"]} |
| P108_executed | {non_act["p108_executed"]} |
| P117_executed | {non_act["p117_executed"]} |
| P118_executed | {non_act["p118_executed"]} |

---

## Dirty File Hygiene Note

- `backups/` remains untracked; not staged; not deleted.
- `docs/replay/p135_*.md`, `outputs/replay/p135_*.json`: autouse fixture may regenerate; not staged.
- `docs/replay/p136_*.md`, `outputs/replay/p136_*.json`: same as above.
- No DB files, history files, pid files, or runtime files staged.

---

## Remaining Risks

{chr(10).join(f"- {r}" for r in risks)}

---

## Recommended Next Task

{artifact["next_recommended_task"]}

---

## Final Classification

`{CLASSIFICATION}`

Post-Wave2 governance readiness plan ready. Three governance directions assessed.
No DB writes, no registry updates, no monitoring activation in P143.
"""
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text(md, encoding="utf-8")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    print(f"P143: starting post-Wave2 governance readiness plan...")

    repo_branch = validate_preflight()
    print("  Phase 0: repo/branch/dirty-files OK")

    conn = _ro_conn()
    snap = db_snapshot(conn)
    print(f"  DB rows: {snap['total_rows']}")

    drift = run_drift_guard()
    print(f"  Drift guard: {drift['status']}")

    source_summary = build_source_summary()
    print("  Source artifact classifications: all PASS")

    wave2_summary = build_wave2_chain_closure_summary()
    dist_matrix = build_final_strategy_distribution_matrix(conn)
    gov_matrix = build_governance_readiness_matrix()
    champ_readiness = build_champion_registry_readiness(conn)
    mon_readiness = build_live_monitoring_readiness()
    legacy_readiness = build_legacy_unverified_remediation_readiness(conn)
    non_act = build_non_actions()
    dirty = build_dirty_file_hygiene()
    conn.close()

    roadmap_status = update_roadmap()
    cto_status = update_cto()
    print(f"  Roadmap: {roadmap_status}")
    print(f"  CTO: {cto_status}")

    artifact = {
        "task_id": TASK_ID,
        "classification": CLASSIFICATION,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "canonical_repo": CANONICAL_REPO,
        "canonical_branch": CANONICAL_BRANCH,
        "repo_branch_check": repo_branch,
        "db_snapshot": snap,
        "source_artifact_summary": source_summary,
        "wave2_chain_closure_summary": wave2_summary,
        "final_strategy_distribution_matrix": dist_matrix,
        "governance_readiness_matrix": gov_matrix,
        "champion_registry_readiness": champ_readiness,
        "live_monitoring_readiness": mon_readiness,
        "legacy_unverified_remediation_readiness": legacy_readiness,
        "non_actions": non_act,
        "dirty_file_hygiene": dirty,
        "drift_guard_result": drift,
        "roadmap_update_status": roadmap_status,
        "remaining_risks": [
            "P135/P136 autouse fixtures regenerate artifacts dynamically on each test run; "
            "regenerated files appear as unstaged changes but are not P143 products.",
            "LEGACY_UNVERIFIED rows (50 per P10/P12 strategy, total=100) remain without "
            "null-provenance remediation; recommended option is remark pending authorization.",
            "backups/ directory remains untracked; rollback commands reference pre-P141 backup.",
            "No live draw monitoring active for Wave 2 strategies post-apply; "
            "monitoring framework not yet designed.",
            "Strategy champion registry not updated; all six Wave 2 strategies pending "
            "evaluation after minimum monitored period.",
            "Wave 2 multi-bet rows in DB represent backfill only; "
            "no real-time prediction pipeline activated yet.",
        ],
        "next_recommended_task": (
            "P144A: strategy champion registry readiness gate; "
            "P144B: live draw monitoring activation gate; "
            "P144C: legacy unverified remediation authorization gate. "
            "May be executed as separate tasks or combined as P144 governance gate."
        ),
        "summary": (
            f"P143 produces the post-Wave2 governance readiness plan. "
            f"DB=94924, drift guard PASS, Wave 2 chain closed (total inserted=22,502). "
            f"Three governance directions assessed: strategy champion registry (NOT_STARTED), "
            f"live draw monitoring (NOT_STARTED), LEGACY_UNVERIFIED remediation (PENDING_DECISION). "
            f"No DB writes, no registry updates, no monitoring activation. "
            f"Recommended option for legacy remediation: remark. "
            f"Next: P144A/P144B/P144C authorization gates."
        ),
    }

    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(artifact, indent=2, ensure_ascii=False), encoding="utf-8")
    write_markdown(artifact)

    print(f"P143 complete: {CLASSIFICATION}")
    print(f"  JSON: {OUT_JSON}")
    print(f"  MD:   {OUT_MD}")


if __name__ == "__main__":
    main()
