"""
P268D-3: H1 confirmatory permutation test for per-ball exit-rank heterogeneity
in the official `drawNumberAppear` (draw-order) field.

Hard constraints (per P268C/P268D1 registry-freeze design and this task's
authorization):
  - This task runs H1 ONLY. H2 and H3 are NOT executed here.
  - Data source is the P268D-1 full-history JSONL artifact
    (`outputs/research/p268d1_draw_order_full_history_artifact_backfill_20260610.jsonl`),
    NOT the local SQLite DB. No DB connection of any kind is opened.
  - Before any H1 computation, this script appends exactly ONE pre-registration
    entry to the production Hypothesis Registry
    (`lottery_api/data/hypothesis_registry.jsonl`), id
    `HR-P268D3-H1-DRAW-ORDER-EXIT-RANK-001`, status `PRE_REGISTERED_BEFORE_TEST`.
  - 2026-04 and 2026-05 are excluded from the eligible draw set (already
    inspected by P268B; excluded from any confirmatory window per P268D1
    registry-freeze).
  - Eligible draws (per lottery_type) are split chronologically 70%
    estimation / 30% holdout. Only the estimation window is used by H1 in
    this task; the holdout window is NOT opened, NOT read, and NOT used for
    any statistic in this task (reserved for H1_holdout in a future task).
  - Null model: within-draw permutation null. For each draw, the `k`
    drawn-ball identities (a fixed-size slice of `drawNumberAppear`) are
    treated as an exchangeable set; under the null, all k! orderings of
    that set are equally likely. The observed test statistic is compared
    against a Monte Carlo null distribution generated by independently
    re-permuting each draw's order labels.
  - Test statistic: dispersion (sum of squared standardized per-ball mean
    exit-rank) across all balls in the relevant pool. "Exit rank" = 1-based
    position of a ball within the (sliced) `drawNumberAppear` sequence.
  - DAILY_539 is the primary game (alpha = 0.01, single pre-registered test,
    no cross-game correction needed for H1 itself per the registry-freeze).
    BIG_LOTTO / POWER_LOTTO / 3_STAR / 4_STAR are computed and reported but
    are explicitly labeled SECONDARY / EXPLORATORY ONLY and cannot alone
    promote to a strategy or change the H1 PASS/FAIL classification.
  - No DB write of any kind. No new strategy. No hit-rate / success-rate
    improvement claim of any kind.
"""

from __future__ import annotations

import json
import time
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = REPO_ROOT / "outputs" / "research"

P268D1_JSONL = OUT_DIR / "p268d1_draw_order_full_history_artifact_backfill_20260610.jsonl"
P268D1_REGISTRY_FREEZE = OUT_DIR / "p268d1_draw_order_registry_freeze_20260610.json"
P268D1_SUMMARY = OUT_DIR / "p268d1_draw_order_full_history_artifact_backfill_20260610.summary.json"
P268D2_JSON = OUT_DIR / "p268d2_draw_order_structure_validation_db_alignment_20260610.json"

OUTPUT_JSON = OUT_DIR / "p268d3_h1_draw_order_confirmatory_permutation_test_20260611.json"
OUTPUT_MD = OUT_DIR / "p268d3_h1_draw_order_confirmatory_permutation_test_20260611.md"

HYPOTHESIS_REGISTRY_PATH = REPO_ROOT / "lottery_api" / "data" / "hypothesis_registry.jsonl"

HYPOTHESIS_ID = "HR-P268D3-H1-DRAW-ORDER-EXIT-RANK-001"

PRIMARY_GAME = "DAILY_539"
SECONDARY_GAMES = ["BIG_LOTTO", "POWER_LOTTO", "3_STAR", "4_STAR"]

# Per-game ball-pool / draw-order configuration for the H1 exit-rank statistic.
#
#   pool_min/pool_max: inclusive range of distinct ball identities considered
#                       for the within-draw permutation (a single namespace).
#   k:                  number of positions in the sliced drawNumberAppear
#                       sequence used for the H1 statistic (the "drawn set").
#   slice_len:          number of leading elements of drawNumberAppear used.
#
# DAILY_539: all 5 drawn numbers, single pool 1-39 (no special number).
# BIG_LOTTO: all 7 positions (6 main + 1 special), single pool 1-49 -- the
#            special number is drawn from the same 1-49 pool as the main
#            numbers, so a single 7-ball within-draw permutation namespace
#            is well-defined.
# POWER_LOTTO: only the first 6 (main) positions, pool 1-38. The 7th
#            (special) position is drawn from a disjoint, smaller pool
#            (1-8) and is EXCLUDED to avoid mixing two incompatible ball
#            namespaces under one permutation.
# 3_STAR / 4_STAR: digit positions, pool 0-9, k = 3 / 4. Digits may repeat
#            within a draw; the within-draw permutation null is still
#            well-defined as a permutation of the (possibly repeated)
#            multiset of digit identities.
GAME_CONFIG = {
    "DAILY_539": {"pool_min": 1, "pool_max": 39, "k": 5, "slice_len": 5, "role": "PRIMARY"},
    "BIG_LOTTO": {"pool_min": 1, "pool_max": 49, "k": 7, "slice_len": 7, "role": "SECONDARY_EXPLORATORY"},
    "POWER_LOTTO": {"pool_min": 1, "pool_max": 38, "k": 6, "slice_len": 6, "role": "SECONDARY_EXPLORATORY"},
    "3_STAR": {"pool_min": 0, "pool_max": 9, "k": 3, "slice_len": 3, "role": "SECONDARY_EXPLORATORY"},
    "4_STAR": {"pool_min": 0, "pool_max": 9, "k": 4, "slice_len": 4, "role": "SECONDARY_EXPLORATORY"},
}

EXCLUDED_MONTHS = {"2026-04", "2026-05"}
ESTIMATION_FRACTION = 0.7

SEED = 42
N_PERMUTATIONS_TARGET = 10000
N_PERMUTATIONS_FALLBACK = 1000
PRIMARY_ALPHA = 0.01

# If the primary-game permutation loop would take longer than this many
# seconds at the target permutation count (estimated from a small timing
# probe), fall back to N_PERMUTATIONS_FALLBACK and mark LOWER_POWER.
RUNTIME_BUDGET_SECONDS = 90.0


def load_jsonl(path: Path) -> list[dict]:
    records = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def load_json(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def append_hypothesis_registry_entry() -> dict:
    """Append the P268D-3 H1 pre-registration entry to the production
    Hypothesis Registry, BEFORE any H1 computation. Append-only; does not
    read or modify any other line in the file."""
    now = datetime.now(timezone.utc).isoformat()
    entry = {
        "hypothesis_id": HYPOTHESIS_ID,
        "task_id": "P268D3",
        "status": "PRE_REGISTERED_BEFORE_TEST",
        "registered_at": now,
        "source_artifact": str(P268D1_JSONL.relative_to(REPO_ROOT)),
        "data_quality_gate": str(P268D2_JSON.relative_to(REPO_ROOT)),
        "H1": {
            "name": "per_ball_exit_rank_heterogeneity",
            "statement": (
                "Per-ball mean exit-rank (1-based position within the "
                "drawNumberAppear draw-order sequence, conditional on the "
                "ball being drawn) is heterogeneous across balls, beyond "
                "what a within-draw fully-exchangeable permutation null "
                "predicts."
            ),
        },
        "family": {
            "primary_game": PRIMARY_GAME,
            "secondary_games": SECONDARY_GAMES,
        },
        "windows": {
            "estimation_holdout_split": "70% estimation / 30% holdout, chronological, per lottery_type",
            "excluded_months": sorted(EXCLUDED_MONTHS),
            "excluded_months_reason": "Already inspected by P268B (look-ahead avoidance per P268D1 registry-freeze).",
            "holdout_status_this_task": "SEALED_NOT_OPENED",
        },
        "null_model": {
            "type": "within_draw_permutation",
            "description": (
                "For each draw, the k drawn-ball identities (a fixed-size "
                "slice of drawNumberAppear, per-game GAME_CONFIG) are an "
                "exchangeable set; all k! orderings are equally likely under "
                "the null. Monte Carlo null generated by independently "
                "re-permuting each draw's order labels."
            ),
        },
        "statistic": {
            "name": "sum_of_squared_standardized_per_ball_mean_exit_rank",
            "description": (
                "For each ball in the pool with n_b appearances in the "
                "estimation window, standardized z_b = (mean_exit_rank_b - "
                "mu_k) / sqrt(sigma_k^2 / n_b), where mu_k=(k+1)/2 and "
                "sigma_k^2=(k^2-1)/12 are the mean/variance of a discrete "
                "Uniform{1..k}. Test statistic T = sum(z_b^2) over balls "
                "with n_b >= 1."
            ),
        },
        "correction": {
            "primary_daily_539_alpha": PRIMARY_ALPHA,
            "primary_daily_539_correction": "single pre-registered test, no cross-game Bonferroni required for H1 itself (per P268D1 registry-freeze)",
            "secondary_games_correction": "EXPLORATORY label only; no Bonferroni/BH-FDR gating applied; cannot alone promote to strategy",
        },
        "pass_fail": {
            "H1_PASS_condition": (
                f"Estimation-window one-sided permutation p < {PRIMARY_ALPHA} "
                "for DAILY_539 AND the holdout window remains unopened/unused "
                "for any H2/H3 computation in this task."
            ),
            "H1_FAIL_condition": f"Estimation-window p >= {PRIMARY_ALPHA} for DAILY_539.",
            "secondary_games_note": "Secondary-game results cannot alone promote H1 to PASS or trigger H2/H3.",
        },
        "h2_h3_run_in_this_task": False,
        "db_write_in_this_task": False,
        "strategy_generated_in_this_task": False,
        "hit_rate_claim_in_this_task": False,
        "permutation_count_target": N_PERMUTATIONS_TARGET,
        "permutation_count_fallback": N_PERMUTATIONS_FALLBACK,
        "seed": SEED,
        "validated_at": None,
        "result_summary": None,
    }
    with open(HYPOTHESIS_REGISTRY_PATH, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    return entry


def prepare_game_records(all_records: list[dict], game: str) -> dict:
    """Filter to a single game, sort chronologically, exclude EXCLUDED_MONTHS,
    and split chronologically into estimation (70%) / holdout (30%).

    The holdout slice is computed for bookkeeping/reporting only (record
    counts) and its contents are NOT used by any statistic in this task.
    """
    recs = [r for r in all_records if r["lottery_type"] == game]
    recs.sort(key=lambda r: r["draw_date"])
    eligible = [r for r in recs if r["month"] not in EXCLUDED_MONTHS]
    excluded = [r for r in recs if r["month"] in EXCLUDED_MONTHS]

    n_eligible = len(eligible)
    n_estimation = int(n_eligible * ESTIMATION_FRACTION)
    estimation = eligible[:n_estimation]
    holdout = eligible[n_estimation:]

    return {
        "game": game,
        "total_records": len(recs),
        "excluded_records": len(excluded),
        "eligible_records": n_eligible,
        "estimation_records": len(estimation),
        "holdout_records": len(holdout),
        "estimation_date_range": (
            [estimation[0]["draw_date"], estimation[-1]["draw_date"]]
            if estimation
            else None
        ),
        "holdout_date_range": (
            [holdout[0]["draw_date"], holdout[-1]["draw_date"]] if holdout else None
        ),
        "estimation_records_data": estimation,
    }


def extract_balls_matrix(records: list[dict], cfg: dict) -> np.ndarray:
    k = cfg["slice_len"]
    rows = []
    for r in records:
        seq = r["drawNumberAppear"]
        rows.append(seq[:k])
    return np.array(rows, dtype=np.int64)


def statistic_from_ranks(balls_flat: np.ndarray, ranks_flat: np.ndarray, cfg: dict) -> float:
    pool_min = cfg["pool_min"]
    pool_max = cfg["pool_max"]
    k = cfg["k"]
    pool_size = pool_max - pool_min + 1

    ids = balls_flat - pool_min
    sums = np.bincount(ids, weights=ranks_flat.astype(np.float64), minlength=pool_size)
    counts = np.bincount(ids, minlength=pool_size)

    mask = counts > 0
    means = sums[mask] / counts[mask]
    mu_k = (k + 1) / 2.0
    var_k = (k * k - 1) / 12.0
    z = (means - mu_k) / np.sqrt(var_k / counts[mask])
    return float(np.sum(z * z))


def run_h1_for_game(game: str, estimation_records: list[dict], cfg: dict, n_permutations: int, seed: int) -> dict:
    balls = extract_balls_matrix(estimation_records, cfg)
    m, k = balls.shape
    assert k == cfg["k"]

    ranks_obs = np.tile(np.arange(1, k + 1), (m, 1))
    t_obs = statistic_from_ranks(balls.flatten(), ranks_obs.flatten(), cfg)

    rng = np.random.default_rng(seed)
    null_stats = np.empty(n_permutations, dtype=np.float64)
    balls_flat = balls.flatten()
    start = time.monotonic()
    for i in range(n_permutations):
        rand_keys = rng.random((m, k))
        order = np.argsort(rand_keys, axis=1)
        ranks_perm = np.argsort(order, axis=1) + 1
        null_stats[i] = statistic_from_ranks(balls_flat, ranks_perm.flatten(), cfg)
    elapsed = time.monotonic() - start

    n_ge = int(np.sum(null_stats >= t_obs))
    p_value = (1 + n_ge) / (n_permutations + 1)

    return {
        "game": game,
        "role": cfg["role"],
        "pool_min": cfg["pool_min"],
        "pool_max": cfg["pool_max"],
        "pool_size": cfg["pool_max"] - cfg["pool_min"] + 1,
        "k": k,
        "n_draws_estimation": m,
        "observed_statistic": t_obs,
        "null_distribution_summary": {
            "n_permutations": n_permutations,
            "mean": float(np.mean(null_stats)),
            "std": float(np.std(null_stats)),
            "min": float(np.min(null_stats)),
            "max": float(np.max(null_stats)),
            "p50": float(np.percentile(null_stats, 50)),
            "p95": float(np.percentile(null_stats, 95)),
            "p99": float(np.percentile(null_stats, 99)),
        },
        "p_value_one_sided": p_value,
        "seed": seed,
        "elapsed_seconds": elapsed,
    }


def render_markdown(artifact: dict) -> str:
    lines = []
    lines.append("# P268D-3 H1 Draw-Order Confirmatory Permutation Test")
    lines.append("")
    lines.append(f"Generated: {artifact['generated_at']}")
    lines.append("")

    lines.append("## P268D-1 / P268D-2 Boundary")
    lines.append("")
    lines.append(artifact["boundary"])
    lines.append("")

    lines.append("## Hypothesis Registry Pre-Registration")
    lines.append("")
    lines.append(f"- Registry entry appended (append-only, before H1 computation): `{artifact['registry_append']['hypothesis_id']}`")
    lines.append(f"- Status: `{artifact['registry_append']['status']}`")
    lines.append(f"- Registered at: {artifact['registry_append']['registered_at']}")
    lines.append(f"- Registry path: `{artifact['registry_append']['registry_path']}`")
    lines.append("")

    lines.append("## Data Source Summary")
    lines.append("")
    lines.append(f"- Source artifact: `{artifact['data_source']['source_artifact']}`")
    lines.append(f"- DB used: {artifact['data_source']['db_used']}")
    lines.append("")

    lines.append("## Estimation / Holdout Split Summary")
    lines.append("")
    lines.append("| Game | Total | Excluded (2026-04/05) | Eligible | Estimation (70%) | Holdout (30%, sealed) |")
    lines.append("|---|---:|---:|---:|---:|---:|")
    for g in [PRIMARY_GAME] + SECONDARY_GAMES:
        s = artifact["splits"][g]
        lines.append(
            f"| {g} | {s['total_records']} | {s['excluded_records']} | {s['eligible_records']} | "
            f"{s['estimation_records']} | {s['holdout_records']} |"
        )
    lines.append("")
    lines.append("- 2026-04 and 2026-05 are excluded from the eligible set (already inspected by P268B).")
    lines.append("- The holdout window is **sealed and not used** by any statistic in this task (reserved for H1_holdout, future task).")
    lines.append("")

    lines.append("## H1 Method")
    lines.append("")
    lines.append(artifact["method"]["statistic_description"])
    lines.append("")
    lines.append(f"- Null model: {artifact['method']['null_model']}")
    lines.append(f"- Permutation count: {artifact['method']['n_permutations']} (target {N_PERMUTATIONS_TARGET}, fallback {N_PERMUTATIONS_FALLBACK})")
    lines.append(f"- Lower power fallback used: {artifact['method']['lower_power_fallback_used']}")
    lines.append(f"- Seed: {artifact['method']['seed']}")
    lines.append("")

    lines.append("## Primary Result: DAILY_539")
    lines.append("")
    p = artifact["primary_result"]
    lines.append(f"- Pool: {p['pool_min']}-{p['pool_max']} ({p['pool_size']} balls), k={p['k']}")
    lines.append(f"- Estimation-window draws: {p['n_draws_estimation']}")
    lines.append(f"- Observed statistic T_obs: {p['observed_statistic']:.6f}")
    lines.append(f"- Null distribution (n={p['null_distribution_summary']['n_permutations']}): mean={p['null_distribution_summary']['mean']:.4f}, std={p['null_distribution_summary']['std']:.4f}, p95={p['null_distribution_summary']['p95']:.4f}, p99={p['null_distribution_summary']['p99']:.4f}")
    lines.append(f"- One-sided permutation p-value: {p['p_value_one_sided']:.6f}")
    lines.append(f"- alpha (pre-registered): {PRIMARY_ALPHA}")
    lines.append(f"- Result: **{artifact['h1_classification']}**")
    lines.append("")

    lines.append("## Secondary / Exploratory Game Results")
    lines.append("")
    lines.append("**These results are SECONDARY / EXPLORATORY ONLY. They cannot alone promote H1 to PASS, change the H1 classification, or trigger H2/H3.**")
    lines.append("")
    lines.append("| Game | Pool | k | n_draws | T_obs | p-value (one-sided, exploratory) |")
    lines.append("|---|---|---:|---:|---:|---:|")
    for r in artifact["secondary_results"]:
        lines.append(
            f"| {r['game']} | {r['pool_min']}-{r['pool_max']} | {r['k']} | {r['n_draws_estimation']} | "
            f"{r['observed_statistic']:.4f} | {r['p_value_one_sided']:.6f} |"
        )
    lines.append("")

    lines.append("## Final Classification")
    lines.append("")
    lines.append(f"`{artifact['final_classification']}`")
    lines.append("")

    lines.append("## Run Booleans")
    lines.append("")
    lines.append(f"- H2/H3 run in this task: {artifact['h2_h3_run']}")
    lines.append(f"- DB write in this task: {artifact['db_write']}")
    lines.append(f"- Hypothesis Registry write in this task: {artifact['hypothesis_registry_write']} (append-only, 1 entry)")
    lines.append(f"- Strategy generated in this task: {artifact['strategy_generated']}")
    lines.append(f"- Hit-rate / success-rate improvement claim made: {artifact['hit_rate_claim']}")
    lines.append("")

    lines.append("## Next-Step Recommendation")
    lines.append("")
    lines.append(artifact["next_step_recommendation"])
    lines.append("")

    lines.append("## Explicit Non-Claims")
    lines.append("")
    for c in artifact["explicit_non_claims"]:
        lines.append(f"- {c}")
    lines.append("")

    return "\n".join(lines)


def main() -> dict:
    registry_entry = append_hypothesis_registry_entry()

    all_records = load_jsonl(P268D1_JSONL)

    splits = {}
    for game in [PRIMARY_GAME] + SECONDARY_GAMES:
        splits[game] = prepare_game_records(all_records, game)

    # Primary: DAILY_539, target permutation count, with runtime fallback.
    cfg_primary = GAME_CONFIG[PRIMARY_GAME]
    estimation_primary = splits[PRIMARY_GAME]["estimation_records_data"]

    # Timing probe with a small permutation count to estimate runtime.
    probe = run_h1_for_game(PRIMARY_GAME, estimation_primary, cfg_primary, n_permutations=200, seed=SEED)
    est_full_seconds = probe["elapsed_seconds"] / 200 * N_PERMUTATIONS_TARGET

    lower_power_fallback_used = False
    if est_full_seconds > RUNTIME_BUDGET_SECONDS:
        n_perm_primary = N_PERMUTATIONS_FALLBACK
        lower_power_fallback_used = True
    else:
        n_perm_primary = N_PERMUTATIONS_TARGET

    primary_result = run_h1_for_game(PRIMARY_GAME, estimation_primary, cfg_primary, n_permutations=n_perm_primary, seed=SEED)

    # Secondary games: same permutation count as primary (or fallback), seed offset per game.
    secondary_results = []
    for idx, game in enumerate(SECONDARY_GAMES, start=1):
        cfg = GAME_CONFIG[game]
        estimation = splits[game]["estimation_records_data"]
        n_perm = N_PERMUTATIONS_FALLBACK if lower_power_fallback_used else N_PERMUTATIONS_TARGET
        result = run_h1_for_game(game, estimation, cfg, n_permutations=n_perm, seed=SEED + idx)
        secondary_results.append(result)

    if lower_power_fallback_used:
        h1_classification = "H1_INCONCLUSIVE_RUNTIME_LIMIT"
    elif primary_result["p_value_one_sided"] < PRIMARY_ALPHA:
        h1_classification = "H1_PRIMARY_PASS"
    else:
        h1_classification = "H1_PRIMARY_FAIL"

    if h1_classification == "H1_PRIMARY_PASS":
        final_classification = "P268D3_H1_DRAW_ORDER_CONFIRMATORY_TEST_COMPLETE_PRIMARY_PASS"
        next_step = (
            "H1 estimation-window result PASSED (p < "
            f"{PRIMARY_ALPHA}) for DAILY_539. Per the registry-freeze, "
            "H1_holdout (sealed holdout window replication) is the required "
            "next gated step before H2/H3 may be considered. A separate, "
            "explicitly-authorized P268D-4 task is required for "
            "H1_holdout/H2/H3; this task does not open the holdout window."
        )
    elif h1_classification == "H1_PRIMARY_FAIL":
        final_classification = "P268D3_H1_DRAW_ORDER_CONFIRMATORY_TEST_COMPLETE_PRIMARY_FAIL"
        next_step = (
            "H1 estimation-window result FAILED (p >= "
            f"{PRIMARY_ALPHA}) for DAILY_539. Per the registry-freeze, this "
            "is a diagnostics-only NULL closure for the draw-order "
            "exit-rank-heterogeneity hypothesis: H1_holdout/H2/H3 are NOT "
            "opened, and no strategy is proposed from this line."
        )
    else:
        final_classification = "P268D3_H1_DRAW_ORDER_CONFIRMATORY_TEST_INCONCLUSIVE_RUNTIME_LIMIT"
        next_step = (
            "Permutation count was reduced to the pre-registered fallback "
            f"({N_PERMUTATIONS_FALLBACK}) due to a runtime-budget estimate "
            "exceeding the limit. Result is LOWER_POWER and inconclusive; "
            "a future task may re-run with the full permutation count on "
            "more capable hardware/runtime budget."
        )

    artifact = {
        "task_id": "P268D3",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "boundary": (
            "P268D-1 (PR #409, merged) produced the registry-freeze artifact "
            "(H1/H1_holdout/H2/H3, status=FROZEN_NOT_TESTED at that time) and "
            "the full-history drawNumberAppear backfill artifact (21,682 "
            "records, 2007-01..2026-05, 0 pending/error, 100% parse "
            "success). P268D-2 (PR #410, merged) ran a structure-validation "
            "aggregate (PASS) and a read-only DB alignment audit "
            "(PARTIAL_ENV_LIMITATION / NO_LOCAL_ROWS), concluding P268D-3 "
            "may proceed using the JSONL artifact (not the local DB) as the "
            "H1 data source."
        ),
        "registry_append": {
            "hypothesis_id": registry_entry["hypothesis_id"],
            "status": registry_entry["status"],
            "registered_at": registry_entry["registered_at"],
            "registry_path": str(HYPOTHESIS_REGISTRY_PATH.relative_to(REPO_ROOT)),
        },
        "data_source": {
            "source_artifact": str(P268D1_JSONL.relative_to(REPO_ROOT)),
            "db_used": False,
        },
        "splits": {
            g: {k: v for k, v in s.items() if k != "estimation_records_data"}
            for g, s in splits.items()
        },
        "method": {
            "statistic_description": (
                "Test statistic T = sum over balls b (with n_b >= 1 "
                "appearances in the estimation window) of "
                "z_b^2, where z_b = (mean_exit_rank_b - mu_k) / "
                "sqrt(sigma_k^2 / n_b), mu_k=(k+1)/2, sigma_k^2=(k^2-1)/12. "
                "Larger T indicates greater dispersion of per-ball mean "
                "exit-rank than expected under full within-draw "
                "exchangeability (heterogeneity)."
            ),
            "null_model": (
                "Within-draw permutation null: for each draw, the k drawn "
                "balls are assigned a uniformly random permutation of "
                "exit-ranks 1..k, independently across draws and across "
                "Monte Carlo replicates."
            ),
            "n_permutations": n_perm_primary,
            "lower_power_fallback_used": lower_power_fallback_used,
            "seed": SEED,
            "probe_estimated_full_run_seconds": est_full_seconds,
        },
        "primary_result": primary_result,
        "secondary_results": secondary_results,
        "h1_classification": h1_classification,
        "final_classification": final_classification,
        "h2_h3_run": False,
        "db_write": False,
        "hypothesis_registry_write": True,
        "strategy_generated": False,
        "hit_rate_claim": False,
        "next_step_recommendation": next_step,
        "explicit_non_claims": [
            "No H2 or H3 statistical test was run in this task.",
            "The holdout window (30%, chronologically most recent eligible draws) was not opened, read for statistics, or used in any computation in this task.",
            "No production database connection of any kind (read or write) was opened in this script.",
            "No new strategy was generated and no betting recommendation is made.",
            "No hit-rate / success-rate-improvement claim is made by this artifact, regardless of the H1 classification.",
            "Secondary/exploratory game results (BIG_LOTTO, POWER_LOTTO, 3_STAR, 4_STAR) cannot alone promote H1 to PASS or trigger H2/H3.",
        ],
    }

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(artifact, f, indent=2, ensure_ascii=False)

    md = render_markdown(artifact)
    with open(OUTPUT_MD, "w", encoding="utf-8") as f:
        f.write(md)

    print(f"Final Classification: {final_classification}")
    return artifact


if __name__ == "__main__":
    main()
